// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  getCampaigns,
  createCampaign,
  getCampaignById,
  updateCampaignById,
  deleteCampaignById,
  getRunningCampaignStats,
  getCampaignAnalytics,
  previewCampaignById,
  updatePreviewCampaignById,
  previewCampaignTextById,
  updateCampaignStatusById,
  updateCampaignArchiveById,
  createCampaignContentById,
  testCampaignById,
} from "../../../dist/methods/campaigns/part1.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getCampaigns: {
    route: "getCampaigns",
    mediaType: null,
    invoke: (bag) =>
      getCampaigns(config, {
        status: bag["status"],
        noBody: bag["no_body"],
        page: bag["page"],
        perPage: bag["per_page"],
        tags: bag["tags"],
        order: bag["order"],
        orderBy: bag["order_by"],
        query: bag["query"],
      }),
  },
  createCampaign: {
    route: "createCampaign",
    mediaType: "application/json",
    invoke: (bag) =>
      createCampaign(config, {
        name: bag.__body?.["name"],
        subject: bag.__body?.["subject"],
        lists: bag.__body?.["lists"],
        fromEmail: bag.__body?.["from_email"],
        contentType: bag.__body?.["content_type"],
        messenger: bag.__body?.["messenger"],
        ["type"]: bag.__body?.["type"],
        tags: bag.__body?.["tags"],
        sendLater: bag.__body?.["send_later"],
        sendAt: bag.__body?.["send_at"],
      }),
  },
  getCampaignById: {
    route: "getCampaignById",
    mediaType: null,
    invoke: (bag) => getCampaignById(config, { id: bag["id"], noBody: bag["no_body"] }),
  },
  updateCampaignById: {
    route: "updateCampaignById",
    mediaType: "application/json",
    invoke: (bag) =>
      updateCampaignById(config, {
        name: bag.__body?.["name"],
        subject: bag.__body?.["subject"],
        lists: bag.__body?.["lists"],
        fromEmail: bag.__body?.["from_email"],
        contentType: bag.__body?.["content_type"],
        messenger: bag.__body?.["messenger"],
        ["type"]: bag.__body?.["type"],
        tags: bag.__body?.["tags"],
        sendLater: bag.__body?.["send_later"],
        sendAt: bag.__body?.["send_at"],
        id: bag["id"],
      }),
  },
  deleteCampaignById: {
    route: "deleteCampaignById",
    mediaType: null,
    invoke: (bag) => deleteCampaignById(config, { id: bag["id"] }),
  },
  getRunningCampaignStats: {
    route: "getRunningCampaignStats",
    mediaType: null,
    invoke: (bag) => getRunningCampaignStats(config, { campaignId: bag["campaign_id"] }),
  },
  getCampaignAnalytics: {
    route: "getCampaignAnalytics",
    mediaType: null,
    invoke: (bag) =>
      getCampaignAnalytics(config, {
        ["type"]: bag["type"],
        from: bag["from"],
        to: bag["to"],
        id: bag["id"],
      }),
  },
  previewCampaignById: {
    route: "previewCampaignById",
    mediaType: null,
    invoke: (bag) => previewCampaignById(config, { id: bag["id"] }),
  },
  updatePreviewCampaignById: {
    route: "updatePreviewCampaignById",
    mediaType: "application/x-www-form-urlencoded",
    invoke: (bag) =>
      updatePreviewCampaignById(config, {
        templateId: bag.__body?.["template_id"],
        contentType: bag.__body?.["content_type"],
        body: bag.__body?.["body"],
        id: bag["id"],
      }),
  },
  previewCampaignTextById: {
    route: "previewCampaignTextById",
    mediaType: "application/x-www-form-urlencoded",
    invoke: (bag) =>
      previewCampaignTextById(config, {
        templateId: bag.__body?.["template_id"],
        contentType: bag.__body?.["content_type"],
        body: bag.__body?.["body"],
        id: bag["id"],
      }),
  },
  updateCampaignStatusById: {
    route: "updateCampaignStatusById",
    mediaType: "application/json",
    invoke: (bag) =>
      updateCampaignStatusById(config, { status: bag.__body?.["status"], id: bag["id"] }),
  },
  updateCampaignArchiveById: {
    route: "updateCampaignArchiveById",
    mediaType: "application/json",
    invoke: (bag) =>
      updateCampaignArchiveById(config, {
        archive: bag.__body?.["archive"],
        archiveTemplateId: bag.__body?.["archive_template_id"],
        archiveMeta: bag.__body?.["archive_meta"],
        id: bag["id"],
      }),
  },
  createCampaignContentById: {
    route: "createCampaignContentById",
    mediaType: "application/json",
    invoke: (bag) =>
      createCampaignContentById(config, {
        id_2: bag.__body?.["id"],
        createdAt: bag.__body?.["created_at"],
        updatedAt: bag.__body?.["updated_at"],
        campaignId: bag.__body?.["CampaignID"],
        views: bag.__body?.["views"],
        clicks: bag.__body?.["clicks"],
        lists: bag.__body?.["lists"],
        startedAt: bag.__body?.["started_at"],
        toSend: bag.__body?.["to_send"],
        sent: bag.__body?.["sent"],
        uuid: bag.__body?.["uuid"],
        ["type"]: bag.__body?.["type"],
        name: bag.__body?.["name"],
        subject: bag.__body?.["subject"],
        fromEmail: bag.__body?.["from_email"],
        body: bag.__body?.["body"],
        sendAt: bag.__body?.["send_at"],
        status: bag.__body?.["status"],
        contentType: bag.__body?.["content_type"],
        tags: bag.__body?.["tags"],
        templateId: bag.__body?.["template_id"],
        messenger: bag.__body?.["messenger"],
        from: bag.__body?.["from"],
        to: bag.__body?.["to"],
        id: bag["id"],
      }),
  },
  testCampaignById: {
    route: "testCampaignById",
    mediaType: "application/json",
    invoke: (bag) =>
      testCampaignById(config, {
        name: bag.__body?.["name"],
        subject: bag.__body?.["subject"],
        lists: bag.__body?.["lists"],
        fromEmail: bag.__body?.["from_email"],
        contentType: bag.__body?.["content_type"],
        messenger: bag.__body?.["messenger"],
        ["type"]: bag.__body?.["type"],
        tags: bag.__body?.["tags"],
        sendLater: bag.__body?.["send_later"],
        sendAt: bag.__body?.["send_at"],
        id: bag["id"],
      }),
  },
};

test("campaigns/part1 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
