// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

/**
 * Restarts the application. Use this operation to reload the application process and its configuration.
 *
 * restarts the app
 */
export async function reloadApp(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/admin/reload`,
    operationId: "reloadApp",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class AdminNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Restarts the application. Use this operation to reload the application process and its configuration.
   *
   * restarts the app
   */
  reloadApp(requestOptions?: RequestOptions): ReturnType<typeof reloadApp> {
    return reloadApp(this._config, requestOptions);
  }
}
