// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { Bounce } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";

export interface GetBouncesParams {
  campaignId?: number;
  page?: number;
  perPage?: number | "all" | (string & {});
  source?: string;
  orderBy?: "email" | "campaign_name" | "source" | "created_at" | (string & {});
  order?: "asc" | "desc" | (string & {});
}

/**
 * Lists bounce records, optionally filtered by campaign or source and sorted by a selected field. Use `page` and `per_page` to paginate the results; set `per_page` to `all` to retrieve all results without pagination.
 *
 * handles retrieval of bounce records.
 *
 * @param campaignId - Numeric identifier for retrieving bounce records
 *   associated with a specific campaign
 * @param page - Page number for paginated results. Start from 1 for the first
 *   page
 * @param perPage - Number of items per page. Use an integer for specific page
 *   size or 'all' to retrieve all results
 * @param source - Filter bounce records by their source of origin
 * @param orderBy - Specifies the field by which to sort the bounce records.
 *   Available options are 'email', 'campaign_name', 'source', and 'created_at'
 * @param order - Determines the sort order of results. Use 'asc' for ascending
 *   or 'desc' for descending order
 */
export async function getBounces(
  config: ClientConfig,
  { campaignId, page, perPage, source, orderBy, order }: GetBouncesParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: {
    results?: Bounce[];
    query?: string;
    total?: number;
    perPage?: number;
    page?: number;
  };
}> {
  const _resp = await sdkRequest<{
    data?: {
      results?: Bounce[];
      query?: string;
      total?: number;
      perPage?: number;
      page?: number;
    };
  }>({
    method: "GET",
    path: `/bounces`,
    operationId: "getBounces",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      campaign_id: queryValue(campaignId, "form", true),
      page: queryValue(page, "form", true),
      per_page: queryValue(perPage, "form", true),
      source: queryValue(source, "form", true),
      order_by: queryValue(orderBy, "form", true),
      order: queryValue(order, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface DeleteBouncesParams {
  all?: boolean;
  id?: string;
}

/**
 * Deletes bounce records selected by a deletion flag or bounce identifiers. Use `all` to indicate bulk deletion or `id` to provide the bounce identifiers to delete.
 *
 * handles deletion of bounce records.
 *
 * @param all - flag for multiple bounce record deletion
 * @param id - list of bounce ids to delete
 */
export async function deleteBounces(
  config: ClientConfig,
  { all, id }: DeleteBouncesParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/bounces`,
    operationId: "deleteBounces",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      all: queryValue(all, "form", true),
      id: queryValue(id, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetBounceByIdParams {
  id: number;
}

/**
 * Retrieves a bounce record by its identifier. Supply the record's numeric `id` to look up the bounce you want to retrieve.
 *
 * handles retrieval of bounce record by id
 *
 * @param id - The id value of the bounce you want to retreive.
 */
export async function getBounceById(
  config: ClientConfig,
  { id }: GetBounceByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Bounce;
}> {
  const _resp = await sdkRequest<{
    data?: Bounce;
  }>({
    method: "GET",
    path: `/bounces/${encodePathSegment(id)}`,
    operationId: "getBounceById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface DeleteBounceByIdParams {
  id: number;
}

/**
 * Deletes a single bounce identified by its ID in the URI. Supply the integer `id` of the bounce you want to remove.
 *
 * handles bounce deletion, either a single one (ID in the URI), or a list.
 *
 * @param id - The id value of the bounce you want to delete.
 */
export async function deleteBounceById(
  config: ClientConfig,
  { id }: DeleteBounceByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/bounces/${encodePathSegment(id)}`,
    operationId: "deleteBounceById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class BouncesNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists bounce records, optionally filtered by campaign or source and sorted by a selected field. Use `page` and `per_page` to paginate the results; set `per_page` to `all` to retrieve all results without pagination.
   *
   * handles retrieval of bounce records.
   */
  get(
    params: GetBouncesParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getBounces> {
    return getBounces(this._config, params, requestOptions);
  }
  /**
   * Deletes bounce records selected by a deletion flag or bounce identifiers. Use `all` to indicate bulk deletion or `id` to provide the bounce identifiers to delete.
   *
   * handles deletion of bounce records.
   */
  delete_(
    params: DeleteBouncesParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteBounces> {
    return deleteBounces(this._config, params, requestOptions);
  }
  /**
   * Retrieves a bounce record by its identifier. Supply the record's numeric `id` to look up the bounce you want to retrieve.
   *
   * handles retrieval of bounce record by id
   */
  getById(
    params: GetBounceByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getBounceById> {
    return getBounceById(this._config, params, requestOptions);
  }
  /**
   * Deletes a single bounce identified by its ID in the URI. Supply the integer `id` of the bounce you want to remove.
   *
   * handles bounce deletion, either a single one (ID in the URI), or a list.
   */
  deleteById(
    params: DeleteBounceByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteBounceById> {
    return deleteBounceById(this._config, params, requestOptions);
  }
}
