// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

export * from "./campaigns/part1";
export * from "./campaigns/part2";
import type { ClientConfig, RequestOptions } from "../client";

import type {
  CreateCampaignContentByIdParams,
  CreateCampaignParams,
  DeleteCampaignByIdParams,
  GetCampaignAnalyticsParams,
  GetCampaignByIdParams,
  GetCampaignsParams,
  GetRunningCampaignStatsParams,
  PreviewCampaignByIdParams,
  PreviewCampaignTextByIdParams,
  TestCampaignByIdParams,
  UpdateCampaignArchiveByIdParams,
  UpdateCampaignByIdParams,
  UpdateCampaignStatusByIdParams,
  UpdatePreviewCampaignByIdParams,
} from "./campaigns/part1";
import {
  createCampaign,
  createCampaignContentById,
  deleteCampaignById,
  getCampaignAnalytics,
  getCampaignById,
  getCampaigns,
  getRunningCampaignStats,
  previewCampaignById,
  previewCampaignTextById,
  testCampaignById,
  updateCampaignArchiveById,
  updateCampaignById,
  updateCampaignStatusById,
  updatePreviewCampaignById,
} from "./campaigns/part1";
import type { TestCampaignByIdFormParams } from "./campaigns/part2";
import { testCampaignByIdForm } from "./campaigns/part2";

export class CampaignsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists campaigns, with optional filters for status and tags and optional sorting controls. Use `query` to apply custom SQL criteria, or use `page` and `per_page` to paginate the results. Set `no_body` to true to request a response without body content.
   *
   * handles retrieval of campaigns
   */
  get(
    params: GetCampaignsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getCampaigns> {
    return getCampaigns(this._config, params, requestOptions);
  }
  /**
   * Creates a campaign from the campaign details supplied in the request body. Provide fields such as `name`, `subject`, and `lists` to define the campaign; all body fields are optional in the schema. A successful response contains the new campaign object.
   *
   * handles campaign creation
   */
  create(
    params: CreateCampaignParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createCampaign> {
    return createCampaign(this._config, params, requestOptions);
  }
  /**
   * Retrieves a campaign by its identifier. Use `id` to select the campaign, and set `no_body` to true if you want the response without body content.
   *
   * handles retrieval of campaigns.
   */
  getById(
    params: GetCampaignByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getCampaignById> {
    return getCampaignById(this._config, params, requestOptions);
  }
  /**
   * Replaces campaign details for the campaign identified by `id`. Supply the campaign fields you want to set, such as `name`, `subject`, or `lists`; the schema does not require any particular body fields. A successful response contains the updated campaign object.
   *
   * handle updation of campaign
   */
  updateById(
    params: UpdateCampaignByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateCampaignById> {
    return updateCampaignById(this._config, params, requestOptions);
  }
  /**
   * Deletes the campaign identified by `id`. Use the campaign's integer identifier to select the campaign to remove. The response contains a boolean result.
   *
   * deletes specified campaign
   */
  deleteById(
    params: DeleteCampaignByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteCampaignById> {
    return deleteCampaignById(this._config, params, requestOptions);
  }
  /**
   * Lists statistics for the campaign identified by `campaign_id`. Supply the campaign ID as a number to retrieve its running campaign statistics. The response contains statistics for the requested campaign.
   *
   * returns stats of a given set of campaign IDs.
   */
  getRunningStats(
    params: GetRunningCampaignStatsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getRunningCampaignStats> {
    return getRunningCampaignStats(this._config, params, requestOptions);
  }
  /**
   * Retrieves campaign analytics for the requested statistic type and date range. Use `type` to select links, views, clicks, or bounces, and provide `from`, `to`, and `id` to scope the results. The response contains counts over time for the specified campaign ID or IDs.
   *
   * retrieves view counts for a campaign.
   */
  getAnalytics(
    params: GetCampaignAnalyticsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getCampaignAnalytics> {
    return getCampaignAnalytics(this._config, params, requestOptions);
  }
  /**
   * Retrieves the rendered HTML preview of a campaign's body. Supply the campaign's integer `id` to select the campaign whose preview you want to view.
   *
   * renders the HTML preview of a campaign body
   */
  previewById(
    params: PreviewCampaignByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof previewCampaignById> {
    return previewCampaignById(this._config, params, requestOptions);
  }
  /**
   * Renders an HTML preview of a campaign using the supplied template and content fields. Use `id` to identify the campaign and provide the preview inputs as form-encoded fields. The request body fields are optional in the schema.
   *
   * renders the HTML preview of a campaign body
   */
  updatePreviewById(
    params: UpdatePreviewCampaignByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updatePreviewCampaignById> {
    return updatePreviewCampaignById(this._config, params, requestOptions);
  }
  /**
   * Renders a text preview of a campaign using the supplied template and content fields. Use `id` to identify the campaign and provide the preview inputs as form-encoded fields. The request body fields are optional in the schema.
   *
   * renders the HTML preview of a campaign body
   */
  previewTextById(
    params: PreviewCampaignTextByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof previewCampaignTextById> {
    return previewCampaignTextById(this._config, params, requestOptions);
  }
  /**
   * Replaces the status of a campaign. Set `status` to `scheduled`, `running`, `paused`, or `cancelled` when you want to change the campaign's state.
   *
   * handles campaign status modification
   */
  updateStatusById(
    params: UpdateCampaignStatusByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateCampaignStatusById> {
    return updateCampaignStatusById(this._config, params, requestOptions);
  }
  /**
   * Replaces the archive settings for a campaign. Use `archive` to set the archive state and `archive_template_id` or `archive_meta` to provide related archive configuration.
   *
   * handles campaign status modification
   */
  updateArchiveById(
    params: UpdateCampaignArchiveByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateCampaignArchiveById> {
    return updateCampaignArchiveById(this._config, params, requestOptions);
  }
  /**
   * Submits updated content for a campaign and converts it to the campaign's content format. Use the campaign identifier in the path and provide any campaign content fields you want to submit.
   *
   * handles campaign content (body) format conversions.
   */
  createContentById(
    params: CreateCampaignContentByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createCampaignContentById> {
    return createCampaignContentById(this._config, params, requestOptions);
  }
  /**
   * Submits a test campaign message to selected subscribers. Provide the campaign identifier and a request body with the test message configuration; the body can use JSON or form-encoded data.
   *
   * handles sending of campaign message to arbitrary subscribers for testing
   */
  testById(
    params: TestCampaignByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof testCampaignById> {
    return testCampaignById(this._config, params, requestOptions);
  }
  /**
   * Submits a test campaign message to selected subscribers. Provide the campaign identifier and a request body with the test message configuration; the body can use JSON or form-encoded data.
   *
   * handles sending of campaign message to arbitrary subscribers for testing
   */
  testByIdForm(
    params: TestCampaignByIdFormParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof testCampaignByIdForm> {
    return testCampaignByIdForm(this._config, params, requestOptions);
  }
}
