// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ImportStatus } from "../types/import";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

/**
 * Retrieves the current status of subscriber imports. Use this endpoint to check the import status without submitting an import request.
 *
 * returns import status.
 */
export async function getImportSubscribers(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: ImportStatus;
}> {
  const _resp = await sdkRequest<{
    data?: ImportStatus;
  }>({
    method: "GET",
    path: `/import/subscribers`,
    operationId: "getImportSubscribers",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface ImportSubscribersParams {
  params?: string;
  file?: Blob | File;
}

/**
 * Uploads and imports a ZIP file containing one or more CSV files of subscribers. Send the upload as `multipart/form-data`; `params` can contain import settings as a JSON string. Use GET /import/subscribers to retrieve import status.
 *
 * handles the uploading and bulk importing of a ZIP file of one or more CSV files.
 *
 * @param params - JSON string containing import parameters for more detail
 *   https://listmonk.app/docs/apis/import/#params-json-string
 * @param file - File for upload.
 */
export async function importSubscribers(
  config: ClientConfig,
  { params, file }: ImportSubscribersParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: ImportStatus;
}> {
  const _resp = await sdkRequest<{
    data?: ImportStatus;
  }>({
    method: "POST",
    path: `/import/subscribers`,
    operationId: "importSubscribers",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      params,
      file,
    },
    contentType: "multipart/form-data",
    config,
  });
  return _resp.data;
}

/**
 * Sends a stop signal to the subscriber importer. Use this endpoint to request that an ongoing import stop.
 *
 * sends a stop signal to the importer.
 */
export async function stopImportSubscribers(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: ImportStatus;
}> {
  const _resp = await sdkRequest<{
    data?: ImportStatus;
  }>({
    method: "DELETE",
    path: `/import/subscribers`,
    operationId: "stopImportSubscribers",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Retrieves logs from an ongoing subscriber import. Use this endpoint to inspect import activity while the import is running.
 *
 * returns import logs from an ongoing import
 */
export async function getImportSubscriberLogs(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: string;
}> {
  const _resp = await sdkRequest<{
    data?: string;
  }>({
    method: "GET",
    path: `/import/subscribers/logs`,
    operationId: "getImportSubscriberLogs",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class ImportNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves the current status of subscriber imports. Use this endpoint to check the import status without submitting an import request.
   *
   * returns import status.
   */
  getSubscribers(requestOptions?: RequestOptions): ReturnType<typeof getImportSubscribers> {
    return getImportSubscribers(this._config, requestOptions);
  }
  /**
   * Uploads and imports a ZIP file containing one or more CSV files of subscribers. Send the upload as `multipart/form-data`; `params` can contain import settings as a JSON string. Use GET /import/subscribers to retrieve import status.
   *
   * handles the uploading and bulk importing of a ZIP file of one or more CSV files.
   */
  subscribers(
    params: ImportSubscribersParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof importSubscribers> {
    return importSubscribers(this._config, params, requestOptions);
  }
  /**
   * Sends a stop signal to the subscriber importer. Use this endpoint to request that an ongoing import stop.
   *
   * sends a stop signal to the importer.
   */
  stopSubscribers(requestOptions?: RequestOptions): ReturnType<typeof stopImportSubscribers> {
    return stopImportSubscribers(this._config, requestOptions);
  }
  /**
   * Retrieves logs from an ongoing subscriber import. Use this endpoint to inspect import activity while the import is running.
   *
   * returns import logs from an ongoing import
   */
  getSubscriberLogs(requestOptions?: RequestOptions): ReturnType<typeof getImportSubscriberLogs> {
    return getImportSubscriberLogs(this._config, requestOptions);
  }
}
