// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ListModel, NewList } from "../types/lists";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";

export interface GetListsParams {
  page?: number;
  perPage?: number | "all" | (string & {});
  query?: string;
  orderBy?: "name" | "status" | "created_at" | "updated_at" | (string & {});
  order?: "ASC" | "DESC" | (string & {});
  minimal?: boolean;
  tag?: string[];
}

/**
 * Lists mailing lists with metadata such as subscriber counts. Use `query` to search by list name, `tag` to filter by tags, and `order_by` and `order` to control sorting. Use `page` and `per_page` to paginate the results.
 *
 * retrieves lists with additional metadata like subscriber counts. This may be slow.
 *
 * @param page - total number of pages
 * @param perPage - number of items per page
 * @param query - Optional string to search a list by name.
 * @param orderBy - Field to sort results by. name|status|created_at|updated_at
 * @param order - ASC|DESC Sort by ascending or descending order.
 * @param minimal - When set to true, returns response without body content
 * @param tag - Tags to filter lists. Repeat in the query for multiple values.
 */
export async function getLists(
  config: ClientConfig,
  { page, perPage, query, orderBy, order, minimal, tag }: GetListsParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: {
    results?: ListModel[];
    total?: number;
    perPage?: number;
    page?: number;
  };
}> {
  const _resp = await sdkRequest<{
    data?: {
      results?: ListModel[];
      total?: number;
      perPage?: number;
      page?: number;
    };
  }>({
    method: "GET",
    path: `/lists`,
    operationId: "getLists",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      page: queryValue(page, "form", true),
      per_page: queryValue(perPage, "form", true),
      query: queryValue(query, "form", true),
      order_by: queryValue(orderBy, "form", true),
      order: queryValue(order, "form", true),
      minimal: queryValue(minimal, "form", true),
      tag: queryValue(tag, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type CreateListParams = NewList;

/**
 * Creates a mailing list from the supplied list details. Provide `name`, `type`, `optin`, `tags`, or `description` as needed; `type` and `optin` have defined accepted values. The response includes the created list and its metadata.
 *
 * handles list creation
 *
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param type_ - Optional enumerated value serialized in the `type` wire field.
 * @param optin - Optional enumerated value serialized in the `optin` wire field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 */
export async function createList(
  config: ClientConfig,
  { name, type: type_, optin, tags, description }: CreateListParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: ListModel;
}> {
  const _resp = await sdkRequest<{
    data?: ListModel;
  }>({
    method: "POST",
    path: `/lists`,
    operationId: "createList",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      ["type"]: type_,
      optin,
      tags,
      description,
    },
    config,
  });
  return _resp.data;
}

export interface GetListByIdParams {
  listId: number;
}

/**
 * Retrieves a mailing list with metadata such as its subscriber count. Supply the list's integer `list_id` to identify the list to retrieve.
 *
 * retrieves lists with additional metadata like subscriber counts. This may be slow.
 *
 * @param listId - The id value of the list you want to retreive.
 */
export async function getListById(
  config: ClientConfig,
  { listId }: GetListByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: ListModel;
}> {
  const _resp = await sdkRequest<{
    data?: ListModel;
  }>({
    method: "GET",
    path: `/lists/${encodePathSegment(listId)}`,
    operationId: "getListById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdateListByIdParams = ListModel & {
  listId: number;
};

/**
 * Replaces the supplied fields on a mailing list identified by its ID. The request body can include list settings, tags, and metadata; all body fields are optional in the schema.
 *
 * handles list modification
 *
 * @param listId - The id value of the list you want to update
 * @param id - Optional `integer` value serialized in the `id` wire field.
 * @param createdAt - Optional `string` value serialized in the `created_at` wire
 *   field.
 * @param updatedAt - Optional `string` value serialized in the `updated_at` wire
 *   field.
 * @param uuid - Optional `string` value serialized in the `uuid` wire field.
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param optin - Optional `string` value serialized in the `optin` wire field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param subscriberCount - Optional `integer` value serialized in the
 *   `subscriber_count` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 */
export async function updateListById(
  config: ClientConfig,
  {
    listId,
    id,
    createdAt,
    updatedAt,
    uuid,
    name,
    type: type_,
    optin,
    tags,
    subscriberCount,
    description,
  }: UpdateListByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: ListModel;
}> {
  const _resp = await sdkRequest<{
    data?: ListModel;
  }>({
    method: "PUT",
    path: `/lists/${encodePathSegment(listId)}`,
    operationId: "updateListById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      id,
      created_at: createdAt,
      updated_at: updatedAt,
      uuid,
      name,
      ["type"]: type_,
      optin,
      tags,
      subscriber_count: subscriberCount,
      description,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteListByIdParams {
  listId: number;
}

/**
 * Deletes a mailing list identified by its ID in the URI. Supply the list's integer `list_id` to specify which list to remove.
 *
 * handles list deletion, either a single one (ID in the URI), or a list.
 *
 * @param listId - The id value of the lists you want to delete.
 */
export async function deleteListById(
  config: ClientConfig,
  { listId }: DeleteListByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/lists/${encodePathSegment(listId)}`,
    operationId: "deleteListById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class ListsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists mailing lists with metadata such as subscriber counts. Use `query` to search by list name, `tag` to filter by tags, and `order_by` and `order` to control sorting. Use `page` and `per_page` to paginate the results.
   *
   * retrieves lists with additional metadata like subscriber counts. This may be slow.
   */
  get(params: GetListsParams = {}, requestOptions?: RequestOptions): ReturnType<typeof getLists> {
    return getLists(this._config, params, requestOptions);
  }
  /**
   * Creates a mailing list from the supplied list details. Provide `name`, `type`, `optin`, `tags`, or `description` as needed; `type` and `optin` have defined accepted values. The response includes the created list and its metadata.
   *
   * handles list creation
   */
  create(
    params: CreateListParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createList> {
    return createList(this._config, params, requestOptions);
  }
  /**
   * Retrieves a mailing list with metadata such as its subscriber count. Supply the list's integer `list_id` to identify the list to retrieve.
   *
   * retrieves lists with additional metadata like subscriber counts. This may be slow.
   */
  getById(
    params: GetListByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getListById> {
    return getListById(this._config, params, requestOptions);
  }
  /**
   * Replaces the supplied fields on a mailing list identified by its ID. The request body can include list settings, tags, and metadata; all body fields are optional in the schema.
   *
   * handles list modification
   */
  updateById(
    params: UpdateListByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateListById> {
    return updateListById(this._config, params, requestOptions);
  }
  /**
   * Deletes a mailing list identified by its ID in the URI. Supply the list's integer `list_id` to specify which list to remove.
   *
   * handles list deletion, either a single one (ID in the URI), or a list.
   */
  deleteById(
    params: DeleteListByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteListById> {
    return deleteListById(this._config, params, requestOptions);
  }
}
