// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

/**
 * Lists log entries currently stored in the log buffer. Use this endpoint to retrieve the buffered entries as an array of strings.
 *
 * returns the log entries stored in the log buffer
 */
export async function getLogs(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: string[];
}> {
  const _resp = await sdkRequest<{
    data?: string[];
  }>({
    method: "GET",
    path: `/logs`,
    operationId: "getLogs",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class LogsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists log entries currently stored in the log buffer. Use this endpoint to retrieve the buffered entries as an array of strings.
   *
   * returns the log entries stored in the log buffer
   */
  get(requestOptions?: RequestOptions): ReturnType<typeof getLogs> {
    return getLogs(this._config, requestOptions);
  }
}
