// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateDate } from "../validation";

export interface DeleteGcSubscribersParams {
  type: string;
}

/**
 * Deletes orphaned or blocklisted subscribers through garbage collection. Specify the subscriber category to collect with the `type` path parameter.
 *
 * garbage collects (deletes) orphaned or blocklisted subscribers.
 *
 * @param type_ - type of GC collected subscribers
 */
export async function deleteGcSubscribers(
  config: ClientConfig,
  { type: type_ }: DeleteGcSubscribersParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: {
    count?: number;
  };
}> {
  const _resp = await sdkRequest<{
    data?: {
      count?: number;
    };
  }>({
    method: "DELETE",
    path: `/maintenance/subscribers/${encodePathSegment(type_)}`,
    operationId: "deleteGcSubscribers",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface DeleteCampaignAnalyticsByTypeParams {
  type: string;
  beforeDate?: string;
}

/**
 * Deletes campaign analytics of the specified type. Use `before_date` to set the date cutoff for the analytics to remove.
 *
 * garbage collects (deletes) campaign analytics.
 *
 * @param type_ - type of GC collected subscribers
 */
export async function deleteCampaignAnalyticsByType(
  config: ClientConfig,
  { type: type_, beforeDate }: DeleteCampaignAnalyticsByTypeParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  if (beforeDate != null) {
    validateDate("before_date", beforeDate);
  }

  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/maintenance/analytics/${encodePathSegment(type_)}`,
    operationId: "deleteCampaignAnalyticsByType",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      before_date: beforeDate,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

export interface DeleteUnconfirmedSubscriptionsParams {
  beforeDate?: string;
}

/**
 * Deletes unconfirmed subscriptions through garbage collection. Use `before_date` to set the cutoff date for the subscriptions to remove.
 *
 * garbage collects (deletes) orphaned or blocklisted subscribers.
 */
export async function deleteUnconfirmedSubscriptions(
  config: ClientConfig,
  { beforeDate }: DeleteUnconfirmedSubscriptionsParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: {
    count?: number;
  };
}> {
  if (beforeDate != null) {
    validateDate("before_date", beforeDate);
  }

  const _resp = await sdkRequest<{
    data?: {
      count?: number;
    };
  }>({
    method: "DELETE",
    path: `/maintenance/subscriptions/unconfirmed`,
    operationId: "deleteUnconfirmedSubscriptions",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      before_date: beforeDate,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

export class MaintenanceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Deletes orphaned or blocklisted subscribers through garbage collection. Specify the subscriber category to collect with the `type` path parameter.
   *
   * garbage collects (deletes) orphaned or blocklisted subscribers.
   */
  deleteGcSubscribers(
    params: DeleteGcSubscribersParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteGcSubscribers> {
    return deleteGcSubscribers(this._config, params, requestOptions);
  }
  /**
   * Deletes campaign analytics of the specified type. Use `before_date` to set the date cutoff for the analytics to remove.
   *
   * garbage collects (deletes) campaign analytics.
   */
  deleteCampaignAnalyticsByType(
    params: DeleteCampaignAnalyticsByTypeParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteCampaignAnalyticsByType> {
    return deleteCampaignAnalyticsByType(this._config, params, requestOptions);
  }
  /**
   * Deletes unconfirmed subscriptions through garbage collection. Use `before_date` to set the cutoff date for the subscriptions to remove.
   *
   * garbage collects (deletes) orphaned or blocklisted subscribers.
   */
  deleteUnconfirmedSubscriptions(
    params: DeleteUnconfirmedSubscriptionsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteUnconfirmedSubscriptions> {
    return deleteUnconfirmedSubscriptions(this._config, params, requestOptions);
  }
}
