// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { MediaFileObject } from "../types/media";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";

/**
 * Lists uploaded media. Use this endpoint to retrieve the available media records and their file details.
 *
 * handles retrieval of uploaded media.
 */
export async function getMedia(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: MediaFileObject[];
}> {
  const _resp = await sdkRequest<{
    data?: MediaFileObject[];
  }>({
    method: "GET",
    path: `/media`,
    operationId: "getMedia",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Uploads a media file. Send the file as a binary value using `multipart/form-data`; the request body schema does not define additional metadata fields.
 *
 * handles media file uploads.
 */
export async function uploadMedia(
  config: ClientConfig,
  body: Uint8Array,
  requestOptions?: RequestOptions,
): Promise<{
  data?: MediaFileObject;
}> {
  const _resp = await sdkRequest<{
    data?: MediaFileObject;
  }>({
    method: "POST",
    path: `/media`,
    operationId: "uploadMedia",
    responseDecoder: "json",
    ...requestOptions,
    body,
    contentType: "multipart/form-data",
    config,
  });
  return _resp.data;
}

export interface GetMediaByIdParams {
  id: number;
}

/**
 * Retrieves an uploaded media record by its identifier. Use the media identifier to access the record's file details and URLs.
 *
 * handles retrieval of uploaded media.
 *
 * @param id - media file id
 */
export async function getMediaById(
  config: ClientConfig,
  { id }: GetMediaByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: MediaFileObject;
}> {
  const _resp = await sdkRequest<{
    data?: MediaFileObject;
  }>({
    method: "GET",
    path: `/media/${encodePathSegment(id)}`,
    operationId: "getMediaById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface DeleteMediaByIdParams {
  id: number;
}

/**
 * Deletes an uploaded media record. Supply the media identifier for the record you want to remove.
 *
 * handles deletion of uploaded media.
 *
 * @param id - The id value of the list you want to delete.
 */
export async function deleteMediaById(
  config: ClientConfig,
  { id }: DeleteMediaByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/media/${encodePathSegment(id)}`,
    operationId: "deleteMediaById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class MediaNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists uploaded media. Use this endpoint to retrieve the available media records and their file details.
   *
   * handles retrieval of uploaded media.
   */
  get(requestOptions?: RequestOptions): ReturnType<typeof getMedia> {
    return getMedia(this._config, requestOptions);
  }
  /**
   * Uploads a media file. Send the file as a binary value using `multipart/form-data`; the request body schema does not define additional metadata fields.
   *
   * handles media file uploads.
   */
  upload(body: Uint8Array, requestOptions?: RequestOptions): ReturnType<typeof uploadMedia> {
    return uploadMedia(this._config, body, requestOptions);
  }
  /**
   * Retrieves an uploaded media record by its identifier. Use the media identifier to access the record's file details and URLs.
   *
   * handles retrieval of uploaded media.
   */
  getById(
    params: GetMediaByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getMediaById> {
    return getMediaById(this._config, params, requestOptions);
  }
  /**
   * Deletes an uploaded media record. Supply the media identifier for the record you want to remove.
   *
   * handles deletion of uploaded media.
   */
  deleteById(
    params: DeleteMediaByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteMediaById> {
    return deleteMediaById(this._config, params, requestOptions);
  }
}
