// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { DashboardChart, DashboardCount, LanguagePack, ServerConfig } from "../types/miscellaneous";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";

/**
 * Returns the service health-check result. Use the boolean `data` value to determine whether the service is responding.
 *
 * healthcheck endpoint
 */
export async function getHealthCheck(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "GET",
    path: `/health`,
    operationId: "getHealthCheck",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Returns the general server configuration. Use this endpoint to retrieve the configuration object exposed by the server.
 *
 * returns general server config.
 */
export async function getServerConfig(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: ServerConfig;
}> {
  const _resp = await sdkRequest<{
    data?: ServerConfig;
  }>({
    method: "GET",
    path: `/config`,
    operationId: "getServerConfig",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface GetI18nLangParams {
  lang: string;
}

/**
 * Returns the JSON language pack for the requested language code. Supply `lang` to select the language pack to retrieve.
 *
 * returns the JSON language pack given the language code
 *
 * @param lang - JSON language pack required
 */
export async function getI18nLang(
  config: ClientConfig,
  { lang }: GetI18nLangParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: LanguagePack;
}> {
  const _resp = await sdkRequest<{
    data?: LanguagePack;
  }>({
    method: "GET",
    path: `/lang/${encodePathSegment(lang)}`,
    operationId: "getI18nLang",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Returns chart data points for the dashboard. Use the `link_clicks` and `campaign_views` data to render the corresponding dashboard charts.
 *
 * returns chart data points to render on the dashboard.
 */
export async function getDashboardCharts(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: DashboardChart;
}> {
  const _resp = await sdkRequest<{
    data?: DashboardChart;
  }>({
    method: "GET",
    path: `/dashboard/charts`,
    operationId: "getDashboardCharts",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Returns statistics counts for the dashboard. Use the returned counts to display summary statistics in the dashboard.
 *
 * returns stats counts to show on the dashboard
 */
export async function getDashboardCounts(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: DashboardCount;
}> {
  const _resp = await sdkRequest<{
    data?: DashboardCount;
  }>({
    method: "GET",
    path: `/dashboard/counts`,
    operationId: "getDashboardCounts",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class MiscellaneousNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns the service health-check result. Use the boolean `data` value to determine whether the service is responding.
   *
   * healthcheck endpoint
   */
  getHealthCheck(requestOptions?: RequestOptions): ReturnType<typeof getHealthCheck> {
    return getHealthCheck(this._config, requestOptions);
  }
  /**
   * Returns the general server configuration. Use this endpoint to retrieve the configuration object exposed by the server.
   *
   * returns general server config.
   */
  getServerConfig(requestOptions?: RequestOptions): ReturnType<typeof getServerConfig> {
    return getServerConfig(this._config, requestOptions);
  }
  /**
   * Returns the JSON language pack for the requested language code. Supply `lang` to select the language pack to retrieve.
   *
   * returns the JSON language pack given the language code
   */
  getI18nLang(
    params: GetI18nLangParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getI18nLang> {
    return getI18nLang(this._config, params, requestOptions);
  }
  /**
   * Returns chart data points for the dashboard. Use the `link_clicks` and `campaign_views` data to render the corresponding dashboard charts.
   *
   * returns chart data points to render on the dashboard.
   */
  getDashboardCharts(requestOptions?: RequestOptions): ReturnType<typeof getDashboardCharts> {
    return getDashboardCharts(this._config, requestOptions);
  }
  /**
   * Returns statistics counts for the dashboard. Use the returned counts to display summary statistics in the dashboard.
   *
   * returns stats counts to show on the dashboard
   */
  getDashboardCounts(requestOptions?: RequestOptions): ReturnType<typeof getDashboardCounts> {
    return getDashboardCounts(this._config, requestOptions);
  }
}
