// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

/**
 * Lists the public mailing lists with their minimal identifying fields. Use this endpoint to retrieve each list's `uuid` and `name` for display or subscription workflows.
 *
 * returns the list of public lists with minimal fields
 */
export async function getPublicLists(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<
  {
    uuid?: string;
    name?: string;
  }[]
> {
  const _resp = await sdkRequest<
    {
      uuid?: string;
      name?: string;
    }[]
  >({
    method: "GET",
    path: `/public/lists`,
    operationId: "getPublicLists",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface HandlePublicSubscriptionParams {
  name?: string;
  email?: string;
  listUuids?: string[];
}

/**
 * Submits a subscription request through the public API. Include `email` and optionally `name` and `list_uuids` in the request body; the schema does not mark any fields as required. A 200 response indicates whether opt-in is required in `has_optin`.
 *
 * handles subscription requests coming from public API calls.
 */
export async function handlePublicSubscription(
  config: ClientConfig,
  { name, email, listUuids }: HandlePublicSubscriptionParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  hasOptin?: boolean;
}> {
  const _resp = await sdkRequest<{
    hasOptin?: boolean;
  }>({
    method: "POST",
    path: `/public/subscription`,
    operationId: "handlePublicSubscription",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      email,
      list_uuids: listUuids,
    },
    config,
  });
  return _resp.data;
}

export class PublicNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists the public mailing lists with their minimal identifying fields. Use this endpoint to retrieve each list's `uuid` and `name` for display or subscription workflows.
   *
   * returns the list of public lists with minimal fields
   */
  getLists(requestOptions?: RequestOptions): ReturnType<typeof getPublicLists> {
    return getPublicLists(this._config, requestOptions);
  }
  /**
   * Submits a subscription request through the public API. Include `email` and optionally `name` and `list_uuids` in the request body; the schema does not mark any fields as required. A 200 response indicates whether opt-in is required in `has_optin`.
   *
   * handles subscription requests coming from public API calls.
   */
  handleSubscription(
    params: HandlePublicSubscriptionParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof handlePublicSubscription> {
    return handlePublicSubscription(this._config, params, requestOptions);
  }
}
