// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { SMTPTest, Settings } from "../types/settings";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest, toWire } from "../client";

/**
 * Returns the settings stored in the database. Use this endpoint to retrieve the server's current configuration settings.
 *
 * returns settings from DB
 */
export async function getSettings(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Settings;
}> {
  const _resp = await sdkRequest<{
    data?: Settings;
  }>({
    method: "GET",
    path: `/settings`,
    operationId: "getSettings",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdateSettingsParams = Settings;

/**
 * Updates settings stored in the database. Supply the settings fields you want to update; each listed field is optional.
 *
 * returns updated settings from the DB.
 *
 * @param appSiteName - Optional `string` value serialized in the `app.site_name`
 *   wire field.
 * @param appRootUrl - Optional `string` value serialized in the `app.root_url`
 *   wire field.
 * @param appLogoUrl - Optional `string` value serialized in the `app.logo_url`
 *   wire field.
 * @param appFaviconUrl - Optional `string` value serialized in the
 *   `app.favicon_url` wire field.
 * @param appFromEmail - Optional `string` value serialized in the
 *   `app.from_email` wire field.
 * @param appNotifyEmails - Optional array value serialized in the
 *   `app.notify_emails` wire field.
 * @param appEnablePublicSubscriptionPage - Optional `boolean` value serialized
 *   in the `app.enable_public_subscription_page` wire field.
 * @param appEnablePublicArchive - Optional `boolean` value serialized in the
 *   `app.enable_public_archive` wire field.
 * @param appSendOptinConfirmation - Optional `boolean` value serialized in the
 *   `app.send_optin_confirmation` wire field.
 * @param appCheckUpdates - Optional `boolean` value serialized in the
 *   `app.check_updates` wire field.
 * @param appLang - Optional `string` value serialized in the `app.lang` wire
 *   field.
 * @param appBatchSize - Optional `integer` value serialized in the
 *   `app.batch_size` wire field.
 * @param appConcurrency - Optional `integer` value serialized in the
 *   `app.concurrency` wire field.
 * @param appMaxSendErrors - Optional `integer` value serialized in the
 *   `app.max_send_errors` wire field.
 * @param appMessageRate - Optional `integer` value serialized in the
 *   `app.message_rate` wire field.
 * @param appMessageSlidingWindow - Optional `boolean` value serialized in the
 *   `app.message_sliding_window` wire field.
 * @param appMessageSlidingWindowDuration - Optional `string` value serialized in
 *   the `app.message_sliding_window_duration` wire field.
 * @param appMessageSlidingWindowRate - Optional `integer` value serialized in
 *   the `app.message_sliding_window_rate` wire field.
 * @param privacyIndividualTracking - Optional `boolean` value serialized in the
 *   `privacy.individual_tracking` wire field.
 * @param privacyUnsubscribeHeader - Optional `boolean` value serialized in the
 *   `privacy.unsubscribe_header` wire field.
 * @param privacyAllowBlocklist - Optional `boolean` value serialized in the
 *   `privacy.allow_blocklist` wire field.
 * @param privacyAllowPreferences - Optional `boolean` value serialized in the
 *   `privacy.allow_preferences` wire field.
 * @param privacyAllowExport - Optional `boolean` value serialized in the
 *   `privacy.allow_export` wire field.
 * @param privacyAllowWipe - Optional `boolean` value serialized in the
 *   `privacy.allow_wipe` wire field.
 * @param privacyExportable - Optional array value serialized in the
 *   `privacy.exportable` wire field.
 * @param privacyDomainBlocklist - Optional array value serialized in the
 *   `privacy.domain_blocklist` wire field.
 * @param uploadProvider - Optional `string` value serialized in the
 *   `upload.provider` wire field.
 * @param uploadFilesystemUploadPath - Optional `string` value serialized in the
 *   `upload.filesystem.upload_path` wire field.
 * @param uploadFilesystemUploadUri - Optional `string` value serialized in the
 *   `upload.filesystem.upload_uri` wire field.
 * @param uploadS3Url - Optional `string` value serialized in the `upload.s3.url`
 *   wire field.
 * @param uploadS3PublicUrl - Optional `string` value serialized in the
 *   `upload.s3.public_url` wire field.
 * @param uploadS3AwsAccessKeyId - Optional `string` value serialized in the
 *   `upload.s3.aws_access_key_id` wire field.
 * @param uploadS3AwsDefaultRegion - Optional `string` value serialized in the
 *   `upload.s3.aws_default_region` wire field.
 * @param uploadS3Bucket - Optional `string` value serialized in the
 *   `upload.s3.bucket` wire field.
 * @param uploadS3BucketDomain - Optional `string` value serialized in the
 *   `upload.s3.bucket_domain` wire field.
 * @param uploadS3BucketPath - Optional `string` value serialized in the
 *   `upload.s3.bucket_path` wire field.
 * @param uploadS3BucketType - Optional `string` value serialized in the
 *   `upload.s3.bucket_type` wire field.
 * @param uploadS3Expiry - Optional `string` value serialized in the
 *   `upload.s3.expiry` wire field.
 * @param smtp - Optional array value serialized in the `smtp` wire field.
 * @param messengers - Optional array value serialized in the `messengers` wire
 *   field.
 * @param bounceEnabled - Optional `boolean` value serialized in the
 *   `bounce.enabled` wire field.
 * @param bounceWebhooksEnabled - Optional `boolean` value serialized in the
 *   `bounce.webhooks_enabled` wire field.
 * @param bounceCount - Optional `integer` value serialized in the `bounce.count`
 *   wire field.
 * @param bounceAction - Optional `string` value serialized in the
 *   `bounce.action` wire field.
 * @param bounceSesEnabled - Optional `boolean` value serialized in the
 *   `bounce.ses_enabled` wire field.
 * @param bounceAzureEnabled - Optional `boolean` value serialized in the
 *   `bounce.azure.enabled` wire field.
 * @param bounceAzureSharedSecret - Optional `string` value serialized in the
 *   `bounce.azure.shared_secret` wire field.
 * @param bounceAzureSharedSecretHeader - Optional `string` value serialized in
 *   the `bounce.azure.shared_secret_header` wire field.
 * @param bounceSendgridEnabled - Optional `boolean` value serialized in the
 *   `bounce.sendgrid_enabled` wire field.
 * @param bounceSendgridKey - Optional `string` value serialized in the
 *   `bounce.sendgrid_key` wire field.
 * @param bounceForwardemailEnabled - Optional `boolean` value serialized in the
 *   `bounce.forwardemail_enabled` wire field.
 * @param bounceForwardemailKey - Optional `string` value serialized in the
 *   `bounce.forwardemail_key` wire field.
 * @param bouncePostmarkEnabled - Optional `boolean` value serialized in the
 *   `bounce.postmark_enabled` wire field.
 * @param bouncePostmarkUsername - Optional `string` value serialized in the
 *   `bounce.postmark_username` wire field.
 * @param bouncePostmarkPassword - Optional `string` value serialized in the
 *   `bounce.postmark_password` wire field.
 * @param bounceMailboxes - Optional array value serialized in the
 *   `bounce.mailboxes` wire field.
 * @param appearanceAdminCustomCss - Optional `string` value serialized in the
 *   `appearance.admin.custom_css` wire field.
 * @param appearanceAdminCustomJs - Optional `string` value serialized in the
 *   `appearance.admin.custom_js` wire field.
 * @param appearancePublicCustomCss - Optional `string` value serialized in the
 *   `appearance.public.custom_css` wire field.
 * @param appearancePublicCustomJs - Optional `string` value serialized in the
 *   `appearance.public.custom_js` wire field.
 */
export async function updateSettings(
  config: ClientConfig,
  {
    appSiteName,
    appRootUrl,
    appLogoUrl,
    appFaviconUrl,
    appFromEmail,
    appNotifyEmails,
    appEnablePublicSubscriptionPage,
    appEnablePublicArchive,
    appSendOptinConfirmation,
    appCheckUpdates,
    appLang,
    appBatchSize,
    appConcurrency,
    appMaxSendErrors,
    appMessageRate,
    appMessageSlidingWindow,
    appMessageSlidingWindowDuration,
    appMessageSlidingWindowRate,
    privacyIndividualTracking,
    privacyUnsubscribeHeader,
    privacyAllowBlocklist,
    privacyAllowPreferences,
    privacyAllowExport,
    privacyAllowWipe,
    privacyExportable,
    privacyDomainBlocklist,
    uploadProvider,
    uploadFilesystemUploadPath,
    uploadFilesystemUploadUri,
    uploadS3Url,
    uploadS3PublicUrl,
    uploadS3AwsAccessKeyId,
    uploadS3AwsDefaultRegion,
    uploadS3Bucket,
    uploadS3BucketDomain,
    uploadS3BucketPath,
    uploadS3BucketType,
    uploadS3Expiry,
    smtp,
    messengers,
    bounceEnabled,
    bounceWebhooksEnabled,
    bounceCount,
    bounceAction,
    bounceSesEnabled,
    bounceAzureEnabled,
    bounceAzureSharedSecret,
    bounceAzureSharedSecretHeader,
    bounceSendgridEnabled,
    bounceSendgridKey,
    bounceForwardemailEnabled,
    bounceForwardemailKey,
    bouncePostmarkEnabled,
    bouncePostmarkUsername,
    bouncePostmarkPassword,
    bounceMailboxes,
    appearanceAdminCustomCss,
    appearanceAdminCustomJs,
    appearancePublicCustomCss,
    appearancePublicCustomJs,
  }: UpdateSettingsParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/settings`,
    operationId: "updateSettings",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      ["app.site_name"]: appSiteName,
      ["app.root_url"]: appRootUrl,
      ["app.logo_url"]: appLogoUrl,
      ["app.favicon_url"]: appFaviconUrl,
      ["app.from_email"]: appFromEmail,
      ["app.notify_emails"]: appNotifyEmails,
      ["app.enable_public_subscription_page"]: appEnablePublicSubscriptionPage,
      ["app.enable_public_archive"]: appEnablePublicArchive,
      ["app.send_optin_confirmation"]: appSendOptinConfirmation,
      ["app.check_updates"]: appCheckUpdates,
      ["app.lang"]: appLang,
      ["app.batch_size"]: appBatchSize,
      ["app.concurrency"]: appConcurrency,
      ["app.max_send_errors"]: appMaxSendErrors,
      ["app.message_rate"]: appMessageRate,
      ["app.message_sliding_window"]: appMessageSlidingWindow,
      ["app.message_sliding_window_duration"]: appMessageSlidingWindowDuration,
      ["app.message_sliding_window_rate"]: appMessageSlidingWindowRate,
      ["privacy.individual_tracking"]: privacyIndividualTracking,
      ["privacy.unsubscribe_header"]: privacyUnsubscribeHeader,
      ["privacy.allow_blocklist"]: privacyAllowBlocklist,
      ["privacy.allow_preferences"]: privacyAllowPreferences,
      ["privacy.allow_export"]: privacyAllowExport,
      ["privacy.allow_wipe"]: privacyAllowWipe,
      ["privacy.exportable"]: privacyExportable,
      ["privacy.domain_blocklist"]: privacyDomainBlocklist,
      ["upload.provider"]: uploadProvider,
      ["upload.filesystem.upload_path"]: uploadFilesystemUploadPath,
      ["upload.filesystem.upload_uri"]: uploadFilesystemUploadUri,
      ["upload.s3.url"]: uploadS3Url,
      ["upload.s3.public_url"]: uploadS3PublicUrl,
      ["upload.s3.aws_access_key_id"]: uploadS3AwsAccessKeyId,
      ["upload.s3.aws_default_region"]: uploadS3AwsDefaultRegion,
      ["upload.s3.bucket"]: uploadS3Bucket,
      ["upload.s3.bucket_domain"]: uploadS3BucketDomain,
      ["upload.s3.bucket_path"]: uploadS3BucketPath,
      ["upload.s3.bucket_type"]: uploadS3BucketType,
      ["upload.s3.expiry"]: uploadS3Expiry,
      smtp: toWire(smtp, "SMTPSettings"),
      messengers,
      ["bounce.enabled"]: bounceEnabled,
      ["bounce.webhooks_enabled"]: bounceWebhooksEnabled,
      ["bounce.count"]: bounceCount,
      ["bounce.action"]: bounceAction,
      ["bounce.ses_enabled"]: bounceSesEnabled,
      ["bounce.azure.enabled"]: bounceAzureEnabled,
      ["bounce.azure.shared_secret"]: bounceAzureSharedSecret,
      ["bounce.azure.shared_secret_header"]: bounceAzureSharedSecretHeader,
      ["bounce.sendgrid_enabled"]: bounceSendgridEnabled,
      ["bounce.sendgrid_key"]: bounceSendgridKey,
      ["bounce.forwardemail_enabled"]: bounceForwardemailEnabled,
      ["bounce.forwardemail_key"]: bounceForwardemailKey,
      ["bounce.postmark_enabled"]: bouncePostmarkEnabled,
      ["bounce.postmark_username"]: bouncePostmarkUsername,
      ["bounce.postmark_password"]: bouncePostmarkPassword,
      ["bounce.mailboxes"]: toWire(bounceMailboxes, "MailBoxBounces"),
      ["appearance.admin.custom_css"]: appearanceAdminCustomCss,
      ["appearance.admin.custom_js"]: appearanceAdminCustomJs,
      ["appearance.public.custom_css"]: appearancePublicCustomCss,
      ["appearance.public.custom_js"]: appearancePublicCustomJs,
    },
    config,
  });
  return _resp.data;
}

export type TestSmtpSettingsParams = SMTPTest;

/**
 * Tests SMTP settings using the supplied SMTP configuration values. Provide any settings to test in the request body; all listed fields are optional.
 *
 * test smtp settings
 *
 * @param uuid - Optional `string` value serialized in the `uuid` wire field.
 * @param enabled - Optional `boolean` value serialized in the `enabled` wire
 *   field.
 * @param host - Optional `string` value serialized in the `host` wire field.
 * @param helloHostname - Optional `string` value serialized in the
 *   `hello_hostname` wire field.
 * @param port - Optional `integer` value serialized in the `port` wire field.
 * @param authProtocol - Optional `string` value serialized in the
 *   `auth_protocol` wire field.
 * @param username - Optional `string` value serialized in the `username` wire
 *   field.
 * @param emailHeaders - Optional array value serialized in the `email_headers`
 *   wire field.
 * @param maxConns - Optional `integer` value serialized in the `max_conns` wire
 *   field.
 * @param maxMsgRetries - Optional `integer` value serialized in the
 *   `max_msg_retries` wire field.
 * @param idleTimeout - Optional `string` value serialized in the `idle_timeout`
 *   wire field.
 * @param waitTimeout - Optional `string` value serialized in the `wait_timeout`
 *   wire field.
 * @param tlsType - Optional `string` value serialized in the `tls_type` wire
 *   field.
 * @param tlsSkipVerify - Optional `boolean` value serialized in the
 *   `tls_skip_verify` wire field.
 * @param strEmailHeaders - Optional `string` value serialized in the
 *   `strEmailHeaders` wire field.
 * @param password - Optional `string` value serialized in the `password` wire
 *   field.
 * @param email - Optional `string` value serialized in the `email` wire field.
 */
export async function testSmtpSettings(
  config: ClientConfig,
  {
    uuid,
    enabled,
    host,
    helloHostname,
    port,
    authProtocol,
    username,
    emailHeaders,
    maxConns,
    maxMsgRetries,
    idleTimeout,
    waitTimeout,
    tlsType,
    tlsSkipVerify,
    strEmailHeaders,
    password,
    email,
  }: TestSmtpSettingsParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/settings/smtp/test`,
    operationId: "testSmtpSettings",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      uuid,
      enabled,
      host,
      hello_hostname: helloHostname,
      port,
      auth_protocol: authProtocol,
      username,
      email_headers: emailHeaders,
      max_conns: maxConns,
      max_msg_retries: maxMsgRetries,
      idle_timeout: idleTimeout,
      wait_timeout: waitTimeout,
      tls_type: tlsType,
      tls_skip_verify: tlsSkipVerify,
      strEmailHeaders,
      password,
      email,
    },
    config,
  });
  return _resp.data;
}

export class SettingsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns the settings stored in the database. Use this endpoint to retrieve the server's current configuration settings.
   *
   * returns settings from DB
   */
  get(requestOptions?: RequestOptions): ReturnType<typeof getSettings> {
    return getSettings(this._config, requestOptions);
  }
  /**
   * Updates settings stored in the database. Supply the settings fields you want to update; each listed field is optional.
   *
   * returns updated settings from the DB.
   */
  update(
    params: UpdateSettingsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateSettings> {
    return updateSettings(this._config, params, requestOptions);
  }
  /**
   * Tests SMTP settings using the supplied SMTP configuration values. Provide any settings to test in the request body; all listed fields are optional.
   *
   * test smtp settings
   */
  testSmtp(
    params: TestSmtpSettingsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof testSmtpSettings> {
    return testSmtpSettings(this._config, params, requestOptions);
  }
}
