// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

export * from "./subscribers/part1";
export * from "./subscribers/part2";
import type { ClientConfig, RequestOptions } from "../client";

import type {
  BlocklistSubscribersQueryParams,
  CreateSubscriberParams,
  DeleteSubscriberBouncesByIdParams,
  DeleteSubscriberByIdParams,
  DeleteSubscriberByListParams,
  DeleteSubscriberByQueryParams,
  ExportSubscriberDataByIdParams,
  GetSubscriberBouncesByIdParams,
  GetSubscriberByIdParams,
  GetSubscribersParams,
  ManageBlocklistBySubscriberListParams,
  ManageBlocklistSubscribersByIdParams,
  ManageSubscriberListByIdParams,
  ManageSubscriberListsParams,
  SubscriberSendOptinByIdParams,
  UpdateSubscriberByIdParams,
} from "./subscribers/part1";
import {
  blocklistSubscribersQuery,
  createSubscriber,
  deleteSubscriberBouncesById,
  deleteSubscriberById,
  deleteSubscriberByList,
  deleteSubscriberByQuery,
  deleteSubscriberByQueryText,
  exportSubscriberDataById,
  getSubscriberBouncesById,
  getSubscriberById,
  getSubscribers,
  manageBlocklistBySubscriberList,
  manageBlocklistSubscribersById,
  manageSubscriberListById,
  manageSubscriberLists,
  subscriberSendOptinById,
  updateSubscriberById,
} from "./subscribers/part1";
import type { ManageSubscriberListsByQueryParams } from "./subscribers/part2";
import {
  blocklistSubscribersQueryText,
  manageSubscriberListsByQuery,
  manageSubscriberListsByQueryText,
} from "./subscribers/part2";

export class SubscribersNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists subscribers, with options to filter and sort the results. Use `query` to filter with an SQL expression, `list_id` to filter by lists, and `order_by` and `order` to control sorting. Use `page` and `per_page` to paginate the results.
   *
   * returns all subscribers.
   */
  get(
    params: GetSubscribersParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getSubscribers> {
    return getSubscribers(this._config, params, requestOptions);
  }
  /**
   * Creates a subscriber from the supplied subscriber details. The request body may be omitted, and no fields are required by the schema; include values such as `email`, `name`, or `lists` to set subscriber data.
   *
   * handles creation of new subscriber
   */
  create(
    params: CreateSubscriberParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createSubscriber> {
    return createSubscriber(this._config, params, requestOptions);
  }
  /**
   * Deletes one or more subscribers identified by the `id` query parameter. Supply the subscriber ID or IDs as a string, with each ID identifying a subscriber to delete.
   *
   * handles subscribers deletion
   */
  deleteByList(
    params: DeleteSubscriberByListParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteSubscriberByList> {
    return deleteSubscriberByList(this._config, params, requestOptions);
  }
  /**
   * Retrieves a subscriber by its identifier. Use the `id` path parameter to select the subscriber whose details you want to view.
   *
   * handles the retrieval of a single subscriber by ID.
   */
  getById(
    params: GetSubscriberByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getSubscriberById> {
    return getSubscriberById(this._config, params, requestOptions);
  }
  /**
   * Replaces subscriber data for the subscriber identified by the path parameter. The request body may be omitted, and the schema does not require any fields; supply the subscriber properties you want included in the update.
   *
   * modify subscriber data
   */
  updateById(
    params: UpdateSubscriberByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateSubscriberById> {
    return updateSubscriberById(this._config, params, requestOptions);
  }
  /**
   * Deletes a subscriber identified by its path parameter. Use the subscriber's integer `id` to select the record to remove.
   *
   * handles subscriber deletion based on id
   */
  deleteById(
    params: DeleteSubscriberByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteSubscriberById> {
    return deleteSubscriberById(this._config, params, requestOptions);
  }
  /**
   * Manages subscriber membership across lists by adding, removing, or unsubscribing subscribers. Supply `action` and the subscriber or list selectors that define which records to modify; `action` must be `add`, `remove`, or `unsubscribe`.
   *
   * handles bulk addition or removal of subscribers
   */
  manageLists(
    params: ManageSubscriberListsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof manageSubscriberLists> {
    return manageSubscriberLists(this._config, params, requestOptions);
  }
  /**
   * Manages subscriber membership in a specified list by adding, removing, or unsubscribing subscribers. Use the `id` path parameter to select the list and provide the subscriber selectors and `action` in the request body.
   *
   * handles bulk addition or removal of subscribers for a specified list id
   */
  manageListById(
    params: ManageSubscriberListByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof manageSubscriberListById> {
    return manageSubscriberListById(this._config, params, requestOptions);
  }
  /**
   * Manages subscribers on the blocklist using subscriber selectors and list settings. Provide `action` to specify whether to add, remove, or unsubscribe the selected subscribers.
   *
   * handles blocklisting of subscriber list
   */
  manageBlocklistByList(
    params: ManageBlocklistBySubscriberListParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof manageBlocklistBySubscriberList> {
    return manageBlocklistBySubscriberList(this._config, params, requestOptions);
  }
  /**
   * Manages the blocklist for the subscriber identified by the path parameter. Use the `id` path parameter to select the subscriber and provide the action and any additional selectors in the request body.
   *
   * handles the blocklisting of one or more subscribers.
   */
  manageBlocklistById(
    params: ManageBlocklistSubscribersByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof manageBlocklistSubscribersById> {
    return manageBlocklistSubscribersById(this._config, params, requestOptions);
  }
  /**
   * Retrieves a subscriber's profile and related activity data for export. Supply the subscriber's numeric `id` to retrieve profile details, subscriptions, campaign views, and link clicks.
   *
   * retrieves a subscriber's profile
   */
  exportDataById(
    params: ExportSubscriberDataByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof exportSubscriberDataById> {
    return exportSubscriberDataById(this._config, params, requestOptions);
  }
  /**
   * Retrieves bounce records associated with a specific subscriber. Supply the subscriber's numeric `id` to look up the records for that subscriber.
   *
   * retrieves a subscriber's bounce records
   */
  getBouncesById(
    params: GetSubscriberBouncesByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getSubscriberBouncesById> {
    return getSubscriberBouncesById(this._config, params, requestOptions);
  }
  /**
   * Deletes the bounce records associated with a specific subscriber. Supply the subscriber's numeric `id` to identify whose bounce records to delete.
   *
   * deletes a subscriber's bounce records
   */
  deleteBouncesById(
    params: DeleteSubscriberBouncesByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteSubscriberBouncesById> {
    return deleteSubscriberBouncesById(this._config, params, requestOptions);
  }
  /**
   * Sends an opt-in confirmation email to a subscriber. Supply the subscriber's numeric `id` to identify the recipient of the confirmation email.
   *
   * sends an optin confirmation e-mail to a subscriber.
   */
  sendOptinById(
    params: SubscriberSendOptinByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof subscriberSendOptinById> {
    return subscriberSendOptinById(this._config, params, requestOptions);
  }
  /**
   * Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
   *
   * bulk deletes based on an arbitrary SQL expression.
   */
  deleteByQuery(
    params: DeleteSubscriberByQueryParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteSubscriberByQuery> {
    return deleteSubscriberByQuery(this._config, params, requestOptions);
  }
  /**
   * Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
   *
   * bulk deletes based on an arbitrary SQL expression.
   */
  deleteByQueryText(
    body: string,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteSubscriberByQueryText> {
    return deleteSubscriberByQueryText(this._config, body, requestOptions);
  }
  /**
   * Adds or removes subscribers from the blocklist based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
   *
   * bulk blocklists subscribers based on an arbitrary SQL expression.
   */
  blocklistQuery(
    params: BlocklistSubscribersQueryParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof blocklistSubscribersQuery> {
    return blocklistSubscribersQuery(this._config, params, requestOptions);
  }
  /**
   * Adds or removes subscribers from the blocklist based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
   *
   * bulk blocklists subscribers based on an arbitrary SQL expression.
   */
  blocklistQueryText(
    body: string,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof blocklistSubscribersQueryText> {
    return blocklistSubscribersQueryText(this._config, body, requestOptions);
  }
  /**
   * Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status` filters.
   *
   * bulk adds/removes/unsubscribes subscribers from one or more lists based on an arbitrary SQL expression.
   */
  manageListsByQuery(
    params: ManageSubscriberListsByQueryParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof manageSubscriberListsByQuery> {
    return manageSubscriberListsByQuery(this._config, params, requestOptions);
  }
  /**
   * Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status` filters.
   *
   * bulk adds/removes/unsubscribes subscribers from one or more lists based on an arbitrary SQL expression.
   */
  manageListsByQueryText(
    body: string,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof manageSubscriberListsByQueryText> {
    return manageSubscriberListsByQueryText(this._config, body, requestOptions);
  }
}
