// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { NewTemplate, Template, UpdateTemplate } from "../types/templates";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest } from "../client";

export interface GetTemplatesParams {
  noBody: boolean;
}

/**
 * Lists templates. Set `no_body` to control whether template bodies are included in the response.
 *
 * handles retrieval of templates
 *
 * @param noBody - boolean flag for response with/without body
 */
export async function getTemplates(
  config: ClientConfig,
  { noBody }: GetTemplatesParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Template[];
}> {
  const _resp = await sdkRequest<{
    data?: Template[];
  }>({
    method: "GET",
    path: `/templates`,
    operationId: "getTemplates",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      no_body: queryValue(noBody, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type CreateTemplateParams = NewTemplate;

/**
 * Creates a new template. Supply `name`, `type`, and `body`; choose `type` from `campaign`, `campaign_visual`, or `tx`, and include `subject` or `body_source` when relevant to that template type.
 *
 * handles template creation
 *
 * @param name - Name of the template
 * @param type_ - Type of the template
 * @param body - HTML body of the template
 * @param subject - Subject line for the template (only for tx)
 * @param bodySource - JSON source for the email-builder template (only for
 *   campaign_visual)
 */
export async function createTemplate(
  config: ClientConfig,
  { name, type: type_, body, subject, bodySource }: CreateTemplateParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Template;
}> {
  const _resp = await sdkRequest<{
    data?: Template;
  }>({
    method: "POST",
    path: `/templates`,
    operationId: "createTemplate",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      ["type"]: type_,
      body,
      subject,
      body_source: bodySource,
    },
    config,
  });
  return _resp.data;
}

export interface GetTemplateByIdParams {
  id: number;
  noBody?: boolean;
}

/**
 * Retrieves a template by its identifier. Use the `no_body` query parameter to request a response with or without the template body.
 *
 * handles retrieval of templates
 *
 * @param id - The id value of the template you want to get.
 * @param noBody - boolean flag for response with/without body
 */
export async function getTemplateById(
  config: ClientConfig,
  { id, noBody }: GetTemplateByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Template;
}> {
  const _resp = await sdkRequest<{
    data?: Template;
  }>({
    method: "GET",
    path: `/templates/${encodePathSegment(id)}`,
    operationId: "getTemplateById",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      no_body: queryValue(noBody, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UpdateTemplateByIdParams = UpdateTemplate & {
  id: number;
};

/**
 * Replaces a template's configuration. Supply the template properties you want to set, and use `type` to choose campaign, visual campaign, or transactional template behavior.
 *
 * handles template modification
 *
 * @param id - The id value of the template you want to update.
 * @param name - Name of the template
 * @param type_ - Type of the template
 * @param subject - Subject line for the template (only for tx)
 * @param bodySource - JSON source for the email-builder template (only for
 *   campaign_visual)
 * @param body - HTML body of the template
 */
export async function updateTemplateById(
  config: ClientConfig,
  { id, name, type: type_, subject, bodySource, body }: UpdateTemplateByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Template;
}> {
  const _resp = await sdkRequest<{
    data?: Template;
  }>({
    method: "PUT",
    path: `/templates/${encodePathSegment(id)}`,
    operationId: "updateTemplateById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      ["type"]: type_,
      subject,
      body_source: bodySource,
      body,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteTemplateByIdParams {
  id: number;
}

/**
 * Deletes a template by its identifier. Use this operation when you no longer need the template; the response indicates whether the deletion succeeded.
 *
 * handles deletion of templates
 *
 * @param id - The id value of the template you want to delete.
 */
export async function deleteTemplateById(
  config: ClientConfig,
  { id }: DeleteTemplateByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/templates/${encodePathSegment(id)}`,
    operationId: "deleteTemplateById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface PreviewTemplateParams {
  templateType?: string;
  body?: string;
}

/**
 * Generates an HTML preview from the supplied template parameters. Provide `template_type` to identify the template type and `body` to supply the template content.
 *
 * get the HTML preview of a template.
 *
 * @param templateType - type of template
 * @param body - template body
 */
export async function previewTemplate(
  config: ClientConfig,
  { templateType, body }: PreviewTemplateParams = {},
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "POST",
    path: `/templates/preview`,
    operationId: "previewTemplate",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      template_type: templateType,
      body,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

export interface PreviewTemplateByIdParams {
  id: number;
  templateType?: string;
  body?: string;
}

/**
 * Renders an HTML preview for a template identified by its integer ID. Supply `template_type` and `body` as form-encoded preview parameters.
 *
 * renders the HTML preview of a template.
 *
 * @param id - The id value of the template you want to get.
 * @param templateType - type of template
 * @param body - template body
 */
export async function previewTemplateById(
  config: ClientConfig,
  { id, templateType, body }: PreviewTemplateByIdParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/templates/${encodePathSegment(id)}/preview`,
    operationId: "previewTemplateById",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      template_type: templateType,
      body,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

export interface SetDefaultTemplateByIdParams {
  id: number;
}

/**
 * Sets the specified template as the default template. Use the template's integer identifier to select which template to make the default.
 *
 * handles template modification.
 *
 * @param id - The id value of the template you want to set to the default
 *   template.
 */
export async function setDefaultTemplateById(
  config: ClientConfig,
  { id }: SetDefaultTemplateByIdParams,
  requestOptions?: RequestOptions,
): Promise<Template> {
  const _resp = await sdkRequest<Template>({
    method: "PUT",
    path: `/templates/${encodePathSegment(id)}/default`,
    operationId: "setDefaultTemplateById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "Template") as Template;
}

export class TemplatesNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists templates. Set `no_body` to control whether template bodies are included in the response.
   *
   * handles retrieval of templates
   */
  get(
    params: GetTemplatesParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getTemplates> {
    return getTemplates(this._config, params, requestOptions);
  }
  /**
   * Creates a new template. Supply `name`, `type`, and `body`; choose `type` from `campaign`, `campaign_visual`, or `tx`, and include `subject` or `body_source` when relevant to that template type.
   *
   * handles template creation
   */
  create(
    params: CreateTemplateParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createTemplate> {
    return createTemplate(this._config, params, requestOptions);
  }
  /**
   * Retrieves a template by its identifier. Use the `no_body` query parameter to request a response with or without the template body.
   *
   * handles retrieval of templates
   */
  getById(
    params: GetTemplateByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getTemplateById> {
    return getTemplateById(this._config, params, requestOptions);
  }
  /**
   * Replaces a template's configuration. Supply the template properties you want to set, and use `type` to choose campaign, visual campaign, or transactional template behavior.
   *
   * handles template modification
   */
  updateById(
    params: UpdateTemplateByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateTemplateById> {
    return updateTemplateById(this._config, params, requestOptions);
  }
  /**
   * Deletes a template by its identifier. Use this operation when you no longer need the template; the response indicates whether the deletion succeeded.
   *
   * handles deletion of templates
   */
  deleteById(
    params: DeleteTemplateByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteTemplateById> {
    return deleteTemplateById(this._config, params, requestOptions);
  }
  /**
   * Generates an HTML preview from the supplied template parameters. Provide `template_type` to identify the template type and `body` to supply the template content.
   *
   * get the HTML preview of a template.
   */
  preview(
    params: PreviewTemplateParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof previewTemplate> {
    return previewTemplate(this._config, params, requestOptions);
  }
  /**
   * Renders an HTML preview for a template identified by its integer ID. Supply `template_type` and `body` as form-encoded preview parameters.
   *
   * renders the HTML preview of a template.
   */
  previewById(
    params: PreviewTemplateByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof previewTemplateById> {
    return previewTemplateById(this._config, params, requestOptions);
  }
  /**
   * Sets the specified template as the default template. Use the template's integer identifier to select which template to make the default.
   *
   * handles template modification.
   */
  setDefaultById(
    params: SetDefaultTemplateByIdParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof setDefaultTemplateById> {
    return setDefaultTemplateById(this._config, params, requestOptions);
  }
}
