// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { TransactionalMessage } from "../types/transactional";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export type TransactWithSubscriberParams = TransactionalMessage;

/**
 * Sends a transactional message to a subscriber. Use `subscriber_email` or `subscriber_id` to identify the recipient, and provide message content or a `template_id` as needed.
 *
 * send message to a subscriber
 *
 * @param subscriberEmail - Optional `string` value serialized in the
 *   `subscriber_email` wire field.
 * @param subscriberId - Optional `integer` value serialized in the
 *   `subscriber_id` wire field.
 * @param templateId - Optional `integer` value serialized in the `template_id`
 *   wire field.
 * @param fromEmail - Optional `string` value serialized in the `from_email` wire
 *   field.
 * @param data - Optional object value serialized in the `data` wire field.
 * @param headers - Optional array value serialized in the `headers` wire field.
 * @param messenger - Optional `string` value serialized in the `messenger` wire
 *   field.
 * @param contentType - Optional `string` value serialized in the `content_type`
 *   wire field.
 */
export async function transactWithSubscriber(
  config: ClientConfig,
  {
    subscriberEmail,
    subscriberId,
    templateId,
    fromEmail,
    data,
    headers,
    messenger,
    contentType,
  }: TransactWithSubscriberParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/tx`,
    operationId: "transactWithSubscriber",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      subscriber_email: subscriberEmail,
      subscriber_id: subscriberId,
      template_id: templateId,
      from_email: fromEmail,
      data,
      headers,
      messenger,
      content_type: contentType,
    },
    config,
  });
  return _resp.data;
}

export class TransactionalNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Sends a transactional message to a subscriber. Use `subscriber_email` or `subscriber_id` to identify the recipient, and provide message content or a `template_id` as needed.
   *
   * send message to a subscriber
   */
  transactWithSubscriber(
    params: TransactWithSubscriberParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof transactWithSubscriber> {
    return transactWithSubscriber(this._config, params, requestOptions);
  }
}
