// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  Campaign,
  CampaignAnalyticsCount,
  CampaignContentRequest,
  CampaignRequest,
  CampaignStats,
  CampaignUpdate,
} from "../../types/campaigns";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, queryValue, sdkRequest } from "../../client";
import { validateDate } from "../../validation";

export interface GetCampaignsParams {
  status?: ("scheduled" | "running" | "paused" | "cancelled" | (string & {}))[];
  noBody?: boolean;
  page?: number;
  perPage?: number | "all" | (string & {});
  tags?: string[];
  order?: "ASC" | "DESC" | (string & {});
  orderBy?: "name" | "status" | "created_at" | "updated_at" | (string & {});
  query?: string;
}

/**
 * Lists campaigns, with optional filters for status and tags and optional sorting controls. Use `query` to apply custom SQL criteria, or use `page` and `per_page` to paginate the results. Set `no_body` to true to request a response without body content.
 *
 * handles retrieval of campaigns
 *
 * @param status - Filter campaigns by status. Multiple status values can be
 *   specified by repeating the parameter
 * @param noBody - When set to true, returns response without body content
 * @param page - Page number for paginated results.
 * @param perPage - Number of items per page. Use an integer for specific page
 *   size or 'all' to retrieve all results
 * @param tags - Filter campaigns by tags. Multiple tags can be specified by
 *   repeating the parameter
 * @param order - Determines the sort order of results. ASC for ascending, DESC
 *   for descending order
 * @param orderBy - Specifies the field by which to sort the campaigns. Available
 *   options are 'name', 'status', 'created_at', and 'updated_at'
 * @param query - SQL query expression to filter campaigns by custom criteria
 */
export async function getCampaigns(
  config: ClientConfig,
  { status, noBody, page, perPage, tags, order, orderBy, query }: GetCampaignsParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: {
    results?: Campaign[];
    query?: string;
    total?: number;
    perPage?: number;
    page?: number;
  };
}> {
  const _resp = await sdkRequest<{
    data?: {
      results?: Campaign[];
      query?: string;
      total?: number;
      perPage?: number;
      page?: number;
    };
  }>({
    method: "GET",
    path: `/campaigns`,
    operationId: "getCampaigns",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      status: queryValue(status, "form", true),
      no_body: queryValue(noBody, "form", true),
      page: queryValue(page, "form", true),
      per_page: queryValue(perPage, "form", true),
      tags: queryValue(tags, "form", true),
      order: queryValue(order, "form", true),
      order_by: queryValue(orderBy, "form", true),
      query: queryValue(query, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type CreateCampaignParams = CampaignRequest;

/**
 * Creates a campaign from the campaign details supplied in the request body. Provide fields such as `name`, `subject`, and `lists` to define the campaign; all body fields are optional in the schema. A successful response contains the new campaign object.
 *
 * handles campaign creation
 *
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param subject - Optional `string` value serialized in the `subject` wire
 *   field.
 * @param lists - Optional array value serialized in the `lists` wire field.
 * @param fromEmail - Optional `string` value serialized in the `from_email` wire
 *   field.
 * @param contentType - Optional `string` value serialized in the `content_type`
 *   wire field.
 * @param messenger - Optional `string` value serialized in the `messenger` wire
 *   field.
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param sendLater - Optional `boolean` value serialized in the `send_later`
 *   wire field.
 * @param sendAt - Optional object value serialized in the `send_at` wire field.
 */
export async function createCampaign(
  config: ClientConfig,
  {
    name,
    subject,
    lists,
    fromEmail,
    contentType,
    messenger,
    type: type_,
    tags,
    sendLater,
    sendAt,
  }: CreateCampaignParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: CampaignUpdate;
}> {
  const _resp = await sdkRequest<{
    data?: CampaignUpdate;
  }>({
    method: "POST",
    path: `/campaigns`,
    operationId: "createCampaign",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      subject,
      lists,
      from_email: fromEmail,
      content_type: contentType,
      messenger,
      ["type"]: type_,
      tags,
      send_later: sendLater,
      send_at: sendAt,
    },
    config,
  });
  return _resp.data;
}

export interface GetCampaignByIdParams {
  id: number;
  noBody?: boolean;
}

/**
 * Retrieves a campaign by its identifier. Use `id` to select the campaign, and set `no_body` to true if you want the response without body content.
 *
 * handles retrieval of campaigns.
 *
 * @param id - The id value of the campaign you want to get.
 * @param noBody - boolean flag for response with/without body
 */
export async function getCampaignById(
  config: ClientConfig,
  { id, noBody }: GetCampaignByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Campaign;
}> {
  const _resp = await sdkRequest<{
    data?: Campaign;
  }>({
    method: "GET",
    path: `/campaigns/${encodePathSegment(id)}`,
    operationId: "getCampaignById",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      no_body: queryValue(noBody, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UpdateCampaignByIdParams = CampaignRequest & {
  id: number;
};

/**
 * Replaces campaign details for the campaign identified by `id`. Supply the campaign fields you want to set, such as `name`, `subject`, or `lists`; the schema does not require any particular body fields. A successful response contains the updated campaign object.
 *
 * handle updation of campaign
 *
 * @param id - the id value of campaign you want to update
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param subject - Optional `string` value serialized in the `subject` wire
 *   field.
 * @param lists - Optional array value serialized in the `lists` wire field.
 * @param fromEmail - Optional `string` value serialized in the `from_email` wire
 *   field.
 * @param contentType - Optional `string` value serialized in the `content_type`
 *   wire field.
 * @param messenger - Optional `string` value serialized in the `messenger` wire
 *   field.
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param sendLater - Optional `boolean` value serialized in the `send_later`
 *   wire field.
 * @param sendAt - Optional object value serialized in the `send_at` wire field.
 */
export async function updateCampaignById(
  config: ClientConfig,
  {
    id,
    name,
    subject,
    lists,
    fromEmail,
    contentType,
    messenger,
    type: type_,
    tags,
    sendLater,
    sendAt,
  }: UpdateCampaignByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: CampaignUpdate;
}> {
  const _resp = await sdkRequest<{
    data?: CampaignUpdate;
  }>({
    method: "PUT",
    path: `/campaigns/${encodePathSegment(id)}`,
    operationId: "updateCampaignById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      subject,
      lists,
      from_email: fromEmail,
      content_type: contentType,
      messenger,
      ["type"]: type_,
      tags,
      send_later: sendLater,
      send_at: sendAt,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteCampaignByIdParams {
  id: number;
}

/**
 * Deletes the campaign identified by `id`. Use the campaign's integer identifier to select the campaign to remove. The response contains a boolean result.
 *
 * deletes specified campaign
 *
 * @param id - The id value of the campaign you want to get.
 */
export async function deleteCampaignById(
  config: ClientConfig,
  { id }: DeleteCampaignByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/campaigns/${encodePathSegment(id)}`,
    operationId: "deleteCampaignById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface GetRunningCampaignStatsParams {
  campaignId: number;
}

/**
 * Lists statistics for the campaign identified by `campaign_id`. Supply the campaign ID as a number to retrieve its running campaign statistics. The response contains statistics for the requested campaign.
 *
 * returns stats of a given set of campaign IDs.
 *
 * @param campaignId - Campaign IDs to get stats for.
 */
export async function getRunningCampaignStats(
  config: ClientConfig,
  { campaignId }: GetRunningCampaignStatsParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: CampaignStats[];
}> {
  const _resp = await sdkRequest<{
    data?: CampaignStats[];
  }>({
    method: "GET",
    path: `/campaigns/running/stats`,
    operationId: "getRunningCampaignStats",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      campaign_id: queryValue(campaignId, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetCampaignAnalyticsParams {
  type: "links" | "views" | "clicks" | "bounces" | (string & {});
  from: Date;
  to: string;
  id: string;
}

/**
 * Retrieves campaign analytics for the requested statistic type and date range. Use `type` to select links, views, clicks, or bounces, and provide `from`, `to`, and `id` to scope the results. The response contains counts over time for the specified campaign ID or IDs.
 *
 * retrieves view counts for a campaign.
 *
 * @param type_ - type of stats, either links, view, click or bounce
 * @param from - start value of date range
 * @param to - end value of date range
 * @param id - campaign id/s to retrive view counts
 */
export async function getCampaignAnalytics(
  config: ClientConfig,
  { type: type_, from, to, id }: GetCampaignAnalyticsParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: CampaignAnalyticsCount[];
}> {
  validateDate("from", from);

  const _resp = await sdkRequest<{
    data?: CampaignAnalyticsCount[];
  }>({
    method: "GET",
    path: `/campaigns/analytics/${encodePathSegment(type_)}`,
    operationId: "getCampaignAnalytics",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      from: queryValue(from, "form", true, "date"),
      to: queryValue(to, "form", true),
      id: queryValue(id, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface PreviewCampaignByIdParams {
  id: number;
}

/**
 * Retrieves the rendered HTML preview of a campaign's body. Supply the campaign's integer `id` to select the campaign whose preview you want to view.
 *
 * renders the HTML preview of a campaign body
 *
 * @param id - The id value of the campaign you want to get the preview of
 */
export async function previewCampaignById(
  config: ClientConfig,
  { id }: PreviewCampaignByIdParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/campaigns/${encodePathSegment(id)}/preview`,
    operationId: "previewCampaignById",
    responseDecoder: "text",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface UpdatePreviewCampaignByIdParams {
  id: number;
  templateId?: number;
  contentType?: string;
  body?: string;
}

/**
 * Renders an HTML preview of a campaign using the supplied template and content fields. Use `id` to identify the campaign and provide the preview inputs as form-encoded fields. The request body fields are optional in the schema.
 *
 * renders the HTML preview of a campaign body
 *
 * @param id - The id value of the campaign you want to get the preview of
 * @param templateId - template id
 * @param contentType - content type
 * @param body - template body
 */
export async function updatePreviewCampaignById(
  config: ClientConfig,
  { id, templateId, contentType, body }: UpdatePreviewCampaignByIdParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "POST",
    path: `/campaigns/${encodePathSegment(id)}/preview`,
    operationId: "updatePreviewCampaignById",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      template_id: templateId,
      content_type: contentType,
      body,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

export interface PreviewCampaignTextByIdParams {
  id: number;
  templateId?: number;
  contentType?: string;
  body?: string;
}

/**
 * Renders a text preview of a campaign using the supplied template and content fields. Use `id` to identify the campaign and provide the preview inputs as form-encoded fields. The request body fields are optional in the schema.
 *
 * renders the HTML preview of a campaign body
 *
 * @param id - The id value of the campaign you want to get the preview of
 * @param templateId - template id
 * @param contentType - content type
 * @param body - campaign body
 */
export async function previewCampaignTextById(
  config: ClientConfig,
  { id, templateId, contentType, body }: PreviewCampaignTextByIdParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "POST",
    path: `/campaigns/${encodePathSegment(id)}/text`,
    operationId: "previewCampaignTextById",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      template_id: templateId,
      content_type: contentType,
      body,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

export interface UpdateCampaignStatusByIdParams {
  id: number;
  status?: "scheduled" | "running" | "paused" | "cancelled" | (string & {});
}

/**
 * Replaces the status of a campaign. Set `status` to `scheduled`, `running`, `paused`, or `cancelled` when you want to change the campaign's state.
 *
 * handles campaign status modification
 *
 * @param id - The id value of the campaign you want to get the preview of
 */
export async function updateCampaignStatusById(
  config: ClientConfig,
  { id, status }: UpdateCampaignStatusByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Campaign;
}> {
  const _resp = await sdkRequest<{
    data?: Campaign;
  }>({
    method: "PUT",
    path: `/campaigns/${encodePathSegment(id)}/status`,
    operationId: "updateCampaignStatusById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      status,
    },
    config,
  });
  return _resp.data;
}

export interface UpdateCampaignArchiveByIdParams {
  id: number;
  archive?: boolean;
  archiveTemplateId?: number;
  archiveMeta?: { [key: string]: unknown };
}

/**
 * Replaces the archive settings for a campaign. Use `archive` to set the archive state and `archive_template_id` or `archive_meta` to provide related archive configuration.
 *
 * handles campaign status modification
 *
 * @param id - The id value of the campaign you want to get the preview of
 */
export async function updateCampaignArchiveById(
  config: ClientConfig,
  { id, archive, archiveTemplateId, archiveMeta }: UpdateCampaignArchiveByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/campaigns/${encodePathSegment(id)}/archive`,
    operationId: "updateCampaignArchiveById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      archive,
      archive_template_id: archiveTemplateId,
      archive_meta: archiveMeta,
    },
    config,
  });
  return _resp.data;
}

export type CreateCampaignContentByIdParams = CampaignContentRequest & {
  id: number;
};

/**
 * Submits updated content for a campaign and converts it to the campaign's content format. Use the campaign identifier in the path and provide any campaign content fields you want to submit.
 *
 * handles campaign content (body) format conversions.
 *
 * @param id - ID of campaign that you choose to create content
 * @param id_2 - Optional `integer` value serialized in the `id` wire field.
 * @param createdAt - Optional `string` value serialized in the `created_at` wire
 *   field.
 * @param updatedAt - Optional `string` value serialized in the `updated_at` wire
 *   field.
 * @param campaignId - Optional `integer` value serialized in the `CampaignID`
 *   wire field.
 * @param views - Optional `integer` value serialized in the `views` wire field.
 * @param clicks - Optional `integer` value serialized in the `clicks` wire
 *   field.
 * @param lists - Optional array value serialized in the `lists` wire field.
 * @param startedAt - Optional `string` value serialized in the `started_at` wire
 *   field.
 * @param toSend - Optional `integer` value serialized in the `to_send` wire
 *   field.
 * @param sent - Optional `integer` value serialized in the `sent` wire field.
 * @param uuid - Optional `string` value serialized in the `uuid` wire field.
 * @param type_ - Optional enumerated value serialized in the `type` wire field.
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param subject - Optional `string` value serialized in the `subject` wire
 *   field.
 * @param fromEmail - Optional `string` value serialized in the `from_email` wire
 *   field.
 * @param body - Optional `string` value serialized in the `body` wire field.
 * @param sendAt - Optional `string` value serialized in the `send_at` wire
 *   field.
 * @param status - Optional `string` value serialized in the `status` wire field.
 * @param contentType - Optional enumerated value serialized in the
 *   `content_type` wire field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param templateId - Optional `integer` value serialized in the `template_id`
 *   wire field.
 * @param messenger - Optional `string` value serialized in the `messenger` wire
 *   field.
 * @param from - Optional `string` value serialized in the `from` wire field.
 * @param to - Optional `string` value serialized in the `to` wire field.
 */
export async function createCampaignContentById(
  config: ClientConfig,
  {
    id,
    id: id_2,
    createdAt,
    updatedAt,
    campaignId,
    views,
    clicks,
    lists,
    startedAt,
    toSend,
    sent,
    uuid,
    type: type_,
    name,
    subject,
    fromEmail,
    body,
    sendAt,
    status,
    contentType,
    tags,
    templateId,
    messenger,
    from,
    to,
  }: CreateCampaignContentByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: string;
}> {
  const _resp = await sdkRequest<{
    data?: string;
  }>({
    method: "POST",
    path: `/campaigns/${encodePathSegment(id)}/content`,
    operationId: "createCampaignContentById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      id: id_2,
      created_at: createdAt,
      updated_at: updatedAt,
      CampaignID: campaignId,
      views,
      clicks,
      lists,
      started_at: startedAt,
      to_send: toSend,
      sent,
      uuid,
      ["type"]: type_,
      name,
      subject,
      from_email: fromEmail,
      body,
      send_at: sendAt,
      status,
      content_type: contentType,
      tags,
      template_id: templateId,
      messenger,
      from,
      to,
    },
    config,
  });
  return _resp.data;
}

export type TestCampaignByIdParams = CampaignRequest & {
  id: number;
};

/**
 * Submits a test campaign message to selected subscribers. Provide the campaign identifier and a request body with the test message configuration; the body can use JSON or form-encoded data.
 *
 * handles sending of campaign message to arbitrary subscribers for testing
 *
 * @param id - ID of campaign that you want to test
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param subject - Optional `string` value serialized in the `subject` wire
 *   field.
 * @param lists - Optional array value serialized in the `lists` wire field.
 * @param fromEmail - Optional `string` value serialized in the `from_email` wire
 *   field.
 * @param contentType - Optional `string` value serialized in the `content_type`
 *   wire field.
 * @param messenger - Optional `string` value serialized in the `messenger` wire
 *   field.
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param sendLater - Optional `boolean` value serialized in the `send_later`
 *   wire field.
 * @param sendAt - Optional object value serialized in the `send_at` wire field.
 */
export async function testCampaignById(
  config: ClientConfig,
  {
    id,
    name,
    subject,
    lists,
    fromEmail,
    contentType,
    messenger,
    type: type_,
    tags,
    sendLater,
    sendAt,
  }: TestCampaignByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/campaigns/${encodePathSegment(id)}/test`,
    operationId: "testCampaignById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      subject,
      lists,
      from_email: fromEmail,
      content_type: contentType,
      messenger,
      ["type"]: type_,
      tags,
      send_later: sendLater,
      send_at: sendAt,
    },
    config,
  });
  return _resp.data;
}
