// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, sdkRequest } from "../../client";

export interface TestCampaignByIdFormParams {
  id: number;
  templateId?: number;
}

/**
 * Submits a test campaign message to selected subscribers. Provide the campaign identifier and a request body with the test message configuration; the body can use JSON or form-encoded data.
 *
 * handles sending of campaign message to arbitrary subscribers for testing
 *
 * @param id - ID of campaign that you want to test
 * @param templateId - template id
 */
export async function testCampaignByIdForm(
  config: ClientConfig,
  { id, templateId }: TestCampaignByIdFormParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/campaigns/${encodePathSegment(id)}/test`,
    operationId: "testCampaignByIdForm",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      template_id: templateId,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}
