// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `Campaign` API schema.
 */
export interface Campaign {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `updated_at` wire field.
   */
  updatedAt?: string;
  /**
   * Optional `integer` value serialized in the `CampaignID` wire field.
   */
  campaignId?: number;
  /**
   * Optional `integer` value serialized in the `views` wire field.
   */
  views?: number;
  /**
   * Optional `integer` value serialized in the `clicks` wire field.
   */
  clicks?: number;
  /**
   * Optional array value serialized in the `lists` wire field.
   */
  lists?: {
    /**
     * Optional `integer` value serialized in the `id` wire field.
     */
    id?: number;
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    name?: string;
  }[];
  /**
   * Optional `string` value serialized in the `started_at` wire field.
   */
  startedAt?: string;
  /**
   * Optional `integer` value serialized in the `to_send` wire field.
   */
  toSend?: number;
  /**
   * Optional `integer` value serialized in the `sent` wire field.
   */
  sent?: number;
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional enumerated value serialized in the `type` wire field.
   */
  type?: "regular" | "optin" | (string & {});
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `subject` wire field.
   */
  subject?: string;
  /**
   * Optional `string` value serialized in the `from_email` wire field.
   */
  fromEmail?: string;
  /**
   * Optional `string` value serialized in the `body` wire field.
   */
  body?: string;
  /**
   * Optional `string` value serialized in the `send_at` wire field.
   */
  sendAt?: string;
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional enumerated value serialized in the `content_type` wire field.
   */
  contentType?: "richtext" | "html" | "markdown" | "plain" | (string & {});
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: string[];
  /**
   * Optional `integer` value serialized in the `template_id` wire field.
   */
  templateId?: number;
  /**
   * Optional `string` value serialized in the `messenger` wire field.
   */
  messenger?: string;
}

/**
 * Typed representation of the `CampaignAnalyticsCount` API schema.
 */
export interface CampaignAnalyticsCount {
  /**
   * Optional `integer` value serialized in the `campaign_id` wire field.
   */
  campaignId?: number;
  /**
   * Optional `integer` value serialized in the `count` wire field.
   */
  count?: number;
  /**
   * Optional `date-time`-formatted value serialized in the `timestamp` wire field.
   */
  timestamp?: string;
}

/**
 * Typed representation of the `CampaignContentRequest` API schema.
 */
export interface CampaignContentRequest {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `updated_at` wire field.
   */
  updatedAt?: string;
  /**
   * Optional `integer` value serialized in the `CampaignID` wire field.
   */
  campaignId?: number;
  /**
   * Optional `integer` value serialized in the `views` wire field.
   */
  views?: number;
  /**
   * Optional `integer` value serialized in the `clicks` wire field.
   */
  clicks?: number;
  /**
   * Optional array value serialized in the `lists` wire field.
   */
  lists?: {
    /**
     * Optional `integer` value serialized in the `id` wire field.
     */
    id?: number;
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    name?: string;
  }[];
  /**
   * Optional `string` value serialized in the `started_at` wire field.
   */
  startedAt?: string;
  /**
   * Optional `integer` value serialized in the `to_send` wire field.
   */
  toSend?: number;
  /**
   * Optional `integer` value serialized in the `sent` wire field.
   */
  sent?: number;
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional enumerated value serialized in the `type` wire field.
   */
  type?: "regular" | "optin" | (string & {});
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `subject` wire field.
   */
  subject?: string;
  /**
   * Optional `string` value serialized in the `from_email` wire field.
   */
  fromEmail?: string;
  /**
   * Optional `string` value serialized in the `body` wire field.
   */
  body?: string;
  /**
   * Optional `string` value serialized in the `send_at` wire field.
   */
  sendAt?: string;
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional enumerated value serialized in the `content_type` wire field.
   */
  contentType?: "richtext" | "html" | "markdown" | "plain" | (string & {});
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: string[];
  /**
   * Optional `integer` value serialized in the `template_id` wire field.
   */
  templateId?: number;
  /**
   * Optional `string` value serialized in the `messenger` wire field.
   */
  messenger?: string;
  /**
   * Optional `string` value serialized in the `from` wire field.
   */
  from?: string;
  /**
   * Optional `string` value serialized in the `to` wire field.
   */
  to?: string;
}

/**
 * Typed representation of the `CampaignRequest` API schema.
 */
export interface CampaignRequest {
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `subject` wire field.
   */
  subject?: string;
  /**
   * Optional array value serialized in the `lists` wire field.
   */
  lists?: number[];
  /**
   * Optional `string` value serialized in the `from_email` wire field.
   */
  fromEmail?: string;
  /**
   * Optional `string` value serialized in the `content_type` wire field.
   */
  contentType?: string;
  /**
   * Optional `string` value serialized in the `messenger` wire field.
   */
  messenger?: string;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: string[];
  /**
   * Optional `boolean` value serialized in the `send_later` wire field.
   */
  sendLater?: boolean;
  /**
   * Optional object value serialized in the `send_at` wire field.
   */
  sendAt?: {
    /**
     * Optional array value serialized in the `headers` wire field.
     */
    headers?: { [key: string]: unknown }[];
    /**
     * Optional `number` value serialized in the `template_id` wire field.
     */
    templateId?: number;
  };
}

/**
 * Typed representation of the `CampaignStats` API schema.
 */
export interface CampaignStats {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional `integer` value serialized in the `to_send` wire field.
   */
  toSend?: number;
  /**
   * Optional `integer` value serialized in the `sent` wire field.
   */
  sent?: number;
  /**
   * Optional `date`-formatted value serialized in the `started_at` wire field.
   */
  startedAt?: string;
  /**
   * Optional `date`-formatted value serialized in the `updated_at` wire field.
   */
  updatedAt?: string;
  /**
   * Optional `integer` value serialized in the `rate` wire field.
   */
  rate?: number;
  /**
   * Optional `integer` value serialized in the `net_rate` wire field.
   */
  netRate?: number;
}

/**
 * Typed representation of the `CampaignUpdate` API schema.
 */
export interface CampaignUpdate {
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `subject` wire field.
   */
  subject?: string;
  /**
   * Optional array value serialized in the `lists` wire field.
   */
  lists?: number[];
  /**
   * Optional `string` value serialized in the `from_email` wire field.
   */
  fromEmail?: string;
  /**
   * Optional `string` value serialized in the `messenger` wire field.
   */
  messenger?: string;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: string[];
  /**
   * Optional `boolean` value serialized in the `send_later` wire field.
   */
  sendLater?: boolean;
  /**
   * Optional object value serialized in the `send_at` wire field.
   */
  sendAt?: { [key: string]: unknown };
  /**
   * Optional array value serialized in the `headers` wire field.
   */
  headers?: { [key: string]: unknown }[];
  /**
   * Optional `integer` value serialized in the `template_id` wire field.
   */
  templateId?: number;
  /**
   * Optional `string` value serialized in the `content_type` wire field.
   */
  contentType?: string;
  /**
   * Optional `string` value serialized in the `body` wire field.
   */
  body?: string;
  /**
   * Optional `string` value serialized in the `altbody` wire field.
   */
  altbody?: string;
  /**
   * Optional `boolean` value serialized in the `archive` wire field.
   */
  archive?: boolean;
  /**
   * Optional `integer` value serialized in the `archive_template_id` wire field.
   */
  archiveTemplateId?: number;
  /**
   * Optional object value serialized in the `archive_meta` wire field.
   */
  archiveMeta?: { [key: string]: unknown };
}
