// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ImportStatus` API schema.
 */
export interface ImportStatus {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: {
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    name?: string;
    /**
     * Optional `integer` value serialized in the `total` wire field.
     */
    total?: number;
    /**
     * Optional `integer` value serialized in the `imported` wire field.
     */
    imported?: number;
    /**
     * Optional `string` value serialized in the `status` wire field.
     */
    status?: string;
  };
}
