// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ListModel` API schema.
 */
export interface ListModel {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `updated_at` wire field.
   */
  updatedAt?: string;
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional `string` value serialized in the `optin` wire field.
   */
  optin?: string;
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: string[];
  /**
   * Optional `integer` value serialized in the `subscriber_count` wire field.
   */
  subscriberCount?: number;
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
}

/**
 * Typed representation of the `NewList` API schema.
 */
export interface NewList {
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional enumerated value serialized in the `type` wire field.
   */
  type?: "public" | "private" | (string & {});
  /**
   * Optional enumerated value serialized in the `optin` wire field.
   */
  optin?: "single" | "double" | (string & {});
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: string[];
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
}
