// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `MediaFileObject` API schema.
 */
export interface MediaFileObject {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional `string` value serialized in the `filename` wire field.
   */
  filename?: string;
  /**
   * Optional `string` value serialized in the `content_type` wire field.
   */
  contentType?: string;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `thumb_url` wire field.
   */
  thumbUrl?: string;
  /**
   * Optional `string` value serialized in the `thumb_uri` wire field.
   */
  thumbUri?: string;
  /**
   * Optional `string` value serialized in the `provider` wire field.
   */
  provider?: string;
  /**
   * Optional object value serialized in the `meta` wire field.
   */
  meta?: { [key: string]: unknown };
  /**
   * Optional `string` value serialized in the `url` wire field.
   */
  url?: string;
  /**
   * Optional `string` value serialized in the `uri` wire field.
   */
  uri?: string;
}
