// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ServerConfig` API schema.
 */
export interface ServerConfig {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: {
    /**
     * Optional array value serialized in the `messengers` wire field.
     */
    messengers?: string[];
    /**
     * Optional array value serialized in the `langs` wire field.
     */
    langs?: {
      /**
       * Optional `string` value serialized in the `code` wire field.
       */
      code?: string;
      /**
       * Optional `string` value serialized in the `name` wire field.
       */
      name?: string;
    }[];
    /**
     * Optional `string` value serialized in the `lang` wire field.
     */
    lang?: string;
    /**
     * Optional `string` value serialized in the `update` wire field.
     */
    update?: string;
    /**
     * Optional `boolean` value serialized in the `needs_restart` wire field.
     */
    needsRestart?: boolean;
    /**
     * Optional `string` value serialized in the `version` wire field.
     */
    version?: string;
  };
}
