// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `LanguagePack` API schema.
 */
export interface LanguagePack {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: {
    /**
     * Optional `string` value serialized in the `_.code` wire field.
     */
    code?: string;
    /**
     * Optional `string` value serialized in the `_.name` wire field.
     */
    name?: string;
    /**
     * Optional `string` value serialized in the `admin.errorMarshallingConfig` wire field.
     */
    adminErrorMarshallingConfig?: string;
    /**
     * Optional `string` value serialized in the `analytics.count` wire field.
     */
    analyticsCount?: string;
    /**
     * Optional `string` value serialized in the `analytics.fromDate` wire field.
     */
    analyticsFromDate?: string;
    /**
     * Optional `string` value serialized in the `analytics.invalidDates` wire field.
     */
    analyticsInvalidDates?: string;
    /**
     * Optional `string` value serialized in the `analytics.isUnique` wire field.
     */
    analyticsIsUnique?: string;
    /**
     * Optional `string` value serialized in the `analytics.links` wire field.
     */
    analyticsLinks?: string;
    /**
     * Optional `string` value serialized in the `analytics.nonUnique` wire field.
     */
    analyticsNonUnique?: string;
    /**
     * Optional `string` value serialized in the `analytics.title` wire field.
     */
    analyticsTitle?: string;
    /**
     * Optional `string` value serialized in the `analytics.toDate` wire field.
     */
    analyticsToDate?: string;
    /**
     * Optional `string` value serialized in the `bounces.numSelected` wire field.
     */
    bouncesNumSelected?: string;
    /**
     * Optional `string` value serialized in the `bounces.selectAll` wire field.
     */
    bouncesSelectAll?: string;
    /**
     * Optional `string` value serialized in the `bounces.source` wire field.
     */
    bouncesSource?: string;
    /**
     * Optional `string` value serialized in the `bounces.unknownService` wire field.
     */
    bouncesUnknownService?: string;
    /**
     * Optional `string` value serialized in the `bounces.view` wire field.
     */
    bouncesView?: string;
    /**
     * Optional `string` value serialized in the `campaigns.addAltText` wire field.
     */
    campaignsAddAltText?: string;
    /**
     * Optional `string` value serialized in the `campaigns.archive` wire field.
     */
    campaignsArchive?: string;
    /**
     * Optional `string` value serialized in the `campaigns.archiveEnable` wire field.
     */
    campaignsArchiveEnable?: string;
    /**
     * Optional `string` value serialized in the `campaigns.archiveHelp` wire field.
     */
    campaignsArchiveHelp?: string;
    /**
     * Optional `string` value serialized in the `campaigns.archiveMeta` wire field.
     */
    campaignsArchiveMeta?: string;
    /**
     * Optional `string` value serialized in the `campaigns.archiveMetaHelp` wire field.
     */
    campaignsArchiveMetaHelp?: string;
    /**
     * Optional `string` value serialized in the `campaigns.cantUpdate` wire field.
     */
    campaignsCantUpdate?: string;
    /**
     * Optional `string` value serialized in the `campaigns.clicks` wire field.
     */
    campaignsClicks?: string;
    /**
     * Optional `string` value serialized in the `campaigns.confirmDelete` wire field.
     */
    campaignsConfirmDelete?: string;
    /**
     * Optional `string` value serialized in the `campaigns.confirmSchedule` wire field.
     */
    campaignsConfirmSchedule?: string;
    /**
     * Optional `string` value serialized in the `campaigns.confirmSwitchFormat` wire field.
     */
    campaignsConfirmSwitchFormat?: string;
    /**
     * Optional `string` value serialized in the `campaigns.content` wire field.
     */
    campaignsContent?: string;
    /**
     * Optional `string` value serialized in the `campaigns.contentHelp` wire field.
     */
    campaignsContentHelp?: string;
    /**
     * Optional `string` value serialized in the `campaigns.continue` wire field.
     */
    campaignsContinue?: string;
    /**
     * Optional `string` value serialized in the `campaigns.copyOf` wire field.
     */
    campaignsCopyOf?: string;
    /**
     * Optional `string` value serialized in the `campaigns.customHeadersHelp` wire field.
     */
    campaignsCustomHeadersHelp?: string;
    /**
     * Optional `string` value serialized in the `campaigns.dateAndTime` wire field.
     */
    campaignsDateAndTime?: string;
    /**
     * Optional `string` value serialized in the `campaigns.ended` wire field.
     */
    campaignsEnded?: string;
    /**
     * Optional `string` value serialized in the `campaigns.errorSendTest` wire field.
     */
    campaignsErrorSendTest?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fieldInvalidBody` wire field.
     */
    campaignsFieldInvalidBody?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fieldInvalidFromEmail` wire field.
     */
    campaignsFieldInvalidFromEmail?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fieldInvalidListIDs` wire field.
     */
    campaignsFieldInvalidListIds?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fieldInvalidMessenger` wire field.
     */
    campaignsFieldInvalidMessenger?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fieldInvalidName` wire field.
     */
    campaignsFieldInvalidName?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fieldInvalidSendAt` wire field.
     */
    campaignsFieldInvalidSendAt?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fieldInvalidSubject` wire field.
     */
    campaignsFieldInvalidSubject?: string;
    /**
     * Optional `string` value serialized in the `campaigns.formatHTML` wire field.
     */
    campaignsFormatHtml?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fromAddress` wire field.
     */
    campaignsFromAddress?: string;
    /**
     * Optional `string` value serialized in the `campaigns.fromAddressPlaceholder` wire field.
     */
    campaignsFromAddressPlaceholder?: string;
    /**
     * Optional `string` value serialized in the `campaigns.invalid` wire field.
     */
    campaignsInvalid?: string;
    /**
     * Optional `string` value serialized in the `campaigns.invalidCustomHeaders` wire field.
     */
    campaignsInvalidCustomHeaders?: string;
    /**
     * Optional `string` value serialized in the `campaigns.markdown` wire field.
     */
    campaignsMarkdown?: string;
    /**
     * Optional `string` value serialized in the `campaigns.needsSendAt` wire field.
     */
    campaignsNeedsSendAt?: string;
    /**
     * Optional `string` value serialized in the `campaigns.newCampaign` wire field.
     */
    campaignsNewCampaign?: string;
    /**
     * Optional `string` value serialized in the `campaigns.noKnownSubsToTest` wire field.
     */
    campaignsNoKnownSubsToTest?: string;
    /**
     * Optional `string` value serialized in the `campaigns.noOptinLists` wire field.
     */
    campaignsNoOptinLists?: string;
    /**
     * Optional `string` value serialized in the `campaigns.noSubs` wire field.
     */
    campaignsNoSubs?: string;
    /**
     * Optional `string` value serialized in the `campaigns.noSubsToTest` wire field.
     */
    campaignsNoSubsToTest?: string;
    /**
     * Optional `string` value serialized in the `campaigns.notFound` wire field.
     */
    campaignsNotFound?: string;
    /**
     * Optional `string` value serialized in the `campaigns.onlyActiveCancel` wire field.
     */
    campaignsOnlyActiveCancel?: string;
    /**
     * Optional `string` value serialized in the `campaigns.onlyActivePause` wire field.
     */
    campaignsOnlyActivePause?: string;
    /**
     * Optional `string` value serialized in the `campaigns.onlyDraftAsScheduled` wire field.
     */
    campaignsOnlyDraftAsScheduled?: string;
    /**
     * Optional `string` value serialized in the `campaigns.onlyPausedDraft` wire field.
     */
    campaignsOnlyPausedDraft?: string;
    /**
     * Optional `string` value serialized in the `campaigns.onlyScheduledAsDraft` wire field.
     */
    campaignsOnlyScheduledAsDraft?: string;
    /**
     * Optional `string` value serialized in the `campaigns.pause` wire field.
     */
    campaignsPause?: string;
    /**
     * Optional `string` value serialized in the `campaigns.plainText` wire field.
     */
    campaignsPlainText?: string;
    /**
     * Optional `string` value serialized in the `campaigns.preview` wire field.
     */
    campaignsPreview?: string;
    /**
     * Optional `string` value serialized in the `campaigns.progress` wire field.
     */
    campaignsProgress?: string;
    /**
     * Optional `string` value serialized in the `campaigns.queryPlaceholder` wire field.
     */
    campaignsQueryPlaceholder?: string;
    /**
     * Optional `string` value serialized in the `campaigns.rateMinuteShort` wire field.
     */
    campaignsRateMinuteShort?: string;
    /**
     * Optional `string` value serialized in the `campaigns.rawHTML` wire field.
     */
    campaignsRawHtml?: string;
    /**
     * Optional `string` value serialized in the `campaigns.removeAltText` wire field.
     */
    campaignsRemoveAltText?: string;
    /**
     * Optional `string` value serialized in the `campaigns.richText` wire field.
     */
    campaignsRichText?: string;
    /**
     * Optional `string` value serialized in the `campaigns.schedule` wire field.
     */
    campaignsSchedule?: string;
    /**
     * Optional `string` value serialized in the `campaigns.scheduled` wire field.
     */
    campaignsScheduled?: string;
    /**
     * Optional `string` value serialized in the `campaigns.send` wire field.
     */
    campaignsSend?: string;
    /**
     * Optional `string` value serialized in the `campaigns.sendLater` wire field.
     */
    campaignsSendLater?: string;
    /**
     * Optional `string` value serialized in the `campaigns.sendTest` wire field.
     */
    campaignsSendTest?: string;
    /**
     * Optional `string` value serialized in the `campaigns.sendTestHelp` wire field.
     */
    campaignsSendTestHelp?: string;
    /**
     * Optional `string` value serialized in the `campaigns.sendToLists` wire field.
     */
    campaignsSendToLists?: string;
    /**
     * Optional `string` value serialized in the `campaigns.sent` wire field.
     */
    campaignsSent?: string;
    /**
     * Optional `string` value serialized in the `campaigns.start` wire field.
     */
    campaignsStart?: string;
    /**
     * Optional `string` value serialized in the `campaigns.started` wire field.
     */
    campaignsStarted?: string;
    /**
     * Optional `string` value serialized in the `campaigns.startedAt` wire field.
     */
    campaignsStartedAt?: string;
    /**
     * Optional `string` value serialized in the `campaigns.stats` wire field.
     */
    campaignsStats?: string;
    /**
     * Optional `string` value serialized in the `campaigns.status.cancelled` wire field.
     */
    campaignsStatusCancelled?: string;
    /**
     * Optional `string` value serialized in the `campaigns.status.draft` wire field.
     */
    campaignsStatusDraft?: string;
    /**
     * Optional `string` value serialized in the `campaigns.status.finished` wire field.
     */
    campaignsStatusFinished?: string;
    /**
     * Optional `string` value serialized in the `campaigns.status.paused` wire field.
     */
    campaignsStatusPaused?: string;
    /**
     * Optional `string` value serialized in the `campaigns.status.running` wire field.
     */
    campaignsStatusRunning?: string;
    /**
     * Optional `string` value serialized in the `campaigns.status.scheduled` wire field.
     */
    campaignsStatusScheduled?: string;
    /**
     * Optional `string` value serialized in the `campaigns.statusChanged` wire field.
     */
    campaignsStatusChanged?: string;
    /**
     * Optional `string` value serialized in the `campaigns.subject` wire field.
     */
    campaignsSubject?: string;
    /**
     * Optional `string` value serialized in the `campaigns.testEmails` wire field.
     */
    campaignsTestEmails?: string;
    /**
     * Optional `string` value serialized in the `campaigns.testSent` wire field.
     */
    campaignsTestSent?: string;
    /**
     * Optional `string` value serialized in the `campaigns.timestamps` wire field.
     */
    campaignsTimestamps?: string;
    /**
     * Optional `string` value serialized in the `campaigns.trackLink` wire field.
     */
    campaignsTrackLink?: string;
    /**
     * Optional `string` value serialized in the `campaigns.views` wire field.
     */
    campaignsViews?: string;
    /**
     * Optional `string` value serialized in the `dashboard.campaignViews` wire field.
     */
    dashboardCampaignViews?: string;
    /**
     * Optional `string` value serialized in the `dashboard.linkClicks` wire field.
     */
    dashboardLinkClicks?: string;
    /**
     * Optional `string` value serialized in the `dashboard.messagesSent` wire field.
     */
    dashboardMessagesSent?: string;
    /**
     * Optional `string` value serialized in the `dashboard.orphanSubs` wire field.
     */
    dashboardOrphanSubs?: string;
    /**
     * Optional `string` value serialized in the `email.data.info` wire field.
     */
    emailDataInfo?: string;
    /**
     * Optional `string` value serialized in the `email.data.title` wire field.
     */
    emailDataTitle?: string;
    /**
     * Optional `string` value serialized in the `email.optin.confirmSub` wire field.
     */
    emailOptinConfirmSub?: string;
    /**
     * Optional `string` value serialized in the `email.optin.confirmSubHelp` wire field.
     */
    emailOptinConfirmSubHelp?: string;
    /**
     * Optional `string` value serialized in the `email.optin.confirmSubInfo` wire field.
     */
    emailOptinConfirmSubInfo?: string;
    /**
     * Optional `string` value serialized in the `email.optin.confirmSubTitle` wire field.
     */
    emailOptinConfirmSubTitle?: string;
    /**
     * Optional `string` value serialized in the `email.optin.confirmSubWelcome` wire field.
     */
    emailOptinConfirmSubWelcome?: string;
    /**
     * Optional `string` value serialized in the `email.optin.privateList` wire field.
     */
    emailOptinPrivateList?: string;
    /**
     * Optional `string` value serialized in the `email.status.campaignReason` wire field.
     */
    emailStatusCampaignReason?: string;
    /**
     * Optional `string` value serialized in the `email.status.campaignSent` wire field.
     */
    emailStatusCampaignSent?: string;
    /**
     * Optional `string` value serialized in the `email.status.campaignUpdateTitle` wire field.
     */
    emailStatusCampaignUpdateTitle?: string;
    /**
     * Optional `string` value serialized in the `email.status.importFile` wire field.
     */
    emailStatusImportFile?: string;
    /**
     * Optional `string` value serialized in the `email.status.importRecords` wire field.
     */
    emailStatusImportRecords?: string;
    /**
     * Optional `string` value serialized in the `email.status.importTitle` wire field.
     */
    emailStatusImportTitle?: string;
    /**
     * Optional `string` value serialized in the `email.status.status` wire field.
     */
    emailStatusStatus?: string;
    /**
     * Optional `string` value serialized in the `email.unsub` wire field.
     */
    emailUnsub?: string;
    /**
     * Optional `string` value serialized in the `email.unsubHelp` wire field.
     */
    emailUnsubHelp?: string;
    /**
     * Optional `string` value serialized in the `email.viewInBrowser` wire field.
     */
    emailViewInBrowser?: string;
    /**
     * Optional `string` value serialized in the `forms.formHTML` wire field.
     */
    formsFormHtml?: string;
    /**
     * Optional `string` value serialized in the `forms.formHTMLHelp` wire field.
     */
    formsFormHtmlHelp?: string;
    /**
     * Optional `string` value serialized in the `forms.noPublicLists` wire field.
     */
    formsNoPublicLists?: string;
    /**
     * Optional `string` value serialized in the `forms.publicLists` wire field.
     */
    formsPublicLists?: string;
    /**
     * Optional `string` value serialized in the `forms.publicSubPage` wire field.
     */
    formsPublicSubPage?: string;
    /**
     * Optional `string` value serialized in the `forms.selectHelp` wire field.
     */
    formsSelectHelp?: string;
    /**
     * Optional `string` value serialized in the `forms.title` wire field.
     */
    formsTitle?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.add` wire field.
     */
    globalsButtonsAdd?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.addNew` wire field.
     */
    globalsButtonsAddNew?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.back` wire field.
     */
    globalsButtonsBack?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.cancel` wire field.
     */
    globalsButtonsCancel?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.clone` wire field.
     */
    globalsButtonsClone?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.close` wire field.
     */
    globalsButtonsClose?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.continue` wire field.
     */
    globalsButtonsContinue?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.delete` wire field.
     */
    globalsButtonsDelete?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.deleteAll` wire field.
     */
    globalsButtonsDeleteAll?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.edit` wire field.
     */
    globalsButtonsEdit?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.enabled` wire field.
     */
    globalsButtonsEnabled?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.insert` wire field.
     */
    globalsButtonsInsert?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.learnMore` wire field.
     */
    globalsButtonsLearnMore?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.more` wire field.
     */
    globalsButtonsMore?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.new` wire field.
     */
    globalsButtonsNew?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.ok` wire field.
     */
    globalsButtonsOk?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.remove` wire field.
     */
    globalsButtonsRemove?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.save` wire field.
     */
    globalsButtonsSave?: string;
    /**
     * Optional `string` value serialized in the `globals.buttons.saveChanges` wire field.
     */
    globalsButtonsSaveChanges?: string;
    /**
     * Optional `string` value serialized in the `globals.days.0` wire field.
     */
    globalsDays0?: string;
    /**
     * Optional `string` value serialized in the `globals.days.1` wire field.
     */
    globalsDays1?: string;
    /**
     * Optional `string` value serialized in the `globals.days.2` wire field.
     */
    globalsDays2?: string;
    /**
     * Optional `string` value serialized in the `globals.days.3` wire field.
     */
    globalsDays3?: string;
    /**
     * Optional `string` value serialized in the `globals.days.4` wire field.
     */
    globalsDays4?: string;
    /**
     * Optional `string` value serialized in the `globals.days.5` wire field.
     */
    globalsDays5?: string;
    /**
     * Optional `string` value serialized in the `globals.days.6` wire field.
     */
    globalsDays6?: string;
    /**
     * Optional `string` value serialized in the `globals.days.7` wire field.
     */
    globalsDays7?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.createdAt` wire field.
     */
    globalsFieldsCreatedAt?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.description` wire field.
     */
    globalsFieldsDescription?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.id` wire field.
     */
    globalsFieldsId?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.name` wire field.
     */
    globalsFieldsName?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.status` wire field.
     */
    globalsFieldsStatus?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.type` wire field.
     */
    globalsFieldsType?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.updatedAt` wire field.
     */
    globalsFieldsUpdatedAt?: string;
    /**
     * Optional `string` value serialized in the `globals.fields.uuid` wire field.
     */
    globalsFieldsUuid?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.confirm` wire field.
     */
    globalsMessagesConfirm?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.confirmDiscard` wire field.
     */
    globalsMessagesConfirmDiscard?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.created` wire field.
     */
    globalsMessagesCreated?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.deleted` wire field.
     */
    globalsMessagesDeleted?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.deletedCount` wire field.
     */
    globalsMessagesDeletedCount?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.done` wire field.
     */
    globalsMessagesDone?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.emptyState` wire field.
     */
    globalsMessagesEmptyState?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.errorCreating` wire field.
     */
    globalsMessagesErrorCreating?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.errorDeleting` wire field.
     */
    globalsMessagesErrorDeleting?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.errorFetching` wire field.
     */
    globalsMessagesErrorFetching?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.errorInvalidIDs` wire field.
     */
    globalsMessagesErrorInvalidIds?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.errorUUID` wire field.
     */
    globalsMessagesErrorUuid?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.errorUpdating` wire field.
     */
    globalsMessagesErrorUpdating?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.internalError` wire field.
     */
    globalsMessagesInternalError?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.invalidData` wire field.
     */
    globalsMessagesInvalidData?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.invalidID` wire field.
     */
    globalsMessagesInvalidId?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.invalidUUID` wire field.
     */
    globalsMessagesInvalidUuid?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.missingFields` wire field.
     */
    globalsMessagesMissingFields?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.notFound` wire field.
     */
    globalsMessagesNotFound?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.passwordChange` wire field.
     */
    globalsMessagesPasswordChange?: string;
    /**
     * Optional `string` value serialized in the `globals.messages.updated` wire field.
     */
    globalsMessagesUpdated?: string;
    /**
     * Optional `string` value serialized in the `globals.months.1` wire field.
     */
    globalsMonths1?: string;
    /**
     * Optional `string` value serialized in the `globals.months.10` wire field.
     */
    globalsMonths10?: string;
    /**
     * Optional `string` value serialized in the `globals.months.11` wire field.
     */
    globalsMonths11?: string;
    /**
     * Optional `string` value serialized in the `globals.months.12` wire field.
     */
    globalsMonths12?: string;
    /**
     * Optional `string` value serialized in the `globals.months.2` wire field.
     */
    globalsMonths2?: string;
    /**
     * Optional `string` value serialized in the `globals.months.3` wire field.
     */
    globalsMonths3?: string;
    /**
     * Optional `string` value serialized in the `globals.months.4` wire field.
     */
    globalsMonths4?: string;
    /**
     * Optional `string` value serialized in the `globals.months.5` wire field.
     */
    globalsMonths5?: string;
    /**
     * Optional `string` value serialized in the `globals.months.6` wire field.
     */
    globalsMonths6?: string;
    /**
     * Optional `string` value serialized in the `globals.months.7` wire field.
     */
    globalsMonths7?: string;
    /**
     * Optional `string` value serialized in the `globals.months.8` wire field.
     */
    globalsMonths8?: string;
    /**
     * Optional `string` value serialized in the `globals.months.9` wire field.
     */
    globalsMonths9?: string;
    /**
     * Optional `string` value serialized in the `globals.states.off` wire field.
     */
    globalsStatesOff?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.all` wire field.
     */
    globalsTermsAll?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.analytics` wire field.
     */
    globalsTermsAnalytics?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.bounce` wire field.
     */
    globalsTermsBounce?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.bounces` wire field.
     */
    globalsTermsBounces?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.campaign` wire field.
     */
    globalsTermsCampaign?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.campaigns` wire field.
     */
    globalsTermsCampaigns?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.dashboard` wire field.
     */
    globalsTermsDashboard?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.day` wire field.
     */
    globalsTermsDay?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.hour` wire field.
     */
    globalsTermsHour?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.list` wire field.
     */
    globalsTermsList?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.lists` wire field.
     */
    globalsTermsLists?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.media` wire field.
     */
    globalsTermsMedia?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.messenger` wire field.
     */
    globalsTermsMessenger?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.messengers` wire field.
     */
    globalsTermsMessengers?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.minute` wire field.
     */
    globalsTermsMinute?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.month` wire field.
     */
    globalsTermsMonth?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.second` wire field.
     */
    globalsTermsSecond?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.settings` wire field.
     */
    globalsTermsSettings?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.subscriber` wire field.
     */
    globalsTermsSubscriber?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.subscribers` wire field.
     */
    globalsTermsSubscribers?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.subscriptions` wire field.
     */
    globalsTermsSubscriptions?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.tag` wire field.
     */
    globalsTermsTag?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.tags` wire field.
     */
    globalsTermsTags?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.template` wire field.
     */
    globalsTermsTemplate?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.templates` wire field.
     */
    globalsTermsTemplates?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.tx` wire field.
     */
    globalsTermsTx?: string;
    /**
     * Optional `string` value serialized in the `globals.terms.year` wire field.
     */
    globalsTermsYear?: string;
    /**
     * Optional `string` value serialized in the `import.alreadyRunning` wire field.
     */
    importAlreadyRunning?: string;
    /**
     * Optional `string` value serialized in the `import.blocklist` wire field.
     */
    importBlocklist?: string;
    /**
     * Optional `string` value serialized in the `import.csvDelim` wire field.
     */
    importCsvDelim?: string;
    /**
     * Optional `string` value serialized in the `import.csvDelimHelp` wire field.
     */
    importCsvDelimHelp?: string;
    /**
     * Optional `string` value serialized in the `import.csvExample` wire field.
     */
    importCsvExample?: string;
    /**
     * Optional `string` value serialized in the `import.csvFile` wire field.
     */
    importCsvFile?: string;
    /**
     * Optional `string` value serialized in the `import.csvFileHelp` wire field.
     */
    importCsvFileHelp?: string;
    /**
     * Optional `string` value serialized in the `import.errorCopyingFile` wire field.
     */
    importErrorCopyingFile?: string;
    /**
     * Optional `string` value serialized in the `import.errorProcessingZIP` wire field.
     */
    importErrorProcessingZip?: string;
    /**
     * Optional `string` value serialized in the `import.errorStarting` wire field.
     */
    importErrorStarting?: string;
    /**
     * Optional `string` value serialized in the `import.importDone` wire field.
     */
    importImportDone?: string;
    /**
     * Optional `string` value serialized in the `import.importStarted` wire field.
     */
    importImportStarted?: string;
    /**
     * Optional `string` value serialized in the `import.instructions` wire field.
     */
    importInstructions?: string;
    /**
     * Optional `string` value serialized in the `import.instructionsHelp` wire field.
     */
    importInstructionsHelp?: string;
    /**
     * Optional `string` value serialized in the `import.invalidDelim` wire field.
     */
    importInvalidDelim?: string;
    /**
     * Optional `string` value serialized in the `import.invalidFile` wire field.
     */
    importInvalidFile?: string;
    /**
     * Optional `string` value serialized in the `import.invalidMode` wire field.
     */
    importInvalidMode?: string;
    /**
     * Optional `string` value serialized in the `import.invalidParams` wire field.
     */
    importInvalidParams?: string;
    /**
     * Optional `string` value serialized in the `import.invalidSubStatus` wire field.
     */
    importInvalidSubStatus?: string;
    /**
     * Optional `string` value serialized in the `import.listSubHelp` wire field.
     */
    importListSubHelp?: string;
    /**
     * Optional `string` value serialized in the `import.mode` wire field.
     */
    importMode?: string;
    /**
     * Optional `string` value serialized in the `import.overwrite` wire field.
     */
    importOverwrite?: string;
    /**
     * Optional `string` value serialized in the `import.overwriteHelp` wire field.
     */
    importOverwriteHelp?: string;
    /**
     * Optional `string` value serialized in the `import.recordsCount` wire field.
     */
    importRecordsCount?: string;
    /**
     * Optional `string` value serialized in the `import.stopImport` wire field.
     */
    importStopImport?: string;
    /**
     * Optional `string` value serialized in the `import.subscribe` wire field.
     */
    importSubscribe?: string;
    /**
     * Optional `string` value serialized in the `import.subscribeWarning` wire field.
     */
    importSubscribeWarning?: string;
    /**
     * Optional `string` value serialized in the `import.title` wire field.
     */
    importTitle?: string;
    /**
     * Optional `string` value serialized in the `import.upload` wire field.
     */
    importUpload?: string;
    /**
     * Optional `string` value serialized in the `lists.confirmDelete` wire field.
     */
    listsConfirmDelete?: string;
    /**
     * Optional `string` value serialized in the `lists.confirmSub` wire field.
     */
    listsConfirmSub?: string;
    /**
     * Optional `string` value serialized in the `lists.invalidName` wire field.
     */
    listsInvalidName?: string;
    /**
     * Optional `string` value serialized in the `lists.newList` wire field.
     */
    listsNewList?: string;
    /**
     * Optional `string` value serialized in the `lists.optin` wire field.
     */
    listsOptin?: string;
    /**
     * Optional `string` value serialized in the `lists.optinHelp` wire field.
     */
    listsOptinHelp?: string;
    /**
     * Optional `string` value serialized in the `lists.optinTo` wire field.
     */
    listsOptinTo?: string;
    /**
     * Optional `string` value serialized in the `lists.optins.double` wire field.
     */
    listsOptinsDouble?: string;
    /**
     * Optional `string` value serialized in the `lists.optins.single` wire field.
     */
    listsOptinsSingle?: string;
    /**
     * Optional `string` value serialized in the `lists.sendCampaign` wire field.
     */
    listsSendCampaign?: string;
    /**
     * Optional `string` value serialized in the `lists.sendOptinCampaign` wire field.
     */
    listsSendOptinCampaign?: string;
    /**
     * Optional `string` value serialized in the `lists.type` wire field.
     */
    listsType?: string;
    /**
     * Optional `string` value serialized in the `lists.typeHelp` wire field.
     */
    listsTypeHelp?: string;
    /**
     * Optional `string` value serialized in the `lists.types.private` wire field.
     */
    listsTypesPrivate?: string;
    /**
     * Optional `string` value serialized in the `lists.types.public` wire field.
     */
    listsTypesPublic?: string;
    /**
     * Optional `string` value serialized in the `logs.title` wire field.
     */
    logsTitle?: string;
    /**
     * Optional `string` value serialized in the `maintenance.help` wire field.
     */
    maintenanceHelp?: string;
    /**
     * Optional `string` value serialized in the `maintenance.maintenance.unconfirmedOptins` wire field.
     */
    maintenanceMaintenanceUnconfirmedOptins?: string;
    /**
     * Optional `string` value serialized in the `maintenance.olderThan` wire field.
     */
    maintenanceOlderThan?: string;
    /**
     * Optional `string` value serialized in the `maintenance.title` wire field.
     */
    maintenanceTitle?: string;
    /**
     * Optional `string` value serialized in the `maintenance.unconfirmedSubs` wire field.
     */
    maintenanceUnconfirmedSubs?: string;
    /**
     * Optional `string` value serialized in the `media.errorReadingFile` wire field.
     */
    mediaErrorReadingFile?: string;
    /**
     * Optional `string` value serialized in the `media.errorResizing` wire field.
     */
    mediaErrorResizing?: string;
    /**
     * Optional `string` value serialized in the `media.errorSavingThumbnail` wire field.
     */
    mediaErrorSavingThumbnail?: string;
    /**
     * Optional `string` value serialized in the `media.errorUploading` wire field.
     */
    mediaErrorUploading?: string;
    /**
     * Optional `string` value serialized in the `media.invalidFile` wire field.
     */
    mediaInvalidFile?: string;
    /**
     * Optional `string` value serialized in the `media.title` wire field.
     */
    mediaTitle?: string;
    /**
     * Optional `string` value serialized in the `media.unsupportedFileType` wire field.
     */
    mediaUnsupportedFileType?: string;
    /**
     * Optional `string` value serialized in the `media.upload` wire field.
     */
    mediaUpload?: string;
    /**
     * Optional `string` value serialized in the `media.uploadHelp` wire field.
     */
    mediaUploadHelp?: string;
    /**
     * Optional `string` value serialized in the `media.uploadImage` wire field.
     */
    mediaUploadImage?: string;
    /**
     * Optional `string` value serialized in the `menu.allCampaigns` wire field.
     */
    menuAllCampaigns?: string;
    /**
     * Optional `string` value serialized in the `menu.allLists` wire field.
     */
    menuAllLists?: string;
    /**
     * Optional `string` value serialized in the `menu.allSubscribers` wire field.
     */
    menuAllSubscribers?: string;
    /**
     * Optional `string` value serialized in the `menu.dashboard` wire field.
     */
    menuDashboard?: string;
    /**
     * Optional `string` value serialized in the `menu.forms` wire field.
     */
    menuForms?: string;
    /**
     * Optional `string` value serialized in the `menu.import` wire field.
     */
    menuImport?: string;
    /**
     * Optional `string` value serialized in the `menu.logs` wire field.
     */
    menuLogs?: string;
    /**
     * Optional `string` value serialized in the `menu.maintenance` wire field.
     */
    menuMaintenance?: string;
    /**
     * Optional `string` value serialized in the `menu.media` wire field.
     */
    menuMedia?: string;
    /**
     * Optional `string` value serialized in the `menu.newCampaign` wire field.
     */
    menuNewCampaign?: string;
    /**
     * Optional `string` value serialized in the `menu.settings` wire field.
     */
    menuSettings?: string;
    /**
     * Optional `string` value serialized in the `public.archiveEmpty` wire field.
     */
    publicArchiveEmpty?: string;
    /**
     * Optional `string` value serialized in the `public.archiveTitle` wire field.
     */
    publicArchiveTitle?: string;
    /**
     * Optional `string` value serialized in the `public.blocklisted` wire field.
     */
    publicBlocklisted?: string;
    /**
     * Optional `string` value serialized in the `public.campaignNotFound` wire field.
     */
    publicCampaignNotFound?: string;
    /**
     * Optional `string` value serialized in the `public.confirmOptinSubTitle` wire field.
     */
    publicConfirmOptinSubTitle?: string;
    /**
     * Optional `string` value serialized in the `public.confirmSub` wire field.
     */
    publicConfirmSub?: string;
    /**
     * Optional `string` value serialized in the `public.confirmSubInfo` wire field.
     */
    publicConfirmSubInfo?: string;
    /**
     * Optional `string` value serialized in the `public.confirmSubTitle` wire field.
     */
    publicConfirmSubTitle?: string;
    /**
     * Optional `string` value serialized in the `public.dataRemoved` wire field.
     */
    publicDataRemoved?: string;
    /**
     * Optional `string` value serialized in the `public.dataRemovedTitle` wire field.
     */
    publicDataRemovedTitle?: string;
    /**
     * Optional `string` value serialized in the `public.dataSent` wire field.
     */
    publicDataSent?: string;
    /**
     * Optional `string` value serialized in the `public.dataSentTitle` wire field.
     */
    publicDataSentTitle?: string;
    /**
     * Optional `string` value serialized in the `public.errorFetchingCampaign` wire field.
     */
    publicErrorFetchingCampaign?: string;
    /**
     * Optional `string` value serialized in the `public.errorFetchingEmail` wire field.
     */
    publicErrorFetchingEmail?: string;
    /**
     * Optional `string` value serialized in the `public.errorFetchingLists` wire field.
     */
    publicErrorFetchingLists?: string;
    /**
     * Optional `string` value serialized in the `public.errorProcessingRequest` wire field.
     */
    publicErrorProcessingRequest?: string;
    /**
     * Optional `string` value serialized in the `public.errorTitle` wire field.
     */
    publicErrorTitle?: string;
    /**
     * Optional `string` value serialized in the `public.invalidFeature` wire field.
     */
    publicInvalidFeature?: string;
    /**
     * Optional `string` value serialized in the `public.invalidLink` wire field.
     */
    publicInvalidLink?: string;
    /**
     * Optional `string` value serialized in the `public.managePrefs` wire field.
     */
    publicManagePrefs?: string;
    /**
     * Optional `string` value serialized in the `public.managePrefsUnsub` wire field.
     */
    publicManagePrefsUnsub?: string;
    /**
     * Optional `string` value serialized in the `public.noListsAvailable` wire field.
     */
    publicNoListsAvailable?: string;
    /**
     * Optional `string` value serialized in the `public.noListsSelected` wire field.
     */
    publicNoListsSelected?: string;
    /**
     * Optional `string` value serialized in the `public.noSubInfo` wire field.
     */
    publicNoSubInfo?: string;
    /**
     * Optional `string` value serialized in the `public.noSubTitle` wire field.
     */
    publicNoSubTitle?: string;
    /**
     * Optional `string` value serialized in the `public.notFoundTitle` wire field.
     */
    publicNotFoundTitle?: string;
    /**
     * Optional `string` value serialized in the `public.prefsSaved` wire field.
     */
    publicPrefsSaved?: string;
    /**
     * Optional `string` value serialized in the `public.privacyConfirmWipe` wire field.
     */
    publicPrivacyConfirmWipe?: string;
    /**
     * Optional `string` value serialized in the `public.privacyExport` wire field.
     */
    publicPrivacyExport?: string;
    /**
     * Optional `string` value serialized in the `public.privacyExportHelp` wire field.
     */
    publicPrivacyExportHelp?: string;
    /**
     * Optional `string` value serialized in the `public.privacyTitle` wire field.
     */
    publicPrivacyTitle?: string;
    /**
     * Optional `string` value serialized in the `public.privacyWipe` wire field.
     */
    publicPrivacyWipe?: string;
    /**
     * Optional `string` value serialized in the `public.privacyWipeHelp` wire field.
     */
    publicPrivacyWipeHelp?: string;
    /**
     * Optional `string` value serialized in the `public.sub` wire field.
     */
    publicSub?: string;
    /**
     * Optional `string` value serialized in the `public.subConfirmed` wire field.
     */
    publicSubConfirmed?: string;
    /**
     * Optional `string` value serialized in the `public.subConfirmedTitle` wire field.
     */
    publicSubConfirmedTitle?: string;
    /**
     * Optional `string` value serialized in the `public.subName` wire field.
     */
    publicSubName?: string;
    /**
     * Optional `string` value serialized in the `public.subNotFound` wire field.
     */
    publicSubNotFound?: string;
    /**
     * Optional `string` value serialized in the `public.subOptinPending` wire field.
     */
    publicSubOptinPending?: string;
    /**
     * Optional `string` value serialized in the `public.subPrivateList` wire field.
     */
    publicSubPrivateList?: string;
    /**
     * Optional `string` value serialized in the `public.subTitle` wire field.
     */
    publicSubTitle?: string;
    /**
     * Optional `string` value serialized in the `public.unsub` wire field.
     */
    publicUnsub?: string;
    /**
     * Optional `string` value serialized in the `public.unsubFull` wire field.
     */
    publicUnsubFull?: string;
    /**
     * Optional `string` value serialized in the `public.unsubHelp` wire field.
     */
    publicUnsubHelp?: string;
    /**
     * Optional `string` value serialized in the `public.unsubTitle` wire field.
     */
    publicUnsubTitle?: string;
    /**
     * Optional `string` value serialized in the `public.unsubbedInfo` wire field.
     */
    publicUnsubbedInfo?: string;
    /**
     * Optional `string` value serialized in the `public.unsubbedTitle` wire field.
     */
    publicUnsubbedTitle?: string;
    /**
     * Optional `string` value serialized in the `public.unsubscribeTitle` wire field.
     */
    publicUnsubscribeTitle?: string;
    /**
     * Optional `string` value serialized in the `settings.appearance.adminHelp` wire field.
     */
    settingsAppearanceAdminHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.appearance.adminName` wire field.
     */
    settingsAppearanceAdminName?: string;
    /**
     * Optional `string` value serialized in the `settings.appearance.customCSS` wire field.
     */
    settingsAppearanceCustomCss?: string;
    /**
     * Optional `string` value serialized in the `settings.appearance.customJS` wire field.
     */
    settingsAppearanceCustomJs?: string;
    /**
     * Optional `string` value serialized in the `settings.appearance.name` wire field.
     */
    settingsAppearanceName?: string;
    /**
     * Optional `string` value serialized in the `settings.appearance.publicHelp` wire field.
     */
    settingsAppearancePublicHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.appearance.publicName` wire field.
     */
    settingsAppearancePublicName?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.action` wire field.
     */
    settingsBouncesAction?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.blocklist` wire field.
     */
    settingsBouncesBlocklist?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.count` wire field.
     */
    settingsBouncesCount?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.countHelp` wire field.
     */
    settingsBouncesCountHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.delete` wire field.
     */
    settingsBouncesDelete?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enable` wire field.
     */
    settingsBouncesEnable?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enableMailbox` wire field.
     */
    settingsBouncesEnableMailbox?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enableSES` wire field.
     */
    settingsBouncesEnableSes?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enableAzure` wire field.
     */
    settingsBouncesEnableAzure?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enableSendgrid` wire field.
     */
    settingsBouncesEnableSendgrid?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enableForwardemail` wire field.
     */
    settingsBouncesEnableForwardemail?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enablePostmark` wire field.
     */
    settingsBouncesEnablePostmark?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enableWebhooks` wire field.
     */
    settingsBouncesEnableWebhooks?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.enabled` wire field.
     */
    settingsBouncesEnabled?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.folder` wire field.
     */
    settingsBouncesFolder?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.folderHelp` wire field.
     */
    settingsBouncesFolderHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.invalidScanInterval` wire field.
     */
    settingsBouncesInvalidScanInterval?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.azureSharedSecret` wire field.
     */
    settingsBouncesAzureSharedSecret?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.azureSharedSecretHelp` wire field.
     */
    settingsBouncesAzureSharedSecretHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.azureSharedSecretHeader` wire field.
     */
    settingsBouncesAzureSharedSecretHeader?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.azureSharedSecretHeaderHelp` wire field.
     */
    settingsBouncesAzureSharedSecretHeaderHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.name` wire field.
     */
    settingsBouncesName?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.scanInterval` wire field.
     */
    settingsBouncesScanInterval?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.scanIntervalHelp` wire field.
     */
    settingsBouncesScanIntervalHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.sendgridKey` wire field.
     */
    settingsBouncesSendgridKey?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.forwardemailKey` wire field.
     */
    settingsBouncesForwardemailKey?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.postmarkUsername` wire field.
     */
    settingsBouncesPostmarkUsername?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.postmarkUsernameHelp` wire field.
     */
    settingsBouncesPostmarkUsernameHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.postmarkPassword` wire field.
     */
    settingsBouncesPostmarkPassword?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.type` wire field.
     */
    settingsBouncesType?: string;
    /**
     * Optional `string` value serialized in the `settings.bounces.username` wire field.
     */
    settingsBouncesUsername?: string;
    /**
     * Optional `string` value serialized in the `settings.confirmRestart` wire field.
     */
    settingsConfirmRestart?: string;
    /**
     * Optional `string` value serialized in the `settings.duplicateMessengerName` wire field.
     */
    settingsDuplicateMessengerName?: string;
    /**
     * Optional `string` value serialized in the `settings.errorEncoding` wire field.
     */
    settingsErrorEncoding?: string;
    /**
     * Optional `string` value serialized in the `settings.errorNoSMTP` wire field.
     */
    settingsErrorNoSmtp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.adminNotifEmails` wire field.
     */
    settingsGeneralAdminNotifEmails?: string;
    /**
     * Optional `string` value serialized in the `settings.general.adminNotifEmailsHelp` wire field.
     */
    settingsGeneralAdminNotifEmailsHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.checkUpdates` wire field.
     */
    settingsGeneralCheckUpdates?: string;
    /**
     * Optional `string` value serialized in the `settings.general.checkUpdatesHelp` wire field.
     */
    settingsGeneralCheckUpdatesHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.enablePublicArchive` wire field.
     */
    settingsGeneralEnablePublicArchive?: string;
    /**
     * Optional `string` value serialized in the `settings.general.enablePublicArchiveHelp` wire field.
     */
    settingsGeneralEnablePublicArchiveHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.enablePublicSubPage` wire field.
     */
    settingsGeneralEnablePublicSubPage?: string;
    /**
     * Optional `string` value serialized in the `settings.general.enablePublicSubPageHelp` wire field.
     */
    settingsGeneralEnablePublicSubPageHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.faviconURL` wire field.
     */
    settingsGeneralFaviconUrl?: string;
    /**
     * Optional `string` value serialized in the `settings.general.faviconURLHelp` wire field.
     */
    settingsGeneralFaviconUrlHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.fromEmail` wire field.
     */
    settingsGeneralFromEmail?: string;
    /**
     * Optional `string` value serialized in the `settings.general.fromEmailHelp` wire field.
     */
    settingsGeneralFromEmailHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.language` wire field.
     */
    settingsGeneralLanguage?: string;
    /**
     * Optional `string` value serialized in the `settings.general.logoURL` wire field.
     */
    settingsGeneralLogoUrl?: string;
    /**
     * Optional `string` value serialized in the `settings.general.logoURLHelp` wire field.
     */
    settingsGeneralLogoUrlHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.name` wire field.
     */
    settingsGeneralName?: string;
    /**
     * Optional `string` value serialized in the `settings.general.rootURL` wire field.
     */
    settingsGeneralRootUrl?: string;
    /**
     * Optional `string` value serialized in the `settings.general.rootURLHelp` wire field.
     */
    settingsGeneralRootUrlHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.sendOptinConfirm` wire field.
     */
    settingsGeneralSendOptinConfirm?: string;
    /**
     * Optional `string` value serialized in the `settings.general.sendOptinConfirmHelp` wire field.
     */
    settingsGeneralSendOptinConfirmHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.general.siteName` wire field.
     */
    settingsGeneralSiteName?: string;
    /**
     * Optional `string` value serialized in the `settings.invalidMessengerName` wire field.
     */
    settingsInvalidMessengerName?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.authProtocol` wire field.
     */
    settingsMailserverAuthProtocol?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.name` wire field.
     */
    settingsMailserverName?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.nameHelp` wire field.
     */
    settingsMailserverNameHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.host` wire field.
     */
    settingsMailserverHost?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.hostHelp` wire field.
     */
    settingsMailserverHostHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.idleTimeout` wire field.
     */
    settingsMailserverIdleTimeout?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.idleTimeoutHelp` wire field.
     */
    settingsMailserverIdleTimeoutHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.maxConns` wire field.
     */
    settingsMailserverMaxConns?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.maxConnsHelp` wire field.
     */
    settingsMailserverMaxConnsHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.password` wire field.
     */
    settingsMailserverPassword?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.passwordHelp` wire field.
     */
    settingsMailserverPasswordHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.port` wire field.
     */
    settingsMailserverPort?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.portHelp` wire field.
     */
    settingsMailserverPortHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.skipTLS` wire field.
     */
    settingsMailserverSkipTls?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.skipTLSHelp` wire field.
     */
    settingsMailserverSkipTlsHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.tls` wire field.
     */
    settingsMailserverTls?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.tlsHelp` wire field.
     */
    settingsMailserverTlsHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.username` wire field.
     */
    settingsMailserverUsername?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.waitTimeout` wire field.
     */
    settingsMailserverWaitTimeout?: string;
    /**
     * Optional `string` value serialized in the `settings.mailserver.waitTimeoutHelp` wire field.
     */
    settingsMailserverWaitTimeoutHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.media.provider` wire field.
     */
    settingsMediaProvider?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.bucket` wire field.
     */
    settingsMediaS3Bucket?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.bucketPath` wire field.
     */
    settingsMediaS3BucketPath?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.bucketPathHelp` wire field.
     */
    settingsMediaS3BucketPathHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.bucketType` wire field.
     */
    settingsMediaS3BucketType?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.bucketTypePrivate` wire field.
     */
    settingsMediaS3BucketTypePrivate?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.bucketTypePublic` wire field.
     */
    settingsMediaS3BucketTypePublic?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.key` wire field.
     */
    settingsMediaS3Key?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.publicURL` wire field.
     */
    settingsMediaS3PublicUrl?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.publicURLHelp` wire field.
     */
    settingsMediaS3PublicUrlHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.region` wire field.
     */
    settingsMediaS3Region?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.secret` wire field.
     */
    settingsMediaS3Secret?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.uploadExpiry` wire field.
     */
    settingsMediaS3UploadExpiry?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.uploadExpiryHelp` wire field.
     */
    settingsMediaS3UploadExpiryHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.url` wire field.
     */
    settingsMediaS3Url?: string;
    /**
     * Optional `string` value serialized in the `settings.media.s3.urlHelp` wire field.
     */
    settingsMediaS3UrlHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.media.title` wire field.
     */
    settingsMediaTitle?: string;
    /**
     * Optional `string` value serialized in the `settings.media.upload.path` wire field.
     */
    settingsMediaUploadPath?: string;
    /**
     * Optional `string` value serialized in the `settings.media.upload.pathHelp` wire field.
     */
    settingsMediaUploadPathHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.media.upload.uri` wire field.
     */
    settingsMediaUploadUri?: string;
    /**
     * Optional `string` value serialized in the `settings.media.upload.uriHelp` wire field.
     */
    settingsMediaUploadUriHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.maxConns` wire field.
     */
    settingsMessengersMaxConns?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.maxConnsHelp` wire field.
     */
    settingsMessengersMaxConnsHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.messageSaved` wire field.
     */
    settingsMessengersMessageSaved?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.name` wire field.
     */
    settingsMessengersName?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.nameHelp` wire field.
     */
    settingsMessengersNameHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.password` wire field.
     */
    settingsMessengersPassword?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.retries` wire field.
     */
    settingsMessengersRetries?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.retriesHelp` wire field.
     */
    settingsMessengersRetriesHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.skipTLSHelp` wire field.
     */
    settingsMessengersSkipTlsHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.timeout` wire field.
     */
    settingsMessengersTimeout?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.timeoutHelp` wire field.
     */
    settingsMessengersTimeoutHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.url` wire field.
     */
    settingsMessengersUrl?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.urlHelp` wire field.
     */
    settingsMessengersUrlHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.messengers.username` wire field.
     */
    settingsMessengersUsername?: string;
    /**
     * Optional `string` value serialized in the `settings.needsRestart` wire field.
     */
    settingsNeedsRestart?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.batchSize` wire field.
     */
    settingsPerformanceBatchSize?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.batchSizeHelp` wire field.
     */
    settingsPerformanceBatchSizeHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.concurrency` wire field.
     */
    settingsPerformanceConcurrency?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.concurrencyHelp` wire field.
     */
    settingsPerformanceConcurrencyHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.maxErrThreshold` wire field.
     */
    settingsPerformanceMaxErrThreshold?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.maxErrThresholdHelp` wire field.
     */
    settingsPerformanceMaxErrThresholdHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.messageRate` wire field.
     */
    settingsPerformanceMessageRate?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.messageRateHelp` wire field.
     */
    settingsPerformanceMessageRateHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.name` wire field.
     */
    settingsPerformanceName?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.slidingWindow` wire field.
     */
    settingsPerformanceSlidingWindow?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.slidingWindowDuration` wire field.
     */
    settingsPerformanceSlidingWindowDuration?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.slidingWindowDurationHelp` wire field.
     */
    settingsPerformanceSlidingWindowDurationHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.slidingWindowHelp` wire field.
     */
    settingsPerformanceSlidingWindowHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.slidingWindowRate` wire field.
     */
    settingsPerformanceSlidingWindowRate?: string;
    /**
     * Optional `string` value serialized in the `settings.performance.slidingWindowRateHelp` wire field.
     */
    settingsPerformanceSlidingWindowRateHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowBlocklist` wire field.
     */
    settingsPrivacyAllowBlocklist?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowBlocklistHelp` wire field.
     */
    settingsPrivacyAllowBlocklistHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowExport` wire field.
     */
    settingsPrivacyAllowExport?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowExportHelp` wire field.
     */
    settingsPrivacyAllowExportHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowPrefs` wire field.
     */
    settingsPrivacyAllowPrefs?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowPrefsHelp` wire field.
     */
    settingsPrivacyAllowPrefsHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowWipe` wire field.
     */
    settingsPrivacyAllowWipe?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.allowWipeHelp` wire field.
     */
    settingsPrivacyAllowWipeHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.domainBlocklist` wire field.
     */
    settingsPrivacyDomainBlocklist?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.domainBlocklistHelp` wire field.
     */
    settingsPrivacyDomainBlocklistHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.individualSubTracking` wire field.
     */
    settingsPrivacyIndividualSubTracking?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.individualSubTrackingHelp` wire field.
     */
    settingsPrivacyIndividualSubTrackingHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.listUnsubHeader` wire field.
     */
    settingsPrivacyListUnsubHeader?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.listUnsubHeaderHelp` wire field.
     */
    settingsPrivacyListUnsubHeaderHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.privacy.name` wire field.
     */
    settingsPrivacyName?: string;
    /**
     * Optional `string` value serialized in the `settings.restart` wire field.
     */
    settingsRestart?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.customHeaders` wire field.
     */
    settingsSmtpCustomHeaders?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.customHeadersHelp` wire field.
     */
    settingsSmtpCustomHeadersHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.enabled` wire field.
     */
    settingsSmtpEnabled?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.heloHost` wire field.
     */
    settingsSmtpHeloHost?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.heloHostHelp` wire field.
     */
    settingsSmtpHeloHostHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.name` wire field.
     */
    settingsSmtpName?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.retries` wire field.
     */
    settingsSmtpRetries?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.retriesHelp` wire field.
     */
    settingsSmtpRetriesHelp?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.sendTest` wire field.
     */
    settingsSmtpSendTest?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.setCustomHeaders` wire field.
     */
    settingsSmtpSetCustomHeaders?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.testConnection` wire field.
     */
    settingsSmtpTestConnection?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.testEnterEmail` wire field.
     */
    settingsSmtpTestEnterEmail?: string;
    /**
     * Optional `string` value serialized in the `settings.smtp.toEmail` wire field.
     */
    settingsSmtpToEmail?: string;
    /**
     * Optional `string` value serialized in the `settings.title` wire field.
     */
    settingsTitle?: string;
    /**
     * Optional `string` value serialized in the `settings.updateAvailable` wire field.
     */
    settingsUpdateAvailable?: string;
    /**
     * Optional `string` value serialized in the `subscribers.advancedQuery` wire field.
     */
    subscribersAdvancedQuery?: string;
    /**
     * Optional `string` value serialized in the `subscribers.advancedQueryHelp` wire field.
     */
    subscribersAdvancedQueryHelp?: string;
    /**
     * Optional `string` value serialized in the `subscribers.attribs` wire field.
     */
    subscribersAttribs?: string;
    /**
     * Optional `string` value serialized in the `subscribers.attribsHelp` wire field.
     */
    subscribersAttribsHelp?: string;
    /**
     * Optional `string` value serialized in the `subscribers.blocklistedHelp` wire field.
     */
    subscribersBlocklistedHelp?: string;
    /**
     * Optional `string` value serialized in the `subscribers.confirmBlocklist` wire field.
     */
    subscribersConfirmBlocklist?: string;
    /**
     * Optional `string` value serialized in the `subscribers.confirmDelete` wire field.
     */
    subscribersConfirmDelete?: string;
    /**
     * Optional `string` value serialized in the `subscribers.confirmExport` wire field.
     */
    subscribersConfirmExport?: string;
    /**
     * Optional `string` value serialized in the `subscribers.domainBlocklisted` wire field.
     */
    subscribersDomainBlocklisted?: string;
    /**
     * Optional `string` value serialized in the `subscribers.downloadData` wire field.
     */
    subscribersDownloadData?: string;
    /**
     * Optional `string` value serialized in the `subscribers.email` wire field.
     */
    subscribersEmail?: string;
    /**
     * Optional `string` value serialized in the `subscribers.emailExists` wire field.
     */
    subscribersEmailExists?: string;
    /**
     * Optional `string` value serialized in the `subscribers.errorBlocklisting` wire field.
     */
    subscribersErrorBlocklisting?: string;
    /**
     * Optional `string` value serialized in the `subscribers.errorNoIDs` wire field.
     */
    subscribersErrorNoIds?: string;
    /**
     * Optional `string` value serialized in the `subscribers.errorNoListsGiven` wire field.
     */
    subscribersErrorNoListsGiven?: string;
    /**
     * Optional `string` value serialized in the `subscribers.errorPreparingQuery` wire field.
     */
    subscribersErrorPreparingQuery?: string;
    /**
     * Optional `string` value serialized in the `subscribers.errorSendingOptin` wire field.
     */
    subscribersErrorSendingOptin?: string;
    /**
     * Optional `string` value serialized in the `subscribers.export` wire field.
     */
    subscribersExport?: string;
    /**
     * Optional `string` value serialized in the `subscribers.invalidAction` wire field.
     */
    subscribersInvalidAction?: string;
    /**
     * Optional `string` value serialized in the `subscribers.invalidEmail` wire field.
     */
    subscribersInvalidEmail?: string;
    /**
     * Optional `string` value serialized in the `subscribers.invalidJSON` wire field.
     */
    subscribersInvalidJson?: string;
    /**
     * Optional `string` value serialized in the `subscribers.invalidName` wire field.
     */
    subscribersInvalidName?: string;
    /**
     * Optional `string` value serialized in the `subscribers.listChangeApplied` wire field.
     */
    subscribersListChangeApplied?: string;
    /**
     * Optional `string` value serialized in the `subscribers.lists` wire field.
     */
    subscribersLists?: string;
    /**
     * Optional `string` value serialized in the `subscribers.listsHelp` wire field.
     */
    subscribersListsHelp?: string;
    /**
     * Optional `string` value serialized in the `subscribers.listsPlaceholder` wire field.
     */
    subscribersListsPlaceholder?: string;
    /**
     * Optional `string` value serialized in the `subscribers.manageLists` wire field.
     */
    subscribersManageLists?: string;
    /**
     * Optional `string` value serialized in the `subscribers.markUnsubscribed` wire field.
     */
    subscribersMarkUnsubscribed?: string;
    /**
     * Optional `string` value serialized in the `subscribers.newSubscriber` wire field.
     */
    subscribersNewSubscriber?: string;
    /**
     * Optional `string` value serialized in the `subscribers.numSelected` wire field.
     */
    subscribersNumSelected?: string;
    /**
     * Optional `string` value serialized in the `subscribers.optinSubject` wire field.
     */
    subscribersOptinSubject?: string;
    /**
     * Optional `string` value serialized in the `subscribers.preconfirm` wire field.
     */
    subscribersPreconfirm?: string;
    /**
     * Optional `string` value serialized in the `subscribers.preconfirmHelp` wire field.
     */
    subscribersPreconfirmHelp?: string;
    /**
     * Optional `string` value serialized in the `subscribers.query` wire field.
     */
    subscribersQuery?: string;
    /**
     * Optional `string` value serialized in the `subscribers.queryPlaceholder` wire field.
     */
    subscribersQueryPlaceholder?: string;
    /**
     * Optional `string` value serialized in the `subscribers.reset` wire field.
     */
    subscribersReset?: string;
    /**
     * Optional `string` value serialized in the `subscribers.selectAll` wire field.
     */
    subscribersSelectAll?: string;
    /**
     * Optional `string` value serialized in the `subscribers.sendOptinConfirm` wire field.
     */
    subscribersSendOptinConfirm?: string;
    /**
     * Optional `string` value serialized in the `subscribers.sentOptinConfirm` wire field.
     */
    subscribersSentOptinConfirm?: string;
    /**
     * Optional `string` value serialized in the `subscribers.status.blocklisted` wire field.
     */
    subscribersStatusBlocklisted?: string;
    /**
     * Optional `string` value serialized in the `subscribers.status.confirmed` wire field.
     */
    subscribersStatusConfirmed?: string;
    /**
     * Optional `string` value serialized in the `subscribers.status.enabled` wire field.
     */
    subscribersStatusEnabled?: string;
    /**
     * Optional `string` value serialized in the `subscribers.status.subscribed` wire field.
     */
    subscribersStatusSubscribed?: string;
    /**
     * Optional `string` value serialized in the `subscribers.status.unconfirmed` wire field.
     */
    subscribersStatusUnconfirmed?: string;
    /**
     * Optional `string` value serialized in the `subscribers.status.unsubscribed` wire field.
     */
    subscribersStatusUnsubscribed?: string;
    /**
     * Optional `string` value serialized in the `subscribers.subscribersDeleted` wire field.
     */
    subscribersSubscribersDeleted?: string;
    /**
     * Optional `string` value serialized in the `templates.cantDeleteDefault` wire field.
     */
    templatesCantDeleteDefault?: string;
    /**
     * Optional `string` value serialized in the `templates.default` wire field.
     */
    templatesDefault?: string;
    /**
     * Optional `string` value serialized in the `templates.dummyName` wire field.
     */
    templatesDummyName?: string;
    /**
     * Optional `string` value serialized in the `templates.dummySubject` wire field.
     */
    templatesDummySubject?: string;
    /**
     * Optional `string` value serialized in the `templates.errorCompiling` wire field.
     */
    templatesErrorCompiling?: string;
    /**
     * Optional `string` value serialized in the `templates.errorRendering` wire field.
     */
    templatesErrorRendering?: string;
    /**
     * Optional `string` value serialized in the `templates.fieldInvalidName` wire field.
     */
    templatesFieldInvalidName?: string;
    /**
     * Optional `string` value serialized in the `templates.makeDefault` wire field.
     */
    templatesMakeDefault?: string;
    /**
     * Optional `string` value serialized in the `templates.newTemplate` wire field.
     */
    templatesNewTemplate?: string;
    /**
     * Optional `string` value serialized in the `templates.placeholderHelp` wire field.
     */
    templatesPlaceholderHelp?: string;
    /**
     * Optional `string` value serialized in the `templates.preview` wire field.
     */
    templatesPreview?: string;
    /**
     * Optional `string` value serialized in the `templates.rawHTML` wire field.
     */
    templatesRawHtml?: string;
    /**
     * Optional `string` value serialized in the `templates.subject` wire field.
     */
    templatesSubject?: string;
    /**
     * Optional `string` value serialized in the `users.login` wire field.
     */
    usersLogin?: string;
    /**
     * Optional `string` value serialized in the `users.logout` wire field.
     */
    usersLogout?: string;
  };
}
