// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `DashboardChart` API schema.
 */
export interface DashboardChart {
  /**
   * Optional array value serialized in the `link_clicks` wire field.
   */
  linkClicks?: {
    /**
     * Optional `integer` value serialized in the `count` wire field.
     */
    count?: number;
    /**
     * Optional `string` value serialized in the `date` wire field.
     */
    date?: string;
  }[];
  /**
   * Optional array value serialized in the `campaign_views` wire field.
   */
  campaignViews?: {
    /**
     * Optional `integer` value serialized in the `count` wire field.
     */
    count?: number;
    /**
     * Optional `string` value serialized in the `date` wire field.
     */
    date?: string;
  }[];
}

/**
 * Typed representation of the `DashboardCount` API schema.
 */
export interface DashboardCount {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: {
    /**
     * Optional object value serialized in the `subscribers` wire field.
     */
    subscribers?: {
      /**
       * Optional `integer` value serialized in the `total` wire field.
       */
      total?: number;
      /**
       * Optional object value serialized in the `blocklisted` wire field.
       */
      blocklisted?: { [key: string]: unknown };
      /**
       * Optional `integer` value serialized in the `orphans` wire field.
       */
      orphans?: number;
    };
    /**
     * Optional object value serialized in the `lists` wire field.
     */
    lists?: {
      /**
       * Optional `integer` value serialized in the `total` wire field.
       */
      total?: number;
      /**
       * Optional `integer` value serialized in the `private` wire field.
       */
      private?: number;
      /**
       * Optional `integer` value serialized in the `public` wire field.
       */
      public?: number;
      /**
       * Optional `integer` value serialized in the `optin_single` wire field.
       */
      optinSingle?: number;
      /**
       * Optional `integer` value serialized in the `optin_double` wire field.
       */
      optinDouble?: number;
    };
    /**
     * Optional object value serialized in the `campaigns` wire field.
     */
    campaigns?: {
      /**
       * Optional `integer` value serialized in the `total` wire field.
       */
      total?: number;
      /**
       * Optional object value serialized in the `by_status` wire field.
       */
      byStatus?: {
        /**
         * Optional `integer` value serialized in the `draft` wire field.
         */
        draft?: number;
      };
    };
    /**
     * Optional `integer` value serialized in the `messages` wire field.
     */
    messages?: number;
  };
}
