// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `MailBoxBounces` API schema.
 */
export interface MailBoxBounces {
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional `boolean` value serialized in the `enabled` wire field.
   */
  enabled?: boolean;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional `string` value serialized in the `host` wire field.
   */
  host?: string;
  /**
   * Optional `integer` value serialized in the `port` wire field.
   */
  port?: number;
  /**
   * Optional `string` value serialized in the `auth_protocol` wire field.
   */
  authProtocol?: string;
  /**
   * Optional `string` value serialized in the `return_path` wire field.
   */
  returnPath?: string;
  /**
   * Optional `string` value serialized in the `username` wire field.
   */
  username?: string;
  /**
   * Optional `boolean` value serialized in the `tls_enabled` wire field.
   */
  tlsEnabled?: boolean;
  /**
   * Optional `boolean` value serialized in the `tls_skip_verify` wire field.
   */
  tlsSkipVerify?: boolean;
  /**
   * Optional `string` value serialized in the `scan_interval` wire field.
   */
  scanInterval?: string;
}

/**
 * Typed representation of the `Settings` API schema.
 */
export interface Settings {
  /**
   * Optional `string` value serialized in the `app.site_name` wire field.
   */
  appSiteName?: string;
  /**
   * Optional `string` value serialized in the `app.root_url` wire field.
   */
  appRootUrl?: string;
  /**
   * Optional `string` value serialized in the `app.logo_url` wire field.
   */
  appLogoUrl?: string;
  /**
   * Optional `string` value serialized in the `app.favicon_url` wire field.
   */
  appFaviconUrl?: string;
  /**
   * Optional `string` value serialized in the `app.from_email` wire field.
   */
  appFromEmail?: string;
  /**
   * Optional array value serialized in the `app.notify_emails` wire field.
   */
  appNotifyEmails?: string[];
  /**
   * Optional `boolean` value serialized in the `app.enable_public_subscription_page` wire field.
   */
  appEnablePublicSubscriptionPage?: boolean;
  /**
   * Optional `boolean` value serialized in the `app.enable_public_archive` wire field.
   */
  appEnablePublicArchive?: boolean;
  /**
   * Optional `boolean` value serialized in the `app.send_optin_confirmation` wire field.
   */
  appSendOptinConfirmation?: boolean;
  /**
   * Optional `boolean` value serialized in the `app.check_updates` wire field.
   */
  appCheckUpdates?: boolean;
  /**
   * Optional `string` value serialized in the `app.lang` wire field.
   */
  appLang?: string;
  /**
   * Optional `integer` value serialized in the `app.batch_size` wire field.
   */
  appBatchSize?: number;
  /**
   * Optional `integer` value serialized in the `app.concurrency` wire field.
   */
  appConcurrency?: number;
  /**
   * Optional `integer` value serialized in the `app.max_send_errors` wire field.
   */
  appMaxSendErrors?: number;
  /**
   * Optional `integer` value serialized in the `app.message_rate` wire field.
   */
  appMessageRate?: number;
  /**
   * Optional `boolean` value serialized in the `app.message_sliding_window` wire field.
   */
  appMessageSlidingWindow?: boolean;
  /**
   * Optional `string` value serialized in the `app.message_sliding_window_duration` wire field.
   */
  appMessageSlidingWindowDuration?: string;
  /**
   * Optional `integer` value serialized in the `app.message_sliding_window_rate` wire field.
   */
  appMessageSlidingWindowRate?: number;
  /**
   * Optional `boolean` value serialized in the `privacy.individual_tracking` wire field.
   */
  privacyIndividualTracking?: boolean;
  /**
   * Optional `boolean` value serialized in the `privacy.unsubscribe_header` wire field.
   */
  privacyUnsubscribeHeader?: boolean;
  /**
   * Optional `boolean` value serialized in the `privacy.allow_blocklist` wire field.
   */
  privacyAllowBlocklist?: boolean;
  /**
   * Optional `boolean` value serialized in the `privacy.allow_preferences` wire field.
   */
  privacyAllowPreferences?: boolean;
  /**
   * Optional `boolean` value serialized in the `privacy.allow_export` wire field.
   */
  privacyAllowExport?: boolean;
  /**
   * Optional `boolean` value serialized in the `privacy.allow_wipe` wire field.
   */
  privacyAllowWipe?: boolean;
  /**
   * Optional array value serialized in the `privacy.exportable` wire field.
   */
  privacyExportable?: string[];
  /**
   * Optional array value serialized in the `privacy.domain_blocklist` wire field.
   */
  privacyDomainBlocklist?: { [key: string]: unknown }[];
  /**
   * Optional `string` value serialized in the `upload.provider` wire field.
   */
  uploadProvider?: string;
  /**
   * Optional `string` value serialized in the `upload.filesystem.upload_path` wire field.
   */
  uploadFilesystemUploadPath?: string;
  /**
   * Optional `string` value serialized in the `upload.filesystem.upload_uri` wire field.
   */
  uploadFilesystemUploadUri?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.url` wire field.
   */
  uploadS3Url?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.public_url` wire field.
   */
  uploadS3PublicUrl?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.aws_access_key_id` wire field.
   */
  uploadS3AwsAccessKeyId?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.aws_default_region` wire field.
   */
  uploadS3AwsDefaultRegion?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.bucket` wire field.
   */
  uploadS3Bucket?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.bucket_domain` wire field.
   */
  uploadS3BucketDomain?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.bucket_path` wire field.
   */
  uploadS3BucketPath?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.bucket_type` wire field.
   */
  uploadS3BucketType?: string;
  /**
   * Optional `string` value serialized in the `upload.s3.expiry` wire field.
   */
  uploadS3Expiry?: string;
  /**
   * Optional array value serialized in the `smtp` wire field.
   */
  smtp?: SMTPSettings[];
  /**
   * Optional array value serialized in the `messengers` wire field.
   */
  messengers?: { [key: string]: unknown }[];
  /**
   * Optional `boolean` value serialized in the `bounce.enabled` wire field.
   */
  bounceEnabled?: boolean;
  /**
   * Optional `boolean` value serialized in the `bounce.webhooks_enabled` wire field.
   */
  bounceWebhooksEnabled?: boolean;
  /**
   * Optional `integer` value serialized in the `bounce.count` wire field.
   */
  bounceCount?: number;
  /**
   * Optional `string` value serialized in the `bounce.action` wire field.
   */
  bounceAction?: string;
  /**
   * Optional `boolean` value serialized in the `bounce.ses_enabled` wire field.
   */
  bounceSesEnabled?: boolean;
  /**
   * Optional `boolean` value serialized in the `bounce.azure.enabled` wire field.
   */
  bounceAzureEnabled?: boolean;
  /**
   * Optional `string` value serialized in the `bounce.azure.shared_secret` wire field.
   */
  bounceAzureSharedSecret?: string;
  /**
   * Optional `string` value serialized in the `bounce.azure.shared_secret_header` wire field.
   */
  bounceAzureSharedSecretHeader?: string;
  /**
   * Optional `boolean` value serialized in the `bounce.sendgrid_enabled` wire field.
   */
  bounceSendgridEnabled?: boolean;
  /**
   * Optional `string` value serialized in the `bounce.sendgrid_key` wire field.
   */
  bounceSendgridKey?: string;
  /**
   * Optional `boolean` value serialized in the `bounce.forwardemail_enabled` wire field.
   */
  bounceForwardemailEnabled?: boolean;
  /**
   * Optional `string` value serialized in the `bounce.forwardemail_key` wire field.
   */
  bounceForwardemailKey?: string;
  /**
   * Optional `boolean` value serialized in the `bounce.postmark_enabled` wire field.
   */
  bouncePostmarkEnabled?: boolean;
  /**
   * Optional `string` value serialized in the `bounce.postmark_username` wire field.
   */
  bouncePostmarkUsername?: string;
  /**
   * Optional `string` value serialized in the `bounce.postmark_password` wire field.
   */
  bouncePostmarkPassword?: string;
  /**
   * Optional array value serialized in the `bounce.mailboxes` wire field.
   */
  bounceMailboxes?: MailBoxBounces[];
  /**
   * Optional `string` value serialized in the `appearance.admin.custom_css` wire field.
   */
  appearanceAdminCustomCss?: string;
  /**
   * Optional `string` value serialized in the `appearance.admin.custom_js` wire field.
   */
  appearanceAdminCustomJs?: string;
  /**
   * Optional `string` value serialized in the `appearance.public.custom_css` wire field.
   */
  appearancePublicCustomCss?: string;
  /**
   * Optional `string` value serialized in the `appearance.public.custom_js` wire field.
   */
  appearancePublicCustomJs?: string;
}

/**
 * Typed representation of the `SMTPSettings` API schema.
 */
export interface SMTPSettings {
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional `boolean` value serialized in the `enabled` wire field.
   */
  enabled?: boolean;
  /**
   * Optional `string` value serialized in the `host` wire field.
   */
  host?: string;
  /**
   * Optional `string` value serialized in the `hello_hostname` wire field.
   */
  helloHostname?: string;
  /**
   * Optional `integer` value serialized in the `port` wire field.
   */
  port?: number;
  /**
   * Optional `string` value serialized in the `auth_protocol` wire field.
   */
  authProtocol?: string;
  /**
   * Optional `string` value serialized in the `username` wire field.
   */
  username?: string;
  /**
   * Optional array value serialized in the `email_headers` wire field.
   */
  emailHeaders?: { [key: string]: unknown }[];
  /**
   * Optional `integer` value serialized in the `max_conns` wire field.
   */
  maxConns?: number;
  /**
   * Optional `integer` value serialized in the `max_msg_retries` wire field.
   */
  maxMsgRetries?: number;
  /**
   * Optional `string` value serialized in the `idle_timeout` wire field.
   */
  idleTimeout?: string;
  /**
   * Optional `string` value serialized in the `wait_timeout` wire field.
   */
  waitTimeout?: string;
  /**
   * Optional `string` value serialized in the `tls_type` wire field.
   */
  tlsType?: string;
  /**
   * Optional `boolean` value serialized in the `tls_skip_verify` wire field.
   */
  tlsSkipVerify?: boolean;
}

/**
 * Typed representation of the `SMTPTest` API schema.
 */
export interface SMTPTest {
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional `boolean` value serialized in the `enabled` wire field.
   */
  enabled?: boolean;
  /**
   * Optional `string` value serialized in the `host` wire field.
   */
  host?: string;
  /**
   * Optional `string` value serialized in the `hello_hostname` wire field.
   */
  helloHostname?: string;
  /**
   * Optional `integer` value serialized in the `port` wire field.
   */
  port?: number;
  /**
   * Optional `string` value serialized in the `auth_protocol` wire field.
   */
  authProtocol?: string;
  /**
   * Optional `string` value serialized in the `username` wire field.
   */
  username?: string;
  /**
   * Optional array value serialized in the `email_headers` wire field.
   */
  emailHeaders?: { [key: string]: unknown }[];
  /**
   * Optional `integer` value serialized in the `max_conns` wire field.
   */
  maxConns?: number;
  /**
   * Optional `integer` value serialized in the `max_msg_retries` wire field.
   */
  maxMsgRetries?: number;
  /**
   * Optional `string` value serialized in the `idle_timeout` wire field.
   */
  idleTimeout?: string;
  /**
   * Optional `string` value serialized in the `wait_timeout` wire field.
   */
  waitTimeout?: string;
  /**
   * Optional `string` value serialized in the `tls_type` wire field.
   */
  tlsType?: string;
  /**
   * Optional `boolean` value serialized in the `tls_skip_verify` wire field.
   */
  tlsSkipVerify?: boolean;
  /**
   * Optional `string` value serialized in the `strEmailHeaders` wire field.
   */
  strEmailHeaders?: string;
  /**
   * Optional `string` value serialized in the `password` wire field.
   */
  password?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
}
