// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `Bounce` API schema.
 */
export interface Bounce {
  /**
   * Optional array value serialized in the `results` wire field.
   */
  results?: {
    /**
     * Optional `integer` value serialized in the `id` wire field.
     */
    id?: number;
    /**
     * Optional `string` value serialized in the `type` wire field.
     */
    type?: string;
    /**
     * Optional `string` value serialized in the `source` wire field.
     */
    source?: string;
    /**
     * Optional object value serialized in the `meta` wire field.
     */
    meta?: { [key: string]: unknown };
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     */
    createdAt?: string;
    /**
     * Optional `string` value serialized in the `email` wire field.
     */
    email?: string;
    /**
     * Optional `string` value serialized in the `subscriber_uuid` wire field.
     */
    subscriberUuid?: string;
    /**
     * Optional `integer` value serialized in the `subscriber_id` wire field.
     */
    subscriberId?: number;
    /**
     * Optional object value serialized in the `campaign` wire field.
     */
    campaign?: {
      /**
       * Optional `integer` value serialized in the `id` wire field.
       */
      id?: number;
      /**
       * Optional `string` value serialized in the `name` wire field.
       */
      name?: string;
    };
    /**
     * Optional `string` value serialized in the `campaign_uuid` wire field.
     */
    campaignUuid?: string;
    /**
     * Optional `integer` value serialized in the `total` wire field.
     */
    total?: number;
  }[];
}
