// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `NewSubscriber` API schema.
 */
export interface NewSubscriber {
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional array value serialized in the `lists` wire field.
   */
  lists?: number[];
  /**
   * Optional array value serialized in the `list_uuids` wire field.
   */
  listUuids?: string[];
  /**
   * Optional `boolean` value serialized in the `preconfirm_subscriptions` wire field.
   */
  preconfirmSubscriptions?: boolean;
  /**
   * Optional object value serialized in the `attribs` wire field.
   */
  attribs?: { [key: string]: unknown };
}

/**
 * Typed representation of the `Subscriber` API schema.
 */
export interface Subscriber {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `updated_at` wire field.
   */
  updatedAt?: string;
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional object value serialized in the `attribs` wire field.
   */
  attribs?: { [key: string]: unknown };
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional array value serialized in the `lists` wire field.
   */
  lists?: {
    /**
     * Optional `string` value serialized in the `subscription_status` wire field.
     */
    subscriptionStatus?: string;
    /**
     * Optional `integer` value serialized in the `id` wire field.
     */
    id?: number;
    /**
     * Optional `string` value serialized in the `uuid` wire field.
     */
    uuid?: string;
    /**
     * Optional `string` value serialized in the `name` wire field.
     */
    name?: string;
    /**
     * Optional `string` value serialized in the `type` wire field.
     */
    type?: string;
    /**
     * Optional array value serialized in the `tags` wire field.
     */
    tags?: string[];
    /**
     * Optional `string` value serialized in the `created_at` wire field.
     */
    createdAt?: string;
    /**
     * Optional `string` value serialized in the `updated_at` wire field.
     */
    updatedAt?: string;
  }[];
}

/**
 * Typed representation of the `SubscriberData` API schema.
 */
export interface SubscriberData {
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional array value serialized in the `profile` wire field.
   */
  profile?: SubscriberProfile[];
  /**
   * Optional array value serialized in the `subscriptions` wire field.
   */
  subscriptions?: Subscriptions[];
  /**
   * Optional array value serialized in the `campaign_views` wire field.
   */
  campaignViews?: { [key: string]: unknown }[];
  /**
   * Optional array value serialized in the `link_clicks` wire field.
   */
  linkClicks?: { [key: string]: unknown }[];
}

/**
 * Typed representation of the `SubscriberProfile` API schema.
 */
export interface SubscriberProfile {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional object value serialized in the `attribs` wire field.
   */
  attribs?: { [key: string]: unknown };
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `updated_at` wire field.
   */
  updatedAt?: string;
}

/**
 * Typed representation of the `SubscriberQueryRequest` API schema.
 */
export interface SubscriberQueryRequest {
  /**
   * Optional `string` value serialized in the `query` wire field.
   */
  query?: string;
  /**
   * The ids of the subscribers to be modified.
   */
  ids?: number[];
  /**
   * Whether to add, remove, or unsubscribe the users.
   */
  action?: "add" | "remove" | "unsubscribe" | (string & {});
  /**
   * The ids of the lists to be modified.
   */
  targetListIds?: number;
  /**
   * confirmed, unconfirmed, or unsubscribed status.
   */
  status?: "confirmed" | "unconfirmed" | "unsubscribed" | (string & {});
}

/**
 * Typed representation of the `Subscriptions` API schema.
 */
export interface Subscriptions {
  /**
   * Optional `string` value serialized in the `subscription_status` wire field.
   */
  subscriptionStatus?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
}

/**
 * Typed representation of the `UpdateSubscriber` API schema.
 */
export interface UpdateSubscriber {
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional array value serialized in the `lists` wire field.
   */
  lists?: number[];
  /**
   * Optional array value serialized in the `list_uuids` wire field.
   */
  listUuids?: string[];
  /**
   * Optional `boolean` value serialized in the `preconfirm_subscriptions` wire field.
   */
  preconfirmSubscriptions?: boolean;
  /**
   * Optional object value serialized in the `attribs` wire field.
   */
  attribs?: { [key: string]: unknown };
}
