// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `NewTemplate` API schema.
 */
export interface NewTemplate {
  /**
   * Name of the template
   */
  name: string;
  /**
   * Type of the template
   */
  type: "campaign" | "campaign_visual" | "tx" | (string & {});
  /**
   * Subject line for the template (only for tx)
   */
  subject?: string;
  /**
   * JSON source for the email-builder template (only for campaign_visual)
   */
  bodySource?: string;
  /**
   * HTML body of the template
   */
  body: string;
}

/**
 * Typed representation of the `Template` API schema.
 */
export interface Template {
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `updated_at` wire field.
   */
  updatedAt?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `body` wire field.
   */
  body?: string;
  /**
   * Optional `string` value serialized in the `body_source` wire field.
   */
  bodySource?: string;
  /**
   * Optional `string` value serialized in the `subject` wire field.
   */
  subject?: string;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional `boolean` value serialized in the `is_default` wire field.
   */
  isDefault?: boolean;
}

/**
 * Typed representation of the `UpdateTemplate` API schema.
 */
export interface UpdateTemplate {
  /**
   * Name of the template
   */
  name?: string;
  /**
   * Type of the template
   */
  type?: "campaign" | "campaign_visual" | "tx" | (string & {});
  /**
   * Subject line for the template (only for tx)
   */
  subject?: string;
  /**
   * JSON source for the email-builder template (only for campaign_visual)
   */
  bodySource?: string;
  /**
   * HTML body of the template
   */
  body?: string;
}
