// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `TransactionalMessage` API schema.
 */
export interface TransactionalMessage {
  /**
   * Optional `string` value serialized in the `subscriber_email` wire field.
   */
  subscriberEmail?: string;
  /**
   * Optional `integer` value serialized in the `subscriber_id` wire field.
   */
  subscriberId?: number;
  /**
   * Optional `integer` value serialized in the `template_id` wire field.
   */
  templateId?: number;
  /**
   * Optional `string` value serialized in the `from_email` wire field.
   */
  fromEmail?: string;
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: { [key: string]: unknown };
  /**
   * Optional array value serialized in the `headers` wire field.
   */
  headers?: { [key: string]: unknown }[];
  /**
   * Optional `string` value serialized in the `messenger` wire field.
   */
  messenger?: string;
  /**
   * Optional `string` value serialized in the `content_type` wire field.
   */
  contentType?: string;
}
