// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import { getSettings, updateSettings, testSmtpSettings } from "../../dist/methods/settings.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getSettings: { route: "getSettings", mediaType: null, invoke: () => getSettings(config, {}) },
  updateSettings: {
    route: "updateSettings",
    mediaType: "application/json",
    invoke: (bag) =>
      updateSettings(config, {
        appSiteName: bag.__body?.["app.site_name"],
        appRootUrl: bag.__body?.["app.root_url"],
        appLogoUrl: bag.__body?.["app.logo_url"],
        appFaviconUrl: bag.__body?.["app.favicon_url"],
        appFromEmail: bag.__body?.["app.from_email"],
        appNotifyEmails: bag.__body?.["app.notify_emails"],
        appEnablePublicSubscriptionPage: bag.__body?.["app.enable_public_subscription_page"],
        appEnablePublicArchive: bag.__body?.["app.enable_public_archive"],
        appSendOptinConfirmation: bag.__body?.["app.send_optin_confirmation"],
        appCheckUpdates: bag.__body?.["app.check_updates"],
        appLang: bag.__body?.["app.lang"],
        appBatchSize: bag.__body?.["app.batch_size"],
        appConcurrency: bag.__body?.["app.concurrency"],
        appMaxSendErrors: bag.__body?.["app.max_send_errors"],
        appMessageRate: bag.__body?.["app.message_rate"],
        appMessageSlidingWindow: bag.__body?.["app.message_sliding_window"],
        appMessageSlidingWindowDuration: bag.__body?.["app.message_sliding_window_duration"],
        appMessageSlidingWindowRate: bag.__body?.["app.message_sliding_window_rate"],
        privacyIndividualTracking: bag.__body?.["privacy.individual_tracking"],
        privacyUnsubscribeHeader: bag.__body?.["privacy.unsubscribe_header"],
        privacyAllowBlocklist: bag.__body?.["privacy.allow_blocklist"],
        privacyAllowPreferences: bag.__body?.["privacy.allow_preferences"],
        privacyAllowExport: bag.__body?.["privacy.allow_export"],
        privacyAllowWipe: bag.__body?.["privacy.allow_wipe"],
        privacyExportable: bag.__body?.["privacy.exportable"],
        privacyDomainBlocklist: bag.__body?.["privacy.domain_blocklist"],
        uploadProvider: bag.__body?.["upload.provider"],
        uploadFilesystemUploadPath: bag.__body?.["upload.filesystem.upload_path"],
        uploadFilesystemUploadUri: bag.__body?.["upload.filesystem.upload_uri"],
        uploadS3Url: bag.__body?.["upload.s3.url"],
        uploadS3PublicUrl: bag.__body?.["upload.s3.public_url"],
        uploadS3AwsAccessKeyId: bag.__body?.["upload.s3.aws_access_key_id"],
        uploadS3AwsDefaultRegion: bag.__body?.["upload.s3.aws_default_region"],
        uploadS3Bucket: bag.__body?.["upload.s3.bucket"],
        uploadS3BucketDomain: bag.__body?.["upload.s3.bucket_domain"],
        uploadS3BucketPath: bag.__body?.["upload.s3.bucket_path"],
        uploadS3BucketType: bag.__body?.["upload.s3.bucket_type"],
        uploadS3Expiry: bag.__body?.["upload.s3.expiry"],
        smtp: bag.__body?.["smtp"],
        messengers: bag.__body?.["messengers"],
        bounceEnabled: bag.__body?.["bounce.enabled"],
        bounceWebhooksEnabled: bag.__body?.["bounce.webhooks_enabled"],
        bounceCount: bag.__body?.["bounce.count"],
        bounceAction: bag.__body?.["bounce.action"],
        bounceSesEnabled: bag.__body?.["bounce.ses_enabled"],
        bounceAzureEnabled: bag.__body?.["bounce.azure.enabled"],
        bounceAzureSharedSecret: bag.__body?.["bounce.azure.shared_secret"],
        bounceAzureSharedSecretHeader: bag.__body?.["bounce.azure.shared_secret_header"],
        bounceSendgridEnabled: bag.__body?.["bounce.sendgrid_enabled"],
        bounceSendgridKey: bag.__body?.["bounce.sendgrid_key"],
        bounceForwardemailEnabled: bag.__body?.["bounce.forwardemail_enabled"],
        bounceForwardemailKey: bag.__body?.["bounce.forwardemail_key"],
        bouncePostmarkEnabled: bag.__body?.["bounce.postmark_enabled"],
        bouncePostmarkUsername: bag.__body?.["bounce.postmark_username"],
        bouncePostmarkPassword: bag.__body?.["bounce.postmark_password"],
        bounceMailboxes: bag.__body?.["bounce.mailboxes"],
        appearanceAdminCustomCss: bag.__body?.["appearance.admin.custom_css"],
        appearanceAdminCustomJs: bag.__body?.["appearance.admin.custom_js"],
        appearancePublicCustomCss: bag.__body?.["appearance.public.custom_css"],
        appearancePublicCustomJs: bag.__body?.["appearance.public.custom_js"],
      }),
  },
  testSmtpSettings: {
    route: "testSMTPSettings",
    mediaType: "application/json",
    invoke: (bag) =>
      testSmtpSettings(config, {
        uuid: bag.__body?.["uuid"],
        enabled: bag.__body?.["enabled"],
        host: bag.__body?.["host"],
        helloHostname: bag.__body?.["hello_hostname"],
        port: bag.__body?.["port"],
        authProtocol: bag.__body?.["auth_protocol"],
        username: bag.__body?.["username"],
        emailHeaders: bag.__body?.["email_headers"],
        maxConns: bag.__body?.["max_conns"],
        maxMsgRetries: bag.__body?.["max_msg_retries"],
        idleTimeout: bag.__body?.["idle_timeout"],
        waitTimeout: bag.__body?.["wait_timeout"],
        tlsType: bag.__body?.["tls_type"],
        tlsSkipVerify: bag.__body?.["tls_skip_verify"],
        strEmailHeaders: bag.__body?.["strEmailHeaders"],
        password: bag.__body?.["password"],
        email: bag.__body?.["email"],
      }),
  },
};

test("settings methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
