// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  NewSubscriber,
  Subscriber,
  SubscriberData,
  SubscriberQueryRequest,
  UpdateSubscriber,
} from "../../types/subscribers";
import { Bounce } from "../../types/shared";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest } from "../../client";

export interface GetSubscribersParams {
  page?: number;
  perPage?: number | "all" | (string & {});
  query?: string;
  orderBy?: "name" | "status" | "created_at" | "updated_at" | (string & {});
  order?: "ASC" | "DESC" | (string & {});
  subscriptionStatus?: string;
  listId?: number[];
}

/**
 * Lists subscribers, with options to filter and sort the results. Use `query` to filter with an SQL expression, `list_id` to filter by lists, and `order_by` and `order` to control sorting. Use `page` and `per_page` to paginate the results.
 *
 * returns all subscribers.
 *
 * @param page - Page number for paginated results.
 * @param perPage - Number of items per page. Use an integer for specific page
 *   size or 'all' to retrieve all results
 * @param query - query subscribers with an SQL expression.
 * @param orderBy - Result sorting field. Options are name, status, created_at,
 *   updated_at
 * @param order - ASC|DESC Sort by ascending or descending order.
 * @param subscriptionStatus - Subscription status to filter by if there are one
 *   or more list_ids.
 * @param listId - ID of lists to filter by. Repeat in the query for multiple
 *   values.
 */
export async function getSubscribers(
  config: ClientConfig,
  { page, perPage, query, orderBy, order, subscriptionStatus, listId }: GetSubscribersParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: {
    results?: Subscriber[];
    query?: string;
    total?: number;
    perPage?: number;
    page?: number;
  };
}> {
  const _resp = await sdkRequest<{
    data?: {
      results?: Subscriber[];
      query?: string;
      total?: number;
      perPage?: number;
      page?: number;
    };
  }>({
    method: "GET",
    path: `/subscribers`,
    operationId: "getSubscribers",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      page: queryValue(page, "form", true),
      per_page: queryValue(perPage, "form", true),
      query: queryValue(query, "form", true),
      order_by: queryValue(orderBy, "form", true),
      order: queryValue(order, "form", true),
      subscription_status: queryValue(subscriptionStatus, "form", true),
      list_id: queryValue(listId, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type CreateSubscriberParams = NewSubscriber;

/**
 * Creates a subscriber from the supplied subscriber details. The request body may be omitted, and no fields are required by the schema; include values such as `email`, `name`, or `lists` to set subscriber data.
 *
 * handles creation of new subscriber
 *
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param status - Optional `string` value serialized in the `status` wire field.
 * @param lists - Optional array value serialized in the `lists` wire field.
 * @param listUuids - Optional array value serialized in the `list_uuids` wire
 *   field.
 * @param preconfirmSubscriptions - Optional `boolean` value serialized in the
 *   `preconfirm_subscriptions` wire field.
 * @param attribs - Optional object value serialized in the `attribs` wire field.
 */
export async function createSubscriber(
  config: ClientConfig,
  {
    email,
    name,
    status,
    lists,
    listUuids,
    preconfirmSubscriptions,
    attribs,
  }: CreateSubscriberParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: Subscriber;
}> {
  const _resp = await sdkRequest<{
    data?: Subscriber;
  }>({
    method: "POST",
    path: `/subscribers`,
    operationId: "createSubscriber",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      email,
      name,
      status,
      lists,
      list_uuids: listUuids,
      preconfirm_subscriptions: preconfirmSubscriptions,
      attribs,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteSubscriberByListParams {
  id: string;
}

/**
 * Deletes one or more subscribers identified by the `id` query parameter. Supply the subscriber ID or IDs as a string, with each ID identifying a subscriber to delete.
 *
 * handles subscribers deletion
 *
 * @param id - subscriber id/s to be deleted
 */
export async function deleteSubscriberByList(
  config: ClientConfig,
  { id }: DeleteSubscriberByListParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/subscribers`,
    operationId: "deleteSubscriberByList",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      id: queryValue(id, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetSubscriberByIdParams {
  id: number;
}

/**
 * Retrieves a subscriber by its identifier. Use the `id` path parameter to select the subscriber whose details you want to view.
 *
 * handles the retrieval of a single subscriber by ID.
 *
 * @param id - The id value of the subscriber you want to get.
 */
export async function getSubscriberById(
  config: ClientConfig,
  { id }: GetSubscriberByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Subscriber;
}> {
  const _resp = await sdkRequest<{
    data?: Subscriber;
  }>({
    method: "GET",
    path: `/subscribers/${encodePathSegment(id)}`,
    operationId: "getSubscriberById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdateSubscriberByIdParams = UpdateSubscriber & {
  id: number;
};

/**
 * Replaces subscriber data for the subscriber identified by the path parameter. The request body may be omitted, and the schema does not require any fields; supply the subscriber properties you want included in the update.
 *
 * modify subscriber data
 *
 * @param id - The id of subscriber to update
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param status - Optional `string` value serialized in the `status` wire field.
 * @param lists - Optional array value serialized in the `lists` wire field.
 * @param listUuids - Optional array value serialized in the `list_uuids` wire
 *   field.
 * @param preconfirmSubscriptions - Optional `boolean` value serialized in the
 *   `preconfirm_subscriptions` wire field.
 * @param attribs - Optional object value serialized in the `attribs` wire field.
 */
export async function updateSubscriberById(
  config: ClientConfig,
  {
    id,
    email,
    name,
    status,
    lists,
    listUuids,
    preconfirmSubscriptions,
    attribs,
  }: UpdateSubscriberByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Subscriber;
}> {
  const _resp = await sdkRequest<{
    data?: Subscriber;
  }>({
    method: "PUT",
    path: `/subscribers/${encodePathSegment(id)}`,
    operationId: "updateSubscriberById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      email,
      name,
      status,
      lists,
      list_uuids: listUuids,
      preconfirm_subscriptions: preconfirmSubscriptions,
      attribs,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteSubscriberByIdParams {
  id: number;
}

/**
 * Deletes a subscriber identified by its path parameter. Use the subscriber's integer `id` to select the record to remove.
 *
 * handles subscriber deletion based on id
 *
 * @param id - The id value of the subscriber you want to get.
 */
export async function deleteSubscriberById(
  config: ClientConfig,
  { id }: DeleteSubscriberByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/subscribers/${encodePathSegment(id)}`,
    operationId: "deleteSubscriberById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type ManageSubscriberListsParams = SubscriberQueryRequest;

/**
 * Manages subscriber membership across lists by adding, removing, or unsubscribing subscribers. Supply `action` and the subscriber or list selectors that define which records to modify; `action` must be `add`, `remove`, or `unsubscribe`.
 *
 * handles bulk addition or removal of subscribers
 *
 * @param query - Optional `string` value serialized in the `query` wire field.
 * @param ids - The ids of the subscribers to be modified.
 * @param action - Whether to add, remove, or unsubscribe the users.
 * @param targetListIds - The ids of the lists to be modified.
 * @param status - confirmed, unconfirmed, or unsubscribed status.
 */
export async function manageSubscriberLists(
  config: ClientConfig,
  { query, ids, action, targetListIds, status }: ManageSubscriberListsParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/lists`,
    operationId: "manageSubscriberLists",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      query,
      ids,
      action,
      target_list_ids: targetListIds,
      status,
    },
    config,
  });
  return _resp.data;
}

export type ManageSubscriberListByIdParams = SubscriberQueryRequest & {
  id: number;
};

/**
 * Manages subscriber membership in a specified list by adding, removing, or unsubscribing subscribers. Use the `id` path parameter to select the list and provide the subscriber selectors and `action` in the request body.
 *
 * handles bulk addition or removal of subscribers for a specified list id
 *
 * @param id - The id of list you want to update
 * @param query - Optional `string` value serialized in the `query` wire field.
 * @param ids - The ids of the subscribers to be modified.
 * @param action - Whether to add, remove, or unsubscribe the users.
 * @param targetListIds - The ids of the lists to be modified.
 * @param status - confirmed, unconfirmed, or unsubscribed status.
 */
export async function manageSubscriberListById(
  config: ClientConfig,
  { id, query, ids, action, targetListIds, status }: ManageSubscriberListByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/lists/${encodePathSegment(id)}`,
    operationId: "manageSubscriberListById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      query,
      ids,
      action,
      target_list_ids: targetListIds,
      status,
    },
    config,
  });
  return _resp.data;
}

export type ManageBlocklistBySubscriberListParams = SubscriberQueryRequest;

/**
 * Manages subscribers on the blocklist using subscriber selectors and list settings. Provide `action` to specify whether to add, remove, or unsubscribe the selected subscribers.
 *
 * handles blocklisting of subscriber list
 *
 * @param query - Optional `string` value serialized in the `query` wire field.
 * @param ids - The ids of the subscribers to be modified.
 * @param action - Whether to add, remove, or unsubscribe the users.
 * @param targetListIds - The ids of the lists to be modified.
 * @param status - confirmed, unconfirmed, or unsubscribed status.
 */
export async function manageBlocklistBySubscriberList(
  config: ClientConfig,
  { query, ids, action, targetListIds, status }: ManageBlocklistBySubscriberListParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/blocklist`,
    operationId: "manageBlocklistBySubscriberList",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      query,
      ids,
      action,
      target_list_ids: targetListIds,
      status,
    },
    config,
  });
  return _resp.data;
}

export type ManageBlocklistSubscribersByIdParams = SubscriberQueryRequest & {
  id: number;
};

/**
 * Manages the blocklist for the subscriber identified by the path parameter. Use the `id` path parameter to select the subscriber and provide the action and any additional selectors in the request body.
 *
 * handles the blocklisting of one or more subscribers.
 *
 * @param id - The id value of the subscriber you want to blocklist.
 * @param query - Optional `string` value serialized in the `query` wire field.
 * @param ids - The ids of the subscribers to be modified.
 * @param action - Whether to add, remove, or unsubscribe the users.
 * @param targetListIds - The ids of the lists to be modified.
 * @param status - confirmed, unconfirmed, or unsubscribed status.
 */
export async function manageBlocklistSubscribersById(
  config: ClientConfig,
  { id, query, ids, action, targetListIds, status }: ManageBlocklistSubscribersByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/${encodePathSegment(id)}/blocklist`,
    operationId: "manageBlocklistSubscribersById",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      query,
      ids,
      action,
      target_list_ids: targetListIds,
      status,
    },
    config,
  });
  return _resp.data;
}

export interface ExportSubscriberDataByIdParams {
  id: number;
}

/**
 * Retrieves a subscriber's profile and related activity data for export. Supply the subscriber's numeric `id` to retrieve profile details, subscriptions, campaign views, and link clicks.
 *
 * retrieves a subscriber's profile
 *
 * @param id - The id value of subscriber profile you want to export
 */
export async function exportSubscriberDataById(
  config: ClientConfig,
  { id }: ExportSubscriberDataByIdParams,
  requestOptions?: RequestOptions,
): Promise<SubscriberData> {
  const _resp = await sdkRequest<SubscriberData>({
    method: "GET",
    path: `/subscribers/${encodePathSegment(id)}/export`,
    operationId: "exportSubscriberDataById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "SubscriberData") as SubscriberData;
}

export interface GetSubscriberBouncesByIdParams {
  id: number;
}

/**
 * Retrieves bounce records associated with a specific subscriber. Supply the subscriber's numeric `id` to look up the records for that subscriber.
 *
 * retrieves a subscriber's bounce records
 *
 * @param id - subscriber id
 */
export async function getSubscriberBouncesById(
  config: ClientConfig,
  { id }: GetSubscriberBouncesByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: Bounce[];
}> {
  const _resp = await sdkRequest<{
    data?: Bounce[];
  }>({
    method: "GET",
    path: `/subscribers/${encodePathSegment(id)}/bounces`,
    operationId: "getSubscriberBouncesById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface DeleteSubscriberBouncesByIdParams {
  id: number;
}

/**
 * Deletes the bounce records associated with a specific subscriber. Supply the subscriber's numeric `id` to identify whose bounce records to delete.
 *
 * deletes a subscriber's bounce records
 *
 * @param id - subscriber id
 */
export async function deleteSubscriberBouncesById(
  config: ClientConfig,
  { id }: DeleteSubscriberBouncesByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "DELETE",
    path: `/subscribers/${encodePathSegment(id)}/bounces`,
    operationId: "deleteSubscriberBouncesById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface SubscriberSendOptinByIdParams {
  id: number;
}

/**
 * Sends an opt-in confirmation email to a subscriber. Supply the subscriber's numeric `id` to identify the recipient of the confirmation email.
 *
 * sends an optin confirmation e-mail to a subscriber.
 *
 * @param id - sends an optin confirmation e-mail to a subscriber
 */
export async function subscriberSendOptinById(
  config: ClientConfig,
  { id }: SubscriberSendOptinByIdParams,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/subscribers/${encodePathSegment(id)}/optin`,
    operationId: "subscriberSendOptinById",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type DeleteSubscriberByQueryParams = SubscriberQueryRequest;

/**
 * Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
 *
 * bulk deletes based on an arbitrary SQL expression.
 *
 * @param query - Optional `string` value serialized in the `query` wire field.
 * @param ids - The ids of the subscribers to be modified.
 * @param action - Whether to add, remove, or unsubscribe the users.
 * @param targetListIds - The ids of the lists to be modified.
 * @param status - confirmed, unconfirmed, or unsubscribed status.
 */
export async function deleteSubscriberByQuery(
  config: ClientConfig,
  { query, ids, action, targetListIds, status }: DeleteSubscriberByQueryParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/subscribers/query/delete`,
    operationId: "deleteSubscriberByQuery",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      query,
      ids,
      action,
      target_list_ids: targetListIds,
      status,
    },
    config,
  });
  return _resp.data;
}

/**
 * Deletes subscribers selected by an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
 *
 * bulk deletes based on an arbitrary SQL expression.
 */
export async function deleteSubscriberByQueryText(
  config: ClientConfig,
  body: string,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "POST",
    path: `/subscribers/query/delete`,
    operationId: "deleteSubscriberByQueryText",
    responseDecoder: "json",
    ...requestOptions,
    body,
    contentType: "text/plain",
    config,
  });
  return _resp.data;
}

export type BlocklistSubscribersQueryParams = SubscriberQueryRequest;

/**
 * Adds or removes subscribers from the blocklist based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
 *
 * bulk blocklists subscribers based on an arbitrary SQL expression.
 *
 * @param query - Optional `string` value serialized in the `query` wire field.
 * @param ids - The ids of the subscribers to be modified.
 * @param action - Whether to add, remove, or unsubscribe the users.
 * @param targetListIds - The ids of the lists to be modified.
 * @param status - confirmed, unconfirmed, or unsubscribed status.
 */
export async function blocklistSubscribersQuery(
  config: ClientConfig,
  { query, ids, action, targetListIds, status }: BlocklistSubscribersQueryParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/query/blocklist`,
    operationId: "blocklistSubscribersQuery",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      query,
      ids,
      action,
      target_list_ids: targetListIds,
      status,
    },
    config,
  });
  return _resp.data;
}
