// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { SubscriberQueryRequest } from "../../types/subscribers";
import type { ClientConfig, RequestOptions } from "../../client";
import { sdkRequest } from "../../client";

/**
 * Adds or removes subscribers from the blocklist based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and any applicable `action`, `target_list_ids`, or `status` filters.
 *
 * bulk blocklists subscribers based on an arbitrary SQL expression.
 */
export async function blocklistSubscribersQueryText(
  config: ClientConfig,
  body: string,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/query/blocklist`,
    operationId: "blocklistSubscribersQueryText",
    responseDecoder: "json",
    ...requestOptions,
    body,
    contentType: "text/plain",
    config,
  });
  return _resp.data;
}

export type ManageSubscriberListsByQueryParams = SubscriberQueryRequest;

/**
 * Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status` filters.
 *
 * bulk adds/removes/unsubscribes subscribers from one or more lists based on an arbitrary SQL expression.
 *
 * @param query - Optional `string` value serialized in the `query` wire field.
 * @param ids - The ids of the subscribers to be modified.
 * @param action - Whether to add, remove, or unsubscribe the users.
 * @param targetListIds - The ids of the lists to be modified.
 * @param status - confirmed, unconfirmed, or unsubscribed status.
 */
export async function manageSubscriberListsByQuery(
  config: ClientConfig,
  { query, ids, action, targetListIds, status }: ManageSubscriberListsByQueryParams = {},
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/query/lists`,
    operationId: "manageSubscriberListsByQuery",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      query,
      ids,
      action,
      target_list_ids: targetListIds,
      status,
    },
    config,
  });
  return _resp.data;
}

/**
 * Adds, removes, or unsubscribes subscribers from lists based on an SQL expression or subscriber identifiers. Provide the expression as plain text or use a JSON body to specify `query`, `ids`, and the applicable `action`, `target_list_ids`, or `status` filters.
 *
 * bulk adds/removes/unsubscribes subscribers from one or more lists based on an arbitrary SQL expression.
 */
export async function manageSubscriberListsByQueryText(
  config: ClientConfig,
  body: string,
  requestOptions?: RequestOptions,
): Promise<{
  data?: boolean;
}> {
  const _resp = await sdkRequest<{
    data?: boolean;
  }>({
    method: "PUT",
    path: `/subscribers/query/lists`,
    operationId: "manageSubscriberListsByQueryText",
    responseDecoder: "json",
    ...requestOptions,
    body,
    contentType: "text/plain",
    config,
  });
  return _resp.data;
}
