// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  getSubscribers,
  createSubscriber,
  deleteSubscriberByList,
  getSubscriberById,
  updateSubscriberById,
  deleteSubscriberById,
  manageSubscriberLists,
  manageSubscriberListById,
  manageBlocklistBySubscriberList,
  manageBlocklistSubscribersById,
  exportSubscriberDataById,
  getSubscriberBouncesById,
  deleteSubscriberBouncesById,
  subscriberSendOptinById,
  deleteSubscriberByQuery,
  deleteSubscriberByQueryText,
  blocklistSubscribersQuery,
} from "../../../dist/methods/subscribers/part1.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getSubscribers: {
    route: "getSubscribers",
    mediaType: null,
    invoke: (bag) =>
      getSubscribers(config, {
        page: bag["page"],
        perPage: bag["per_page"],
        query: bag["query"],
        orderBy: bag["order_by"],
        order: bag["order"],
        subscriptionStatus: bag["subscription_status"],
        listId: bag["list_id"],
      }),
  },
  createSubscriber: {
    route: "createSubscriber",
    mediaType: "application/json",
    invoke: (bag) =>
      createSubscriber(config, {
        email: bag.__body?.["email"],
        name: bag.__body?.["name"],
        status: bag.__body?.["status"],
        lists: bag.__body?.["lists"],
        listUuids: bag.__body?.["list_uuids"],
        preconfirmSubscriptions: bag.__body?.["preconfirm_subscriptions"],
        attribs: bag.__body?.["attribs"],
      }),
  },
  deleteSubscriberByList: {
    route: "deleteSubscriberByList",
    mediaType: null,
    invoke: (bag) => deleteSubscriberByList(config, { id: bag["id"] }),
  },
  getSubscriberById: {
    route: "getSubscriberById",
    mediaType: null,
    invoke: (bag) => getSubscriberById(config, { id: bag["id"] }),
  },
  updateSubscriberById: {
    route: "updateSubscriberById",
    mediaType: "application/json",
    invoke: (bag) =>
      updateSubscriberById(config, {
        email: bag.__body?.["email"],
        name: bag.__body?.["name"],
        status: bag.__body?.["status"],
        lists: bag.__body?.["lists"],
        listUuids: bag.__body?.["list_uuids"],
        preconfirmSubscriptions: bag.__body?.["preconfirm_subscriptions"],
        attribs: bag.__body?.["attribs"],
        id: bag["id"],
      }),
  },
  deleteSubscriberById: {
    route: "deleteSubscriberById",
    mediaType: null,
    invoke: (bag) => deleteSubscriberById(config, { id: bag["id"] }),
  },
  manageSubscriberLists: {
    route: "manageSubscriberLists",
    mediaType: "application/json",
    invoke: (bag) =>
      manageSubscriberLists(config, {
        query: bag.__body?.["query"],
        ids: bag.__body?.["ids"],
        action: bag.__body?.["action"],
        targetListIds: bag.__body?.["target_list_ids"],
        status: bag.__body?.["status"],
      }),
  },
  manageSubscriberListById: {
    route: "manageSubscriberListById",
    mediaType: "application/json",
    invoke: (bag) =>
      manageSubscriberListById(config, {
        query: bag.__body?.["query"],
        ids: bag.__body?.["ids"],
        action: bag.__body?.["action"],
        targetListIds: bag.__body?.["target_list_ids"],
        status: bag.__body?.["status"],
        id: bag["id"],
      }),
  },
  manageBlocklistBySubscriberList: {
    route: "manageBlocklistBySubscriberList",
    mediaType: "application/json",
    invoke: (bag) =>
      manageBlocklistBySubscriberList(config, {
        query: bag.__body?.["query"],
        ids: bag.__body?.["ids"],
        action: bag.__body?.["action"],
        targetListIds: bag.__body?.["target_list_ids"],
        status: bag.__body?.["status"],
      }),
  },
  manageBlocklistSubscribersById: {
    route: "manageBlocklistSubscribersById",
    mediaType: "application/json",
    invoke: (bag) =>
      manageBlocklistSubscribersById(config, {
        query: bag.__body?.["query"],
        ids: bag.__body?.["ids"],
        action: bag.__body?.["action"],
        targetListIds: bag.__body?.["target_list_ids"],
        status: bag.__body?.["status"],
        id: bag["id"],
      }),
  },
  exportSubscriberDataById: {
    route: "exportSubscriberDataByID",
    mediaType: null,
    invoke: (bag) => exportSubscriberDataById(config, { id: bag["id"] }),
  },
  getSubscriberBouncesById: {
    route: "getSubscriberBouncesById",
    mediaType: null,
    invoke: (bag) => getSubscriberBouncesById(config, { id: bag["id"] }),
  },
  deleteSubscriberBouncesById: {
    route: "deleteSubscriberBouncesById",
    mediaType: null,
    invoke: (bag) => deleteSubscriberBouncesById(config, { id: bag["id"] }),
  },
  subscriberSendOptinById: {
    route: "subscriberSendOptinById",
    mediaType: null,
    invoke: (bag) => subscriberSendOptinById(config, { id: bag["id"] }),
  },
  deleteSubscriberByQuery: {
    route: "deleteSubscriberByQuery",
    mediaType: "application/json",
    invoke: (bag) =>
      deleteSubscriberByQuery(config, {
        query: bag.__body?.["query"],
        ids: bag.__body?.["ids"],
        action: bag.__body?.["action"],
        targetListIds: bag.__body?.["target_list_ids"],
        status: bag.__body?.["status"],
      }),
  },
  deleteSubscriberByQueryText: {
    route: "deleteSubscriberByQuery",
    mediaType: "text/plain",
    invoke: (bag) => deleteSubscriberByQueryText(config, { body: bag.__body }),
  },
  blocklistSubscribersQuery: {
    route: "blocklistSubscribersQuery",
    mediaType: "application/json",
    invoke: (bag) =>
      blocklistSubscribersQuery(config, {
        query: bag.__body?.["query"],
        ids: bag.__body?.["ids"],
        action: bag.__body?.["action"],
        targetListIds: bag.__body?.["target_list_ids"],
        status: bag.__body?.["status"],
      }),
  },
};

test("subscribers/part1 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
