// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, LoggingConfig } from "./client";
import { MiscellaneousNamespace } from "./methods/miscellaneous";
import { SettingsNamespace } from "./methods/settings";
import { AdminNamespace } from "./methods/admin";
import { LogsNamespace } from "./methods/logs";
import { SubscribersNamespace } from "./methods/subscribers";
import { BouncesNamespace } from "./methods/bounces";
import { ListsNamespace } from "./methods/lists";
import { ImportNamespace } from "./methods/import";
import { CampaignsNamespace } from "./methods/campaigns";
import { MediaNamespace } from "./methods/media";
import { TemplatesNamespace } from "./methods/templates";
import { TransactionalNamespace } from "./methods/transactional";
import { MaintenanceNamespace } from "./methods/maintenance";
import { PublicNamespace } from "./methods/public";

export class Listmonk {
  private readonly _config: ClientConfig;
  readonly miscellaneous: MiscellaneousNamespace;
  readonly settings: SettingsNamespace;
  readonly admin: AdminNamespace;
  readonly logs: LogsNamespace;
  readonly subscribers: SubscribersNamespace;
  readonly bounces: BouncesNamespace;
  readonly lists: ListsNamespace;
  readonly import: ImportNamespace;
  readonly campaigns: CampaignsNamespace;
  readonly media: MediaNamespace;
  readonly templates: TemplatesNamespace;
  readonly transactional: TransactionalNamespace;
  readonly maintenance: MaintenanceNamespace;
  readonly public: PublicNamespace;

  constructor(config: ClientConfig) {
    this._config = config;
    this.miscellaneous = new MiscellaneousNamespace(config);
    this.settings = new SettingsNamespace(config);
    this.admin = new AdminNamespace(config);
    this.logs = new LogsNamespace(config);
    this.subscribers = new SubscribersNamespace(config);
    this.bounces = new BouncesNamespace(config);
    this.lists = new ListsNamespace(config);
    this.import = new ImportNamespace(config);
    this.campaigns = new CampaignsNamespace(config);
    this.media = new MediaNamespace(config);
    this.templates = new TemplatesNamespace(config);
    this.transactional = new TransactionalNamespace(config);
    this.maintenance = new MaintenanceNamespace(config);
    this.public = new PublicNamespace(config);
  }

  /**
   * Turns SDK logging on and configures it. Logging is OFF by default — this
   * SDK reports nothing until you call this (or construct the client with
   * `logging: { enabled: true }`). Reports go to the endpoint this build was
   * generated with, or to the `endpoint` you pass; with neither, nothing is sent.
   * Pass `{ enabled: false }` to turn it off.
   */
  setLoggingConfig(config: LoggingConfig): void {
    this._config.logging = { ...this._config.logging, enabled: true, ...config };
  }
}
