// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type * as Types from "./types";
import { fromWire, toWire } from "./client";
import { SdkValidationError } from "./errors";

import { validateDate, validateDateTime } from "./validation";

type RuntimeRecord = Record<string, unknown>;

interface RuntimeSchema {
  ref?: string;
  type?: string | readonly string[];
  nullable?: boolean;
  enum?: readonly unknown[];
  required?: readonly string[];
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  additionalProperties?: RuntimeSchema;
  oneOf?: readonly RuntimeSchema[];
  anyOf?: readonly RuntimeSchema[];
  allOf?: readonly RuntimeSchema[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  multipleOf?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  format?: "email" | "uri" | "uuid" | "date" | "date-time";
}

const modelSchemas: Readonly<Record<string, RuntimeSchema>> = {
  CampaignStats: {
    type: "object",
    properties: {
      id: { type: "integer" },
      status: { type: "string" },
      toSend: { type: "integer" },
      sent: { type: "integer" },
      startedAt: { type: "string", format: "date" },
      updatedAt: { type: "string", format: "date" },
      rate: { type: "integer" },
      netRate: { type: "integer" },
    },
  },
  CampaignAnalyticsCount: {
    type: "object",
    properties: {
      campaignId: { type: "integer" },
      count: { type: "integer" },
      timestamp: { type: "string", format: "date-time" },
    },
  },
  NewTemplate: {
    type: "object",
    required: ["name", "type", "body"],
    properties: {
      name: { type: "string" },
      type: { type: "string" },
      subject: { type: "string" },
      bodySource: { type: "string" },
      body: { type: "string" },
    },
  },
};

const isRecord = (value: unknown): value is RuntimeRecord =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const childField = (field: string, property: string): string =>
  field ? `${field}.${property}` : property;

const hasType = (schema: RuntimeSchema, type: string): boolean =>
  schema.type === type || (Array.isArray(schema.type) && schema.type.includes(type));

const allowsNull = (schema: RuntimeSchema | undefined, seen = new Set<string>()): boolean => {
  if (!schema) return false;
  if (schema.nullable === true || hasType(schema, "null")) return true;
  if (!schema.ref || seen.has(schema.ref)) return false;
  seen.add(schema.ref);
  const referenced = modelSchemas[schema.ref];
  return referenced ? allowsNull(referenced, seen) : false;
};

const validationFailure = (field: string, code: "required", message: string): never => {
  throw new SdkValidationError(field, code, message);
};

const validateNode = (value: unknown, schema: RuntimeSchema, field: string): unknown => {
  if (schema.ref) {
    const referenced = modelSchemas[schema.ref];
    return referenced ? validateNode(value, referenced, field) : value;
  }

  if (value === null) {
    if (schema.nullable === true || hasType(schema, "null")) return value;
    return value;
  }

  if (schema.allOf) {
    for (const member of schema.allOf) validateNode(value, member, field);
  }

  if (schema.oneOf || schema.anyOf) {
    const members = schema.oneOf ?? schema.anyOf ?? [];
    let firstError: unknown;
    for (const member of members) {
      try {
        return validateNode(value, member, field);
      } catch (error) {
        firstError ??= error;
      }
    }
    if (firstError instanceof Error) throw firstError;
  }

  if (hasType(schema, "object") || schema.properties) {
    if (!isRecord(value)) return value;
    for (const property of schema.required ?? []) {
      const propertyValue = value[property];
      const propertySchema = schema.properties?.[property];
      const missing =
        !Object.prototype.hasOwnProperty.call(value, property) || propertyValue === undefined;
      const invalidNull = propertyValue === null && !allowsNull(propertySchema);
      if (missing || invalidNull) {
        validationFailure(
          childField(field, property),
          "required",
          `Validation failed for '${childField(field, property)}': value is required`,
        );
      }
    }
    for (const [property, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.prototype.hasOwnProperty.call(value, property)) {
        validateNode(value[property], propertySchema, childField(field, property));
      }
    }
    if (schema.additionalProperties) {
      for (const [property, propertyValue] of Object.entries(value)) {
        if (!(property in (schema.properties ?? {}))) {
          validateNode(propertyValue, schema.additionalProperties, childField(field, property));
        }
      }
    }
  }

  if (hasType(schema, "array")) {
    if (!Array.isArray(value)) return value;
    if (schema.items) {
      value.forEach((item, index) =>
        validateNode(item, schema.items as RuntimeSchema, childField(field, String(index))),
      );
    }
  }

  if (schema.format === "date") validateDate(field, value as string);

  if (schema.format === "date-time") validateDateTime(field, value as string);

  return value;
};

const validateModel = <T>(value: T, typeName: string): T => {
  const schema = modelSchemas[typeName];
  return schema ? (validateNode(value, schema, "") as T) : value;
};

export const modelConstructionStyle = "typed-record" as const;

/** Constructs a validated LanguagePack model value. */
export function createLanguagePack(value: Types.LanguagePack): Types.LanguagePack {
  return validateModel({ ...value }, "LanguagePack");
}

/** Constructs a validated ServerConfig model value. */
export function createServerConfig(value: Types.ServerConfig): Types.ServerConfig {
  return validateModel({ ...value }, "ServerConfig");
}

/** Constructs a validated DashboardChart model value. */
export function createDashboardChart(value: Types.DashboardChart): Types.DashboardChart {
  return validateModel({ ...value }, "DashboardChart");
}

/** Constructs a validated DashboardCount model value. */
export function createDashboardCount(value: Types.DashboardCount): Types.DashboardCount {
  return validateModel({ ...value }, "DashboardCount");
}

/** Constructs a validated SMTPSettings model value. */
export function createSMTPSettings(value: Types.SMTPSettings): Types.SMTPSettings {
  return validateModel({ ...value }, "SMTPSettings");
}

/** Constructs a validated SMTPTest model value. */
export function createSMTPTest(value: Types.SMTPTest): Types.SMTPTest {
  return validateModel({ ...value }, "SMTPTest");
}

/** Constructs a validated MailBoxBounces model value. */
export function createMailBoxBounces(value: Types.MailBoxBounces): Types.MailBoxBounces {
  return validateModel({ ...value }, "MailBoxBounces");
}

/** Constructs a validated Settings model value. */
export function createSettings(value: Types.Settings): Types.Settings {
  return validateModel({ ...value }, "Settings");
}

/** Constructs a validated SubscriberProfile model value. */
export function createSubscriberProfile(value: Types.SubscriberProfile): Types.SubscriberProfile {
  return validateModel({ ...value }, "SubscriberProfile");
}

/** Constructs a validated Subscriptions model value. */
export function createSubscriptions(value: Types.Subscriptions): Types.Subscriptions {
  return validateModel({ ...value }, "Subscriptions");
}

/** Constructs a validated SubscriberData model value. */
export function createSubscriberData(value: Types.SubscriberData): Types.SubscriberData {
  return validateModel({ ...value }, "SubscriberData");
}

/** Constructs a validated Subscriber model value. */
export function createSubscriberModel(value: Types.Subscriber): Types.Subscriber {
  return validateModel({ ...value }, "Subscriber");
}

/** Constructs a validated NewSubscriber model value. */
export function createNewSubscriber(value: Types.NewSubscriber): Types.NewSubscriber {
  return validateModel({ ...value }, "NewSubscriber");
}

/** Constructs a validated UpdateSubscriber model value. */
export function createUpdateSubscriber(value: Types.UpdateSubscriber): Types.UpdateSubscriber {
  return validateModel({ ...value }, "UpdateSubscriber");
}

/** Constructs a validated SubscriberQueryRequest model value. */
export function createSubscriberQueryRequest(
  value: Types.SubscriberQueryRequest,
): Types.SubscriberQueryRequest {
  return validateModel({ ...value }, "SubscriberQueryRequest");
}

/** Constructs a validated Bounce model value. */
export function createBounce(value: Types.Bounce): Types.Bounce {
  return validateModel({ ...value }, "Bounce");
}

/** Constructs a validated ListModel model value. */
export function createListModel(value: Types.ListModel): Types.ListModel {
  return validateModel({ ...value }, "ListModel");
}

/** Constructs a validated NewList model value. */
export function createNewList(value: Types.NewList): Types.NewList {
  return validateModel({ ...value }, "NewList");
}

/** Constructs a validated ImportStatus model value. */
export function createImportStatus(value: Types.ImportStatus): Types.ImportStatus {
  return validateModel({ ...value }, "ImportStatus");
}

/** Constructs a validated Campaign model value. */
export function createCampaignModel(value: Types.Campaign): Types.Campaign {
  return validateModel({ ...value }, "Campaign");
}

/** Constructs a validated CampaignContentRequest model value. */
export function createCampaignContentRequest(
  value: Types.CampaignContentRequest,
): Types.CampaignContentRequest {
  return validateModel({ ...value }, "CampaignContentRequest");
}

/** Constructs a validated CampaignRequest model value. */
export function createCampaignRequest(value: Types.CampaignRequest): Types.CampaignRequest {
  return validateModel({ ...value }, "CampaignRequest");
}

/** Constructs a validated CampaignUpdate model value. */
export function createCampaignUpdate(value: Types.CampaignUpdate): Types.CampaignUpdate {
  return validateModel({ ...value }, "CampaignUpdate");
}

/** Constructs a validated CampaignStats model value. */
export function createCampaignStats(value: Types.CampaignStats): Types.CampaignStats {
  return validateModel({ ...value }, "CampaignStats");
}

/** Constructs a validated CampaignAnalyticsCount model value. */
export function createCampaignAnalyticsCount(
  value: Types.CampaignAnalyticsCount,
): Types.CampaignAnalyticsCount {
  return validateModel({ ...value }, "CampaignAnalyticsCount");
}

/** Constructs a validated MediaFileObject model value. */
export function createMediaFileObject(value: Types.MediaFileObject): Types.MediaFileObject {
  return validateModel({ ...value }, "MediaFileObject");
}

/** Constructs a validated Template model value. */
export function createTemplateModel(value: Types.Template): Types.Template {
  return validateModel({ ...value }, "Template");
}

/** Constructs a validated NewTemplate model value. */
export function createNewTemplate(value: Types.NewTemplate): Types.NewTemplate {
  return validateModel({ ...value }, "NewTemplate");
}

/** Constructs a validated UpdateTemplate model value. */
export function createUpdateTemplate(value: Types.UpdateTemplate): Types.UpdateTemplate {
  return validateModel({ ...value }, "UpdateTemplate");
}

/** Constructs a validated TransactionalMessage model value. */
export function createTransactionalMessage(
  value: Types.TransactionalMessage,
): Types.TransactionalMessage {
  return validateModel({ ...value }, "TransactionalMessage");
}

/** Serializes a constructed model using the generated wire-name mapping. */
export function serializeModel<T>(value: T, typeName: string): unknown {
  return toWire(validateModel(value, typeName), typeName);
}

/** Decodes and validates a wire model through the generated public surface. */
export function deserializeModel<T>(value: unknown, typeName: string): T {
  return validateModel<T>(fromWire(value, typeName) as T, typeName);
}
